-- Generated by scripts/ci/forensic-data-audit.ts --print-sql. Read only.
-- Identifiers only; hashed provider references. No automatic reconciliation.
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
START TRANSACTION READ ONLY;
-- booking_missing_owner (error; owner: bookings)
SELECT /*+ MAX_EXECUTION_TIME(5000) */ 'booking_missing_owner' AS finding, COUNT(*) AS total FROM (SELECT b.id AS recordId FROM bookings b LEFT JOIN users u ON u.id = b.userId WHERE b.userId <= 0 OR u.id IS NULL) findings;
SELECT /*+ MAX_EXECUTION_TIME(5000) */ 'booking_missing_owner' AS finding, recordId FROM (SELECT b.id AS recordId FROM bookings b LEFT JOIN users u ON u.id = b.userId WHERE b.userId <= 0 OR u.id IS NULL) findings ORDER BY recordId LIMIT 50;
-- legacy_tenant_unassigned (review; owner: tenant)
SELECT /*+ MAX_EXECUTION_TIME(5000) */ 'legacy_tenant_unassigned' AS finding, COUNT(*) AS total FROM (SELECT id AS recordId FROM bookings WHERE tenantId IS NULL) findings;
SELECT /*+ MAX_EXECUTION_TIME(5000) */ 'legacy_tenant_unassigned' AS finding, recordId FROM (SELECT id AS recordId FROM bookings WHERE tenantId IS NULL) findings ORDER BY recordId LIMIT 50;
-- agency_without_owner (error; owner: travel-agent)
SELECT /*+ MAX_EXECUTION_TIME(5000) */ 'agency_without_owner' AS finding, COUNT(*) AS total FROM (SELECT a.id AS recordId FROM travel_agents a LEFT JOIN users u ON u.id = a.ownerUserId WHERE a.ownerUserId IS NULL OR u.id IS NULL) findings;
SELECT /*+ MAX_EXECUTION_TIME(5000) */ 'agency_without_owner' AS finding, recordId FROM (SELECT a.id AS recordId FROM travel_agents a LEFT JOIN users u ON u.id = a.ownerUserId WHERE a.ownerUserId IS NULL OR u.id IS NULL) findings ORDER BY recordId LIMIT 50;
-- passenger_count_mismatch (error; owner: bookings)
SELECT /*+ MAX_EXECUTION_TIME(5000) */ 'passenger_count_mismatch' AS finding, COUNT(*) AS total FROM (SELECT b.id AS recordId FROM bookings b LEFT JOIN passengers p ON p.bookingId = b.id GROUP BY b.id, b.numberOfPassengers HAVING COUNT(p.id) <> b.numberOfPassengers) findings;
SELECT /*+ MAX_EXECUTION_TIME(5000) */ 'passenger_count_mismatch' AS finding, recordId FROM (SELECT b.id AS recordId FROM bookings b LEFT JOIN passengers p ON p.bookingId = b.id GROUP BY b.id, b.numberOfPassengers HAVING COUNT(p.id) <> b.numberOfPassengers) findings ORDER BY recordId LIMIT 50;
-- orphan_passenger (error; owner: bookings)
SELECT /*+ MAX_EXECUTION_TIME(5000) */ 'orphan_passenger' AS finding, COUNT(*) AS total FROM (SELECT p.id AS recordId FROM passengers p LEFT JOIN bookings b ON b.id = p.bookingId WHERE b.id IS NULL) findings;
SELECT /*+ MAX_EXECUTION_TIME(5000) */ 'orphan_passenger' AS finding, recordId FROM (SELECT p.id AS recordId FROM passengers p LEFT JOIN bookings b ON b.id = p.bookingId WHERE b.id IS NULL) findings ORDER BY recordId LIMIT 50;
-- segment_reservation_mismatch (error; owner: booking-settlement)
SELECT /*+ MAX_EXECUTION_TIME(5000) */ 'segment_reservation_mismatch' AS finding, COUNT(*) AS total FROM (SELECT b.id AS recordId FROM bookings b JOIN booking_segments s ON s.bookingId = b.id WHERE b.paymentStatus = 'paid' AND b.status = 'confirmed' GROUP BY b.id, b.seatsReserved HAVING SUM(s.seatsReserved) <> COUNT(s.id) OR b.seatsReserved = 0) findings;
SELECT /*+ MAX_EXECUTION_TIME(5000) */ 'segment_reservation_mismatch' AS finding, recordId FROM (SELECT b.id AS recordId FROM bookings b JOIN booking_segments s ON s.bookingId = b.id WHERE b.paymentStatus = 'paid' AND b.status = 'confirmed' GROUP BY b.id, b.seatsReserved HAVING SUM(s.seatsReserved) <> COUNT(s.id) OR b.seatsReserved = 0) findings ORDER BY recordId LIMIT 50;
-- segment_allocation_mismatch (error; owner: booking-settlement)
SELECT /*+ MAX_EXECUTION_TIME(5000) */ 'segment_allocation_mismatch' AS finding, COUNT(*) AS total FROM (SELECT b.id AS recordId FROM bookings b JOIN booking_segments s ON s.bookingId = b.id GROUP BY b.id, b.totalAmount HAVING COUNT(s.segmentAmount) <> COUNT(s.id) OR SUM(s.segmentAmount) <> b.totalAmount) findings;
SELECT /*+ MAX_EXECUTION_TIME(5000) */ 'segment_allocation_mismatch' AS finding, recordId FROM (SELECT b.id AS recordId FROM bookings b JOIN booking_segments s ON s.bookingId = b.id GROUP BY b.id, b.totalAmount HAVING COUNT(s.segmentAmount) <> COUNT(s.id) OR SUM(s.segmentAmount) <> b.totalAmount) findings ORDER BY recordId LIMIT 50;
-- segment_identity_mismatch (error; owner: multi-city)
SELECT /*+ MAX_EXECUTION_TIME(5000) */ 'segment_identity_mismatch' AS finding, COUNT(*) AS total FROM (SELECT s.id AS recordId FROM booking_segments s LEFT JOIN bookings b ON b.id = s.bookingId LEFT JOIN flights f ON f.id = s.flightId WHERE b.id IS NULL OR f.id IS NULL OR NOT (b.tenantId <=> f.tenantId)) findings;
SELECT /*+ MAX_EXECUTION_TIME(5000) */ 'segment_identity_mismatch' AS finding, recordId FROM (SELECT s.id AS recordId FROM booking_segments s LEFT JOIN bookings b ON b.id = s.bookingId LEFT JOIN flights f ON f.id = s.flightId WHERE b.id IS NULL OR f.id IS NULL OR NOT (b.tenantId <=> f.tenantId)) findings ORDER BY recordId LIMIT 50;
-- invoice_ancillary_inconsistency (error; owner: bookings)
SELECT /*+ MAX_EXECUTION_TIME(5000) */ 'invoice_ancillary_inconsistency' AS finding, COUNT(*) AS total FROM (SELECT b.id AS recordId FROM bookings b JOIN booking_ancillaries a ON a.bookingId = b.id AND a.status = 'active' GROUP BY b.id, b.totalAmount HAVING SUM(a.totalPrice) > b.totalAmount OR SUM(a.quantity <= 0 OR a.unitPrice < 0 OR a.totalPrice <> a.quantity * a.unitPrice) > 0) findings;
SELECT /*+ MAX_EXECUTION_TIME(5000) */ 'invoice_ancillary_inconsistency' AS finding, recordId FROM (SELECT b.id AS recordId FROM bookings b JOIN booking_ancillaries a ON a.bookingId = b.id AND a.status = 'active' GROUP BY b.id, b.totalAmount HAVING SUM(a.totalPrice) > b.totalAmount OR SUM(a.quantity <= 0 OR a.unitPrice < 0 OR a.totalPrice <> a.quantity * a.unitPrice) > 0) findings ORDER BY recordId LIMIT 50;
-- booking_flight_tenant_mismatch (error; owner: tenant)
SELECT /*+ MAX_EXECUTION_TIME(5000) */ 'booking_flight_tenant_mismatch' AS finding, COUNT(*) AS total FROM (SELECT b.id AS recordId FROM bookings b LEFT JOIN flights f ON f.id = b.flightId WHERE f.id IS NULL OR NOT (b.tenantId <=> f.tenantId)) findings;
SELECT /*+ MAX_EXECUTION_TIME(5000) */ 'booking_flight_tenant_mismatch' AS finding, recordId FROM (SELECT b.id AS recordId FROM bookings b LEFT JOIN flights f ON f.id = b.flightId WHERE f.id IS NULL OR NOT (b.tenantId <=> f.tenantId)) findings ORDER BY recordId LIMIT 50;
-- passenger_tenant_mismatch (error; owner: tenant)
SELECT /*+ MAX_EXECUTION_TIME(5000) */ 'passenger_tenant_mismatch' AS finding, COUNT(*) AS total FROM (SELECT p.id AS recordId FROM passengers p JOIN bookings b ON b.id = p.bookingId WHERE NOT (p.tenantId <=> b.tenantId)) findings;
SELECT /*+ MAX_EXECUTION_TIME(5000) */ 'passenger_tenant_mismatch' AS finding, recordId FROM (SELECT p.id AS recordId FROM passengers p JOIN bookings b ON b.id = p.bookingId WHERE NOT (p.tenantId <=> b.tenantId)) findings ORDER BY recordId LIMIT 50;
-- unlinked_legacy_hold (review; owner: inventory-capacity)
SELECT /*+ MAX_EXECUTION_TIME(5000) */ 'unlinked_legacy_hold' AS finding, COUNT(*) AS total FROM (SELECT id AS recordId FROM seat_holds WHERE inventoryLockId IS NULL AND status = 'active') findings;
SELECT /*+ MAX_EXECUTION_TIME(5000) */ 'unlinked_legacy_hold' AS finding, recordId FROM (SELECT id AS recordId FROM seat_holds WHERE inventoryLockId IS NULL AND status = 'active') findings ORDER BY recordId LIMIT 50;
-- collected_funds_under_review (error; owner: payment-settlement)
SELECT /*+ MAX_EXECUTION_TIME(5000) */ 'collected_funds_under_review' AS finding, COUNT(*) AS total FROM (SELECT SHA2(paymentIntentId, 256) AS recordId FROM payment_receipts WHERE settlementStatus = 'review_required') findings;
SELECT /*+ MAX_EXECUTION_TIME(5000) */ 'collected_funds_under_review' AS finding, recordId FROM (SELECT SHA2(paymentIntentId, 256) AS recordId FROM payment_receipts WHERE settlementStatus = 'review_required') findings ORDER BY recordId LIMIT 50;
-- terminal_booking_retains_resources (error; owner: booking-settlement)
SELECT /*+ MAX_EXECUTION_TIME(5000) */ 'terminal_booking_retains_resources' AS finding, COUNT(*) AS total FROM (SELECT b.id AS recordId FROM bookings b WHERE b.status = 'cancelled' AND (b.seatsReserved = 1 OR EXISTS (SELECT 1 FROM booking_segments s WHERE s.bookingId = b.id AND (s.seatsReserved = 1 OR s.status <> 'cancelled')) OR EXISTS (SELECT 1 FROM seat_inventory si WHERE si.bookingId = b.id))) findings;
SELECT /*+ MAX_EXECUTION_TIME(5000) */ 'terminal_booking_retains_resources' AS finding, recordId FROM (SELECT b.id AS recordId FROM bookings b WHERE b.status = 'cancelled' AND (b.seatsReserved = 1 OR EXISTS (SELECT 1 FROM booking_segments s WHERE s.bookingId = b.id AND (s.seatsReserved = 1 OR s.status <> 'cancelled')) OR EXISTS (SELECT 1 FROM seat_inventory si WHERE si.bookingId = b.id))) findings ORDER BY recordId LIMIT 50;
-- ndc_booking_status_mismatch (error; owner: ndc)
SELECT /*+ MAX_EXECUTION_TIME(5000) */ 'ndc_booking_status_mismatch' AS finding, COUNT(*) AS total FROM (SELECT n.id AS recordId FROM ndc_orders n LEFT JOIN bookings b ON b.id = n.bookingId WHERE b.id IS NULL OR n.totalAmount <> b.totalAmount OR (b.paymentStatus = 'refunded' AND n.status <> 'refunded') OR (b.status = 'cancelled' AND n.status NOT IN ('cancelled','refunded')) OR (b.status = 'confirmed' AND b.paymentStatus = 'paid' AND n.status = 'pending')) findings;
SELECT /*+ MAX_EXECUTION_TIME(5000) */ 'ndc_booking_status_mismatch' AS finding, recordId FROM (SELECT n.id AS recordId FROM ndc_orders n LEFT JOIN bookings b ON b.id = n.bookingId WHERE b.id IS NULL OR n.totalAmount <> b.totalAmount OR (b.paymentStatus = 'refunded' AND n.status <> 'refunded') OR (b.status = 'cancelled' AND n.status NOT IN ('cancelled','refunded')) OR (b.status = 'confirmed' AND b.paymentStatus = 'paid' AND n.status = 'pending')) findings ORDER BY recordId LIMIT 50;
ROLLBACK;
