// Explicit response field allowlists. Review contract changes with producers and consumers.
import { z } from "zod";
import { outputNumber, structuredValue } from "./primitives";
export const responseContracts = {
  createFlight: z.object({ success: z.boolean(), flightId: outputNumber }),
  updateFlightAvailability: z.object({ success: z.boolean() }),
  getAllBookings: z.array(
    z.object({
      id: outputNumber,
      bookingReference: z.string(),
      pnr: z.string(),
      status: z.enum(["cancelled", "completed", "pending", "confirmed"]),
      totalAmount: outputNumber,
      paymentStatus: z.enum(["pending", "paid", "refunded", "failed"]),
      cabinClass: z.enum(["economy", "business"]),
      numberOfPassengers: outputNumber,
      createdAt: z.date(),
      user: z.object({
        name: z.union([z.null(), z.string()]),
        email: z.union([z.null(), z.string()]),
      }),
      flight: z.object({
        flightNumber: z.string(),
        departureTime: z.date(),
        origin: z.string(),
        destination: z.string(),
      }),
    })
  ),
  updateBookingStatus: z.object({ success: z.boolean() }),
  updateFlightStatus: z.object({
    success: z.boolean(),
    affectedBookings: outputNumber,
  }),
  cancelFlightAndRefund: z.object({
    requestedBookings: outputNumber,
    pendingBookings: outputNumber,
    reviewRequiredBookings: outputNumber,
    success: z.boolean(),
    refundedBookings: outputNumber,
    completedBookings: outputNumber,
  }),
  getMetrics: z.object({
    period: z.object({
      start: z.date(),
      end: z.date(),
      durationHours: outputNumber,
    }),
    funnel: z.object({
      searches: outputNumber,
      bookingsStarted: outputNumber,
      bookingsCompleted: outputNumber,
      paymentsSuccessful: outputNumber,
      searchToBookingRate: outputNumber,
      bookingToPaymentRate: outputNumber,
      overallConversionRate: outputNumber,
    }),
    payments: z.object({
      totalAttempts: outputNumber,
      successful: outputNumber,
      failed: outputNumber,
      successRate: outputNumber,
      failureRate: outputNumber,
      averageAmount: outputNumber,
      totalRevenue: outputNumber,
      byPaymentMethod: z.record(
        z.string(),
        z.object({ count: outputNumber, amount: outputNumber })
      ),
    }),
    refunds: z.object({
      totalRefunds: outputNumber,
      totalRefundAmount: outputNumber,
      averageRefundAmount: outputNumber,
      refundRate: outputNumber,
      byReason: z.record(z.string(), outputNumber),
    }),
    revenue: z.object({
      totalRevenue: outputNumber,
      netRevenue: outputNumber,
      averageBookingValue: outputNumber,
      revenueByClass: z.object({
        economy: outputNumber,
        business: outputNumber,
      }),
      revenueByHour: z.record(z.string(), outputNumber),
    }),
    engagement: z.object({
      totalLogins: outputNumber,
      uniqueUsers: outputNumber,
      newRegistrations: outputNumber,
      searchesPerUser: outputNumber,
      bookingsPerUser: outputNumber,
      returnUserRate: outputNumber,
    }),
    eventCounts: z.object({
      search_performed: outputNumber,
      booking_started: outputNumber,
      booking_completed: outputNumber,
      booking_cancelled: outputNumber,
      payment_initiated: outputNumber,
      payment_success: outputNumber,
      payment_failed: outputNumber,
      refund_issued: outputNumber,
      user_login: outputNumber,
      user_registration: outputNumber,
    }),
    recentEvents: z.array(
      z.object({
        type: z.enum([
          "search_performed",
          "booking_started",
          "booking_completed",
          "booking_cancelled",
          "payment_initiated",
          "payment_success",
          "payment_failed",
          "refund_issued",
          "user_login",
          "user_registration",
        ]),
        timestamp: z.date(),
        userId: z.union([z.undefined(), outputNumber]).optional(),
        sessionId: z.union([z.undefined(), z.string()]).optional(),
        metadata: z
          .union([z.undefined(), z.record(z.string(), structuredValue)])
          .optional(),
      })
    ),
    timeSeries: z.object({
      searches: z.array(
        z.object({ timestamp: z.string(), value: outputNumber })
      ),
      bookings: z.array(
        z.object({ timestamp: z.string(), value: outputNumber })
      ),
      revenue: z.array(
        z.object({ timestamp: z.string(), value: outputNumber })
      ),
    }),
  }),
  getMetricsSummary: z.object({
    period: z.object({ start: z.date(), end: z.date() }),
    totalSearches: outputNumber,
    totalBookings: outputNumber,
    totalRevenue: outputNumber,
    conversionRate: outputNumber,
    paymentSuccessRate: outputNumber,
  }),
  getRealTimeStats: z.object({
    searchesPerMinute: outputNumber,
    bookingsPerMinute: outputNumber,
    revenuePerMinute: outputNumber,
    activeUsers: outputNumber,
  }),
  getMetricsInfo: z.object({ eventCount: outputNumber, timestamp: z.date() }),
  flushMetrics: z.object({ success: z.boolean(), flushedEvents: outputNumber }),
  getAuditLogs: z.object({
    logs: z.array(
      z.object({
        id: outputNumber,
        createdAt: z.date(),
        userId: z.union([z.null(), outputNumber]),
        eventType: z.string(),
        eventCategory: z.enum([
          "booking",
          "modification",
          "payment",
          "auth",
          "user_management",
          "flight_management",
          "refund",
          "access",
          "system",
        ]),
        outcome: z.enum(["error", "success", "failure"]),
        severity: z.enum(["high", "medium", "low", "critical"]),
        resourceType: z.union([z.null(), z.string()]),
        resourceId: z.union([z.null(), z.string()]),
        timestamp: z.date(),
        eventId: z.string(),
        userRole: z.union([z.null(), z.string()]),
        actorType: z.enum(["user", "admin", "system", "api"]),
        sourceIp: z.union([z.null(), z.string()]),
        userAgent: z.union([z.null(), z.string()]),
        requestId: z.union([z.null(), z.string()]),
        previousValue: z.union([z.null(), z.string()]),
        newValue: z.union([z.null(), z.string()]),
        changeDescription: z.union([z.null(), z.string()]),
        metadata: z.union([z.null(), z.string()]),
      })
    ),
    total: outputNumber,
    limit: outputNumber,
    offset: outputNumber,
  }),
  getAuditLogById: z.object({
    id: outputNumber,
    createdAt: z.date(),
    userId: z.union([z.null(), outputNumber]),
    eventType: z.string(),
    eventCategory: z.enum([
      "booking",
      "modification",
      "payment",
      "auth",
      "user_management",
      "flight_management",
      "refund",
      "access",
      "system",
    ]),
    outcome: z.enum(["error", "success", "failure"]),
    severity: z.enum(["high", "medium", "low", "critical"]),
    resourceType: z.union([z.null(), z.string()]),
    resourceId: z.union([z.null(), z.string()]),
    timestamp: z.date(),
    eventId: z.string(),
    userRole: z.union([z.null(), z.string()]),
    actorType: z.enum(["user", "admin", "system", "api"]),
    sourceIp: z.union([z.null(), z.string()]),
    userAgent: z.union([z.null(), z.string()]),
    requestId: z.union([z.null(), z.string()]),
    previousValue: z.union([z.null(), z.string()]),
    newValue: z.union([z.null(), z.string()]),
    changeDescription: z.union([z.null(), z.string()]),
    metadata: z.union([z.null(), z.string()]),
  }),
  getAuditLogsForResource: z.array(
    z.object({
      id: outputNumber,
      createdAt: z.date(),
      userId: z.union([z.null(), outputNumber]),
      eventType: z.string(),
      eventCategory: z.enum([
        "booking",
        "modification",
        "payment",
        "auth",
        "user_management",
        "flight_management",
        "refund",
        "access",
        "system",
      ]),
      outcome: z.enum(["error", "success", "failure"]),
      severity: z.enum(["high", "medium", "low", "critical"]),
      resourceType: z.union([z.null(), z.string()]),
      resourceId: z.union([z.null(), z.string()]),
      timestamp: z.date(),
      eventId: z.string(),
      userRole: z.union([z.null(), z.string()]),
      actorType: z.enum(["user", "admin", "system", "api"]),
      sourceIp: z.union([z.null(), z.string()]),
      userAgent: z.union([z.null(), z.string()]),
      requestId: z.union([z.null(), z.string()]),
      previousValue: z.union([z.null(), z.string()]),
      newValue: z.union([z.null(), z.string()]),
      changeDescription: z.union([z.null(), z.string()]),
      metadata: z.union([z.null(), z.string()]),
    })
  ),
  getAuditLogsForUser: z.array(
    z.object({
      id: outputNumber,
      createdAt: z.date(),
      userId: z.union([z.null(), outputNumber]),
      eventType: z.string(),
      eventCategory: z.enum([
        "booking",
        "modification",
        "payment",
        "auth",
        "user_management",
        "flight_management",
        "refund",
        "access",
        "system",
      ]),
      outcome: z.enum(["error", "success", "failure"]),
      severity: z.enum(["high", "medium", "low", "critical"]),
      resourceType: z.union([z.null(), z.string()]),
      resourceId: z.union([z.null(), z.string()]),
      timestamp: z.date(),
      eventId: z.string(),
      userRole: z.union([z.null(), z.string()]),
      actorType: z.enum(["user", "admin", "system", "api"]),
      sourceIp: z.union([z.null(), z.string()]),
      userAgent: z.union([z.null(), z.string()]),
      requestId: z.union([z.null(), z.string()]),
      previousValue: z.union([z.null(), z.string()]),
      newValue: z.union([z.null(), z.string()]),
      changeDescription: z.union([z.null(), z.string()]),
      metadata: z.union([z.null(), z.string()]),
    })
  ),
  getHighSeverityEvents: z.array(
    z.object({
      id: outputNumber,
      createdAt: z.date(),
      userId: z.union([z.null(), outputNumber]),
      eventType: z.string(),
      eventCategory: z.enum([
        "booking",
        "modification",
        "payment",
        "auth",
        "user_management",
        "flight_management",
        "refund",
        "access",
        "system",
      ]),
      outcome: z.enum(["error", "success", "failure"]),
      severity: z.enum(["high", "medium", "low", "critical"]),
      resourceType: z.union([z.null(), z.string()]),
      resourceId: z.union([z.null(), z.string()]),
      timestamp: z.date(),
      eventId: z.string(),
      userRole: z.union([z.null(), z.string()]),
      actorType: z.enum(["user", "admin", "system", "api"]),
      sourceIp: z.union([z.null(), z.string()]),
      userAgent: z.union([z.null(), z.string()]),
      requestId: z.union([z.null(), z.string()]),
      previousValue: z.union([z.null(), z.string()]),
      newValue: z.union([z.null(), z.string()]),
      changeDescription: z.union([z.null(), z.string()]),
      metadata: z.union([z.null(), z.string()]),
    })
  ),
  getAuditLogStats: z.object({
    totalEvents: outputNumber,
    eventsByCategory: z.record(z.string(), outputNumber),
    eventsByOutcome: z.record(z.string(), outputNumber),
    eventsBySeverity: z.record(z.string(), outputNumber),
    recentHighSeverityCount: outputNumber,
  }),
};
