// Explicit response field allowlists. Review contract changes with producers and consumers.
import { z } from "zod";
import { outputNumber, structuredValue } from "./primitives";
export const responseContracts = {
  getAvailable: z.array(
    z.object({
      id: outputNumber,
      code: z.string(),
      category: z.enum([
        "baggage",
        "meal",
        "seat",
        "insurance",
        "lounge",
        "priority_boarding",
      ]),
      name: z.string(),
      description: z.union([z.null(), z.string()]),
      price: outputNumber,
      currency: z.string(),
      available: z.boolean(),
      applicableCabinClasses: z.union([z.null(), z.string()]),
      applicableAirlines: z.union([z.null(), z.string()]),
      icon: z.union([z.null(), z.string()]),
      createdAt: z.date(),
      updatedAt: z.date(),
    })
  ),
  getByCategory: z.array(
    z.object({
      id: outputNumber,
      code: z.string(),
      category: z.enum([
        "baggage",
        "meal",
        "seat",
        "insurance",
        "lounge",
        "priority_boarding",
      ]),
      name: z.string(),
      description: z.union([z.null(), z.string()]),
      price: outputNumber,
      currency: z.string(),
      available: z.boolean(),
      applicableCabinClasses: z.union([z.null(), z.string()]),
      applicableAirlines: z.union([z.null(), z.string()]),
      icon: z.union([z.null(), z.string()]),
      createdAt: z.date(),
      updatedAt: z.date(),
    })
  ),
  getById: z.object({
    id: outputNumber,
    code: z.string(),
    category: z.enum([
      "baggage",
      "meal",
      "seat",
      "insurance",
      "lounge",
      "priority_boarding",
    ]),
    name: z.string(),
    description: z.union([z.null(), z.string()]),
    price: outputNumber,
    currency: z.string(),
    available: z.boolean(),
    applicableCabinClasses: z.union([z.null(), z.string()]),
    applicableAirlines: z.union([z.null(), z.string()]),
    icon: z.union([z.null(), z.string()]),
    createdAt: z.date(),
    updatedAt: z.date(),
  }),
  addToBooking: z.object({
    id: outputNumber,
    totalPrice: outputNumber,
    service: z.object({
      id: outputNumber,
      code: z.string(),
      category: z.enum([
        "baggage",
        "meal",
        "seat",
        "insurance",
        "lounge",
        "priority_boarding",
      ]),
      name: z.string(),
      description: z.union([z.null(), z.string()]),
      price: outputNumber,
      currency: z.string(),
      available: z.boolean(),
      applicableCabinClasses: z.union([z.null(), z.string()]),
      applicableAirlines: z.union([z.null(), z.string()]),
      icon: z.union([z.null(), z.string()]),
      createdAt: z.date(),
      updatedAt: z.date(),
    }),
  }),
  getBookingAncillaries: z.array(
    z.object({
      metadata: structuredValue,
      id: outputNumber,
      bookingId: outputNumber,
      passengerId: z.union([z.null(), outputNumber]),
      quantity: outputNumber,
      unitPrice: outputNumber,
      totalPrice: outputNumber,
      status: z.enum(["cancelled", "active", "refunded"]),
      createdAt: z.date(),
      service: z.union([
        z.null(),
        z.object({
          id: outputNumber,
          code: z.string(),
          category: z.enum([
            "baggage",
            "meal",
            "seat",
            "insurance",
            "lounge",
            "priority_boarding",
          ]),
          name: z.string(),
          description: z.union([z.null(), z.string()]),
          icon: z.union([z.null(), z.string()]),
        }),
      ]),
    })
  ),
  removeFromBooking: z.boolean(),
  calculateTotal: z.object({ total: outputNumber }),
  adminCreate: z.object({ id: outputNumber, success: z.boolean() }),
  adminUpdate: z.object({ success: z.boolean() }),
  adminDeactivate: z.object({ success: z.boolean() }),
};
