// Explicit response field allowlists. Review contract changes with producers and consumers.
import { z } from "zod";
import { outputNumber } from "./primitives";
export const responseContracts = {
  submitInfo: z.object({
    id: outputNumber,
    passengerId: outputNumber,
    bookingId: outputNumber,
    status: z.enum([
      "rejected",
      "complete",
      "incomplete",
      "validated",
      "submitted",
    ]),
    message: z.string(),
  }),
  getMyAPISStatus: z.union([
    z.object({
      passengerId: outputNumber,
      passengerName: z.string(),
      bookingId: outputNumber,
      hasData: z.boolean(),
      status: z.enum([
        "rejected",
        "complete",
        "incomplete",
        "validated",
        "submitted",
      ]),
      data: z.null(),
      completeness: outputNumber,
      missingFields: z.array(z.string()),
      validatedAt: z.undefined().optional(),
      submittedAt: z.undefined().optional(),
    }),
    z.object({
      passengerId: outputNumber,
      passengerName: z.string(),
      bookingId: outputNumber,
      hasData: z.boolean(),
      status: z.enum([
        "rejected",
        "complete",
        "incomplete",
        "validated",
        "submitted",
      ]),
      data: z.object({
        documentType: z.string(),
        documentNumber: z.string(),
        issuingCountry: z.string(),
        nationality: z.string(),
        dateOfBirth: z.union([z.null(), z.string()]),
        gender: z.string(),
        expiryDate: z.union([z.null(), z.string()]),
        givenNames: z.string(),
        surname: z.string(),
        residenceCountry: z.union([z.null(), z.string()]),
        residenceAddress: z.union([z.null(), z.string()]),
        destinationAddress: z.union([z.null(), z.string()]),
        redressNumber: z.union([z.null(), z.string()]),
        knownTravelerNumber: z.union([z.null(), z.string()]),
      }),
      completeness: outputNumber,
      missingFields: z.array(z.string()),
      validatedAt: z.union([z.null(), z.string()]),
      submittedAt: z.union([z.null(), z.string()]),
    }),
  ]),
  getFlightStatus: z.object({
    flightId: outputNumber,
    flightNumber: z.string(),
    departureTime: z.date(),
    totalPassengers: outputNumber,
    passengerStatuses: z.array(
      z.object({
        passengerId: outputNumber,
        name: z.string(),
        bookingReference: z.string(),
        pnr: z.string(),
        apisStatus: z.enum([
          "rejected",
          "complete",
          "incomplete",
          "validated",
          "submitted",
        ]),
        validatedAt: z.union([z.null(), z.string()]),
        submittedAt: z.union([z.null(), z.string()]),
      })
    ),
    summary: z.object({
      incomplete: outputNumber,
      complete: outputNumber,
      validated: outputNumber,
      submitted: outputNumber,
      rejected: outputNumber,
    }),
    readyForSubmission: z.boolean(),
  }),
  validatePassenger: z.object({
    passengerId: outputNumber,
    valid: z.boolean(),
    status: z.enum([
      "rejected",
      "complete",
      "incomplete",
      "validated",
      "submitted",
    ]),
    errors: z.array(z.string()),
    warnings: z.array(z.string()),
    validatedAt: z.union([z.null(), z.string()]),
  }),
  generateMessage: z.object({
    flightId: outputNumber,
    flightNumber: z.string(),
    format: z.enum(["paxlst", "pnrgov"]),
    messageContent: z.string(),
    passengerCount: outputNumber,
    validatedCount: outputNumber,
    missingCount: outputNumber,
    generatedAt: z.string(),
  }),
  submitToAuthorities: z.object({
    submissionId: outputNumber,
    flightId: outputNumber,
    flightNumber: z.string(),
    destinationCountry: z.string(),
    format: z.enum(["paxlst", "pnrgov"]),
    status: z.enum([
      "error",
      "pending",
      "rejected",
      "submitted",
      "acknowledged",
    ]),
    submittedAt: z.string(),
    passengerCount: outputNumber,
    validatedCount: outputNumber,
  }),
  getRequirements: z.union([
    z.object({
      originCountry: z.string(),
      destinationCountry: z.string(),
      requiredFields: z.array(z.string()),
      submissionDeadlineMinutes: outputNumber,
      format: z.enum(["paxlst", "pnrgov"]),
      source: z.literal("database"),
    }),
    z.object({
      originCountry: z.string(),
      destinationCountry: z.string(),
      requiredFields: z.array(z.string()),
      submissionDeadlineMinutes: outputNumber,
      format: z.enum(["paxlst", "pnrgov"]),
      source: z.literal("default"),
    }),
  ]),
  flagIncomplete: z.object({
    flightId: outputNumber,
    flightNumber: z.string(),
    incompletePassengers: z.array(
      z.object({
        passengerId: outputNumber,
        name: z.string(),
        bookingReference: z.string(),
        pnr: z.string(),
        reason: z.string(),
      })
    ),
    totalPassengers: outputNumber,
    incompleteCount: outputNumber,
  }),
  getSubmissions: z.array(
    z.object({
      id: outputNumber,
      flightId: outputNumber,
      destinationCountry: z.string(),
      format: z.enum(["paxlst", "pnrgov"]),
      submissionTime: z.union([z.null(), z.string()]),
      acknowledgmentTime: z.union([z.null(), z.string()]),
      status: z.enum([
        "error",
        "pending",
        "rejected",
        "submitted",
        "acknowledged",
      ]),
      responseMessage: z.union([z.null(), z.string()]),
      createdAt: z.string(),
    })
  ),
};
