// Explicit response field allowlists. Review contract changes with producers and consumers.
import { z } from "zod";
import { outputNumber } from "./primitives";
export const responseContracts = {
  registerUnit: z.object({
    id: outputNumber,
    unitCode: z.string(),
    airportId: outputNumber,
    terminal: z.string(),
    zone: z.string(),
    status: z.enum(["maintenance", "online", "offline", "jam"]),
    hasPrinter: z.boolean(),
    hasScale: z.boolean(),
    hasPayment: z.boolean(),
    beltConnected: z.boolean(),
    lastMaintenance: z.union([z.null(), z.date()]),
    createdAt: z.date(),
    updatedAt: z.date(),
  }),
  scanPass: z.object({
    success: z.boolean(),
    bookingId: outputNumber,
    passengerId: outputNumber,
    passengerName: z.string(),
    flightNumber: z.string(),
    cabinClass: z.union([z.null(), z.string()]),
    capabilityToken: z.string(),
  }),
  initiate: z.object({
    success: z.boolean(),
    session: z.object({
      bagWeights: z.array(outputNumber),
      version: outputNumber,
      id: outputNumber,
      unitId: outputNumber,
      bookingId: outputNumber,
      passengerId: outputNumber,
      totalBags: outputNumber,
      totalWeight: outputNumber,
      allowanceWeight: outputNumber,
      excessWeight: outputNumber,
      excessFee: outputNumber,
      paymentStatus: z.enum(["pending", "paid", "none"]),
      status: z.enum([
        "error",
        "payment",
        "complete",
        "started",
        "weighing",
        "printing",
        "timeout",
      ]),
      startedAt: z.date(),
      completedAt: z.union([z.null(), z.date()]),
      errorMessage: z.union([z.null(), z.string()]),
      createdAt: z.date(),
    }),
    sessionToken: z.string(),
  }),
  weighBag: z.object({
    session: z.object({
      id: outputNumber,
      unitId: outputNumber,
      bookingId: outputNumber,
      passengerId: outputNumber,
      totalBags: outputNumber,
      totalWeight: outputNumber,
      bagWeights: z.array(outputNumber),
      allowanceWeight: outputNumber,
      excessWeight: outputNumber,
      excessFee: outputNumber,
      paymentStatus: z.enum(["pending", "paid", "none"]),
      status: z.enum([
        "error",
        "payment",
        "complete",
        "started",
        "weighing",
        "printing",
        "timeout",
      ]),
      version: outputNumber,
      startedAt: z.date(),
      completedAt: z.union([z.null(), z.date()]),
      errorMessage: z.union([z.null(), z.string()]),
      createdAt: z.date(),
    }),
    bagNumber: outputNumber,
    weightGrams: outputNumber,
    withinAllowance: z.boolean(),
    success: z.boolean(),
  }),
  checkAllowance: z.object({
    allowanceWeightGrams: outputNumber,
    cabinClass: z.string(),
    maxBagWeightGrams: outputNumber,
    excessFeePerKgCents: outputNumber,
  }),
  calculateFee: z.object({
    allowanceWeightGrams: outputNumber,
    totalWeightGrams: outputNumber,
    excessWeightGrams: outputNumber,
    excessFeeCents: outputNumber,
    currency: z.string(),
  }),
  processPayment: z.never(),
  printTag: z.object({
    success: z.boolean(),
    tag: z.object({
      id: outputNumber,
      sessionId: outputNumber,
      bagNumber: outputNumber,
      tagNumber: z.string(),
      weight: outputNumber,
      destination: z.string(),
      connectionTags: z.union([z.null(), z.array(z.string())]),
      printedAt: z.union([z.null(), z.date()]),
      status: z.enum([
        "arrived",
        "lost",
        "printed",
        "attached",
        "loaded",
        "transferred",
      ]),
      createdAt: z.date(),
    }),
  }),
  confirm: z.object({
    session: z.object({
      id: outputNumber,
      unitId: outputNumber,
      bookingId: outputNumber,
      passengerId: outputNumber,
      totalBags: outputNumber,
      totalWeight: outputNumber,
      bagWeights: z.array(outputNumber),
      allowanceWeight: outputNumber,
      excessWeight: outputNumber,
      excessFee: outputNumber,
      paymentStatus: z.enum(["pending", "paid", "none"]),
      status: z.enum([
        "error",
        "payment",
        "complete",
        "started",
        "weighing",
        "printing",
        "timeout",
      ]),
      version: outputNumber,
      startedAt: z.date(),
      completedAt: z.union([z.null(), z.date()]),
      errorMessage: z.union([z.null(), z.string()]),
      createdAt: z.date(),
    }),
    tags: z.array(
      z.object({
        id: outputNumber,
        sessionId: outputNumber,
        bagNumber: outputNumber,
        tagNumber: z.string(),
        weight: outputNumber,
        destination: z.string(),
        connectionTags: z.union([z.null(), z.array(z.string())]),
        printedAt: z.union([z.null(), z.date()]),
        status: z.enum([
          "arrived",
          "lost",
          "printed",
          "attached",
          "loaded",
          "transferred",
        ]),
        createdAt: z.date(),
      })
    ),
    success: z.boolean(),
  }),
  getUnits: z.object({
    units: z.array(
      z.object({
        id: outputNumber,
        unitCode: z.string(),
        airportId: outputNumber,
        terminal: z.string(),
        zone: z.string(),
        status: z.enum(["maintenance", "online", "offline", "jam"]),
        hasPrinter: z.boolean(),
        hasScale: z.boolean(),
        hasPayment: z.boolean(),
        beltConnected: z.boolean(),
        lastMaintenance: z.union([z.null(), z.date()]),
        createdAt: z.date(),
        updatedAt: z.date(),
      })
    ),
  }),
  getUnitStatus: z.object({
    unit: z.object({
      id: outputNumber,
      unitCode: z.string(),
      airportId: outputNumber,
      terminal: z.string(),
      zone: z.string(),
      status: z.enum(["maintenance", "online", "offline", "jam"]),
      hasPrinter: z.boolean(),
      hasScale: z.boolean(),
      hasPayment: z.boolean(),
      beltConnected: z.boolean(),
      lastMaintenance: z.union([z.null(), z.date()]),
      createdAt: z.date(),
      updatedAt: z.date(),
    }),
    activeSessions: outputNumber,
    isOperational: z.boolean(),
    unavailableReason: z.string(),
  }),
  getAnalytics: z.object({
    airportId: outputNumber,
    period: z.object({ start: z.date(), end: z.date() }),
    totalSessions: outputNumber,
    completedSessions: outputNumber,
    errorSessions: outputNumber,
    timeoutSessions: outputNumber,
    averageSessionDurationMs: outputNumber,
    totalBagsProcessed: outputNumber,
    totalWeightGrams: outputNumber,
    totalExcessFeeCents: outputNumber,
    units: z.array(
      z.object({
        unitId: outputNumber,
        unitCode: z.string(),
        status: z.enum(["maintenance", "online", "offline", "jam"]),
        sessionsProcessed: outputNumber,
      })
    ),
  }),
};
