// Explicit response field allowlists. Review contract changes with producers and consumers.
import { z } from "zod";
import { outputNumber } from "./primitives";
export const responseContracts = {
  track: z.object({
    baggage: z.object({
      id: outputNumber,
      status: z.enum([
        "checked_in",
        "security_screening",
        "loading",
        "in_transit",
        "arrived",
        "customs",
        "ready_for_pickup",
        "claimed",
        "lost",
        "found",
        "damaged",
      ]),
      createdAt: z.date(),
      updatedAt: z.date(),
      description: z.union([z.null(), z.string()]),
      bookingId: outputNumber,
      passengerId: outputNumber,
      tagNumber: z.string(),
      weight: z.string(),
      lastLocation: z.union([z.null(), z.string()]),
      specialHandling: z.union([z.null(), z.string()]),
      lostReportedAt: z.union([z.null(), z.date()]),
      lostDescription: z.union([z.null(), z.string()]),
    }),
    tracking: z.array(
      z.object({
        id: outputNumber,
        status: z.enum([
          "checked_in",
          "security_screening",
          "loading",
          "in_transit",
          "arrived",
          "customs",
          "ready_for_pickup",
          "claimed",
          "lost",
          "found",
          "damaged",
        ]),
        createdAt: z.date(),
        notes: z.union([z.null(), z.string()]),
        baggageId: outputNumber,
        location: z.string(),
        scannedAt: z.date(),
        scannedBy: z.union([z.null(), outputNumber]),
      })
    ),
  }),
  getByTag: z.object({
    id: outputNumber,
    status: z.enum([
      "checked_in",
      "security_screening",
      "loading",
      "in_transit",
      "arrived",
      "customs",
      "ready_for_pickup",
      "claimed",
      "lost",
      "found",
      "damaged",
    ]),
    createdAt: z.date(),
    updatedAt: z.date(),
    description: z.union([z.null(), z.string()]),
    bookingId: outputNumber,
    passengerId: outputNumber,
    tagNumber: z.string(),
    weight: z.string(),
    lastLocation: z.union([z.null(), z.string()]),
    specialHandling: z.union([z.null(), z.string()]),
    lostReportedAt: z.union([z.null(), z.date()]),
    lostDescription: z.union([z.null(), z.string()]),
  }),
  register: z.object({
    success: z.boolean(),
    baggage: z.object({
      id: outputNumber,
      status: z.enum([
        "checked_in",
        "security_screening",
        "loading",
        "in_transit",
        "arrived",
        "customs",
        "ready_for_pickup",
        "claimed",
        "lost",
        "found",
        "damaged",
      ]),
      createdAt: z.date(),
      updatedAt: z.date(),
      description: z.union([z.null(), z.string()]),
      bookingId: outputNumber,
      passengerId: outputNumber,
      tagNumber: z.string(),
      weight: z.string(),
      lastLocation: z.union([z.null(), z.string()]),
      specialHandling: z.union([z.null(), z.string()]),
      lostReportedAt: z.union([z.null(), z.date()]),
      lostDescription: z.union([z.null(), z.string()]),
    }),
  }),
  getBookingBaggage: z.array(
    z.object({
      id: outputNumber,
      status: z.enum([
        "checked_in",
        "security_screening",
        "loading",
        "in_transit",
        "arrived",
        "customs",
        "ready_for_pickup",
        "claimed",
        "lost",
        "found",
        "damaged",
      ]),
      createdAt: z.date(),
      updatedAt: z.date(),
      description: z.union([z.null(), z.string()]),
      bookingId: outputNumber,
      passengerId: outputNumber,
      tagNumber: z.string(),
      weight: z.string(),
      lastLocation: z.union([z.null(), z.string()]),
      specialHandling: z.union([z.null(), z.string()]),
      lostReportedAt: z.union([z.null(), z.date()]),
      lostDescription: z.union([z.null(), z.string()]),
      passengerName: z.union([z.undefined(), z.string()]).optional(),
    })
  ),
  getPassengerBaggage: z.array(
    z.object({
      id: outputNumber,
      status: z.enum([
        "checked_in",
        "security_screening",
        "loading",
        "in_transit",
        "arrived",
        "customs",
        "ready_for_pickup",
        "claimed",
        "lost",
        "found",
        "damaged",
      ]),
      createdAt: z.date(),
      updatedAt: z.date(),
      description: z.union([z.null(), z.string()]),
      bookingId: outputNumber,
      passengerId: outputNumber,
      tagNumber: z.string(),
      weight: z.string(),
      lastLocation: z.union([z.null(), z.string()]),
      specialHandling: z.union([z.null(), z.string()]),
      lostReportedAt: z.union([z.null(), z.date()]),
      lostDescription: z.union([z.null(), z.string()]),
    })
  ),
  reportLost: z.object({
    success: z.boolean(),
    baggage: z.object({
      id: outputNumber,
      status: z.enum([
        "checked_in",
        "security_screening",
        "loading",
        "in_transit",
        "arrived",
        "customs",
        "ready_for_pickup",
        "claimed",
        "lost",
        "found",
        "damaged",
      ]),
      createdAt: z.date(),
      updatedAt: z.date(),
      description: z.union([z.null(), z.string()]),
      bookingId: outputNumber,
      passengerId: outputNumber,
      tagNumber: z.string(),
      weight: z.string(),
      lastLocation: z.union([z.null(), z.string()]),
      specialHandling: z.union([z.null(), z.string()]),
      lostReportedAt: z.union([z.null(), z.date()]),
      lostDescription: z.union([z.null(), z.string()]),
    }),
  }),
  getStatusLabels: z.object({
    checked_in: z.string(),
    security_screening: z.string(),
    loading: z.string(),
    in_transit: z.string(),
    arrived: z.string(),
    customs: z.string(),
    ready_for_pickup: z.string(),
    claimed: z.string(),
    lost: z.string(),
    found: z.string(),
    damaged: z.string(),
  }),
  adminUpdateStatus: z.object({
    success: z.boolean(),
    baggage: z.object({
      id: outputNumber,
      status: z.enum([
        "checked_in",
        "security_screening",
        "loading",
        "in_transit",
        "arrived",
        "customs",
        "ready_for_pickup",
        "claimed",
        "lost",
        "found",
        "damaged",
      ]),
      createdAt: z.date(),
      updatedAt: z.date(),
      description: z.union([z.null(), z.string()]),
      bookingId: outputNumber,
      passengerId: outputNumber,
      tagNumber: z.string(),
      weight: z.string(),
      lastLocation: z.union([z.null(), z.string()]),
      specialHandling: z.union([z.null(), z.string()]),
      lostReportedAt: z.union([z.null(), z.date()]),
      lostDescription: z.union([z.null(), z.string()]),
    }),
  }),
  adminGetAll: z.array(
    z.object({
      id: outputNumber,
      status: z.enum([
        "checked_in",
        "security_screening",
        "loading",
        "in_transit",
        "arrived",
        "customs",
        "ready_for_pickup",
        "claimed",
        "lost",
        "found",
        "damaged",
      ]),
      createdAt: z.date(),
      updatedAt: z.date(),
      description: z.union([z.null(), z.string()]),
      bookingId: outputNumber,
      passengerId: outputNumber,
      tagNumber: z.string(),
      weight: z.string(),
      lastLocation: z.union([z.null(), z.string()]),
      specialHandling: z.union([z.null(), z.string()]),
      lostReportedAt: z.union([z.null(), z.date()]),
      lostDescription: z.union([z.null(), z.string()]),
      passengerName: z.union([z.undefined(), z.string()]).optional(),
    })
  ),
  adminGetLost: z.array(
    z.object({
      id: outputNumber,
      status: z.enum([
        "checked_in",
        "security_screening",
        "loading",
        "in_transit",
        "arrived",
        "customs",
        "ready_for_pickup",
        "claimed",
        "lost",
        "found",
        "damaged",
      ]),
      createdAt: z.date(),
      updatedAt: z.date(),
      description: z.union([z.null(), z.string()]),
      bookingId: outputNumber,
      passengerId: outputNumber,
      tagNumber: z.string(),
      weight: z.string(),
      lastLocation: z.union([z.null(), z.string()]),
      specialHandling: z.union([z.null(), z.string()]),
      lostReportedAt: z.union([z.null(), z.date()]),
      lostDescription: z.union([z.null(), z.string()]),
    })
  ),
  adminMarkFound: z.object({
    success: z.boolean(),
    baggage: z.object({
      id: outputNumber,
      status: z.enum([
        "checked_in",
        "security_screening",
        "loading",
        "in_transit",
        "arrived",
        "customs",
        "ready_for_pickup",
        "claimed",
        "lost",
        "found",
        "damaged",
      ]),
      createdAt: z.date(),
      updatedAt: z.date(),
      description: z.union([z.null(), z.string()]),
      bookingId: outputNumber,
      passengerId: outputNumber,
      tagNumber: z.string(),
      weight: z.string(),
      lastLocation: z.union([z.null(), z.string()]),
      specialHandling: z.union([z.null(), z.string()]),
      lostReportedAt: z.union([z.null(), z.date()]),
      lostDescription: z.union([z.null(), z.string()]),
    }),
  }),
  adminGetStats: z.object({
    totalBaggage: outputNumber,
    checkedIn: outputNumber,
    inTransit: outputNumber,
    claimed: outputNumber,
    lost: outputNumber,
    damaged: outputNumber,
  }),
  adminGetByStatus: z.array(
    z.object({
      id: outputNumber,
      status: z.enum([
        "checked_in",
        "security_screening",
        "loading",
        "in_transit",
        "arrived",
        "customs",
        "ready_for_pickup",
        "claimed",
        "lost",
        "found",
        "damaged",
      ]),
      createdAt: z.date(),
      updatedAt: z.date(),
      description: z.union([z.null(), z.string()]),
      bookingId: outputNumber,
      passengerId: outputNumber,
      tagNumber: z.string(),
      weight: z.string(),
      lastLocation: z.union([z.null(), z.string()]),
      specialHandling: z.union([z.null(), z.string()]),
      lostReportedAt: z.union([z.null(), z.date()]),
      lostDescription: z.union([z.null(), z.string()]),
    })
  ),
};
