// Explicit response field allowlists. Review contract changes with producers and consumers.
import { z } from "zod";
import { outputNumber } from "./primitives";
export const responseContracts = {
  health: z.object({
    status: z.enum(["error", "degraded", "ok"]),
    redis: z.object({
      connected: z.boolean(),
      latency: z.union([z.undefined(), outputNumber]).optional(),
      error: z.union([z.undefined(), z.string()]).optional(),
    }),
    memory: z.object({ entries: outputNumber, maxSize: outputNumber }),
  }),
  stats: z.object({
    hitRate: outputNumber,
    redisConnected: z.boolean(),
    memoryEntries: outputNumber,
    namespaceVersions: z.record(z.string(), outputNumber),
    uptime: outputNumber,
    hits: outputNumber,
    misses: outputNumber,
    sets: outputNumber,
    deletes: outputNumber,
    errors: outputNumber,
    memoryFallbackUsed: outputNumber,
  }),
  redisInfo: z.union([
    z.object({
      available: z.boolean(),
      message: z.string(),
      version: z.undefined().optional(),
      uptimeSeconds: z.undefined().optional(),
      connectedClients: z.undefined().optional(),
      usedMemory: z.undefined().optional(),
      usedMemoryPeak: z.undefined().optional(),
      totalKeys: z.undefined().optional(),
      expiredKeys: z.undefined().optional(),
      evictedKeys: z.undefined().optional(),
      hitRate: z.undefined().optional(),
    }),
    z.object({
      available: z.boolean(),
      version: z.string(),
      uptimeSeconds: outputNumber,
      connectedClients: outputNumber,
      usedMemory: z.string(),
      usedMemoryPeak: z.string(),
      totalKeys: outputNumber,
      expiredKeys: outputNumber,
      evictedKeys: outputNumber,
      hitRate: outputNumber,
      message: z.undefined().optional(),
    }),
  ]),
  invalidateNamespace: z.object({ success: z.boolean(), message: z.string() }),
  invalidateFlightSearch: z.object({
    success: z.boolean(),
    message: z.string(),
  }),
  invalidateReferenceData: z.object({
    success: z.boolean(),
    message: z.string(),
  }),
  invalidatePricing: z.object({ success: z.boolean(), message: z.string() }),
  invalidateUserSession: z.object({
    success: z.boolean(),
    message: z.string(),
  }),
  resetStats: z.object({ success: z.boolean(), message: z.string() }),
  clearAll: z.object({ success: z.boolean(), message: z.string() }),
  reconnect: z.object({ success: z.boolean(), message: z.string() }),
  config: z.object({
    ttl: z.object({
      FLIGHT_SEARCH: z.literal(120),
      PRICING: z.literal(60),
      AVAILABILITY: z.literal(30),
      FLIGHT_DETAILS: z.literal(300),
      USER_SESSION: z.literal(900),
      POPULAR_ROUTES: z.literal(600),
      AIRPORTS: z.literal(3600),
      AIRLINES: z.literal(3600),
      CITIES: z.literal(3600),
      STATIC_CONFIG: z.literal(86400),
    }),
    namespaces: z.object({
      SEARCH: z.literal("search"),
      FLIGHT: z.literal("flight"),
      PRICING: z.literal("pricing"),
      AIRPORTS: z.literal("airports"),
      AIRLINES: z.literal("airlines"),
      CITIES: z.literal("cities"),
      SESSION: z.literal("session"),
      ROUTES: z.literal("routes"),
      USER: z.literal("user"),
    }),
    redisUrl: z.string(),
    cachePrefix: z.string(),
  }),
};
