// Explicit response field allowlists. Review contract changes with producers and consumers.
import { z } from "zod";
import { outputNumber, structuredValue } from "./primitives";
export const responseContracts = {
  fileClaim: z.object({
    id: outputNumber,
    bookingId: outputNumber,
    flightId: outputNumber,
    passengerId: z.union([z.null(), outputNumber]),
    regulationType: z.enum(["local", "eu261", "dot"]),
    claimType: z.enum([
      "delay",
      "cancellation",
      "denied_boarding",
      "downgrade",
    ]),
    flightDistance: z.union([z.null(), outputNumber]),
    delayMinutes: z.union([z.null(), outputNumber]),
    calculatedAmount: outputNumber,
    approvedAmount: z.union([z.null(), outputNumber]),
    currency: z.string(),
    status: z.enum([
      "pending",
      "paid",
      "approved",
      "denied",
      "under_review",
      "appealed",
    ]),
    reason: z.union([z.null(), z.string()]),
    denialReason: z.union([z.null(), z.string()]),
    filedAt: z.date(),
    resolvedAt: z.union([z.null(), z.date()]),
    paidAt: z.union([z.null(), z.date()]),
    createdAt: z.date(),
    updatedAt: z.date(),
  }),
  getMyClaims: z.array(
    z.object({
      id: outputNumber,
      bookingId: outputNumber,
      flightId: outputNumber,
      passengerId: z.union([z.null(), outputNumber]),
      regulationType: z.enum(["local", "eu261", "dot"]),
      claimType: z.enum([
        "delay",
        "cancellation",
        "denied_boarding",
        "downgrade",
      ]),
      flightDistance: z.union([z.null(), outputNumber]),
      delayMinutes: z.union([z.null(), outputNumber]),
      calculatedAmount: outputNumber,
      approvedAmount: z.union([z.null(), outputNumber]),
      currency: z.string(),
      status: z.enum([
        "pending",
        "paid",
        "approved",
        "denied",
        "under_review",
        "appealed",
      ]),
      reason: z.union([z.null(), z.string()]),
      denialReason: z.union([z.null(), z.string()]),
      filedAt: z.date(),
      resolvedAt: z.union([z.null(), z.date()]),
      paidAt: z.union([z.null(), z.date()]),
      createdAt: z.date(),
      updatedAt: z.date(),
    })
  ),
  getClaimDetail: z.object({
    id: outputNumber,
    bookingId: outputNumber,
    flightId: outputNumber,
    passengerId: z.union([z.null(), outputNumber]),
    regulationType: z.enum(["local", "eu261", "dot"]),
    claimType: z.enum([
      "delay",
      "cancellation",
      "denied_boarding",
      "downgrade",
    ]),
    flightDistance: z.union([z.null(), outputNumber]),
    delayMinutes: z.union([z.null(), outputNumber]),
    calculatedAmount: outputNumber,
    approvedAmount: z.union([z.null(), outputNumber]),
    currency: z.string(),
    status: z.enum([
      "pending",
      "paid",
      "approved",
      "denied",
      "under_review",
      "appealed",
    ]),
    reason: z.union([z.null(), z.string()]),
    denialReason: z.union([z.null(), z.string()]),
    filedAt: z.date(),
    resolvedAt: z.union([z.null(), z.date()]),
    paidAt: z.union([z.null(), z.date()]),
    createdAt: z.date(),
    updatedAt: z.date(),
  }),
  checkEligibility: z.object({
    eligible: z.boolean(),
    regulationType: z.enum(["local", "eu261", "dot"]),
    estimatedAmount: outputNumber,
    currency: z.string(),
    reason: z.string(),
    flightDistance: outputNumber,
    delayMinutes: outputNumber,
  }),
  processClaim: z.object({
    id: outputNumber,
    bookingId: outputNumber,
    flightId: outputNumber,
    passengerId: z.union([z.null(), outputNumber]),
    regulationType: z.enum(["local", "eu261", "dot"]),
    claimType: z.enum([
      "delay",
      "cancellation",
      "denied_boarding",
      "downgrade",
    ]),
    flightDistance: z.union([z.null(), outputNumber]),
    delayMinutes: z.union([z.null(), outputNumber]),
    calculatedAmount: outputNumber,
    approvedAmount: z.union([z.null(), outputNumber]),
    currency: z.string(),
    status: z.enum([
      "pending",
      "paid",
      "approved",
      "denied",
      "under_review",
      "appealed",
    ]),
    reason: z.union([z.null(), z.string()]),
    denialReason: z.union([z.null(), z.string()]),
    filedAt: z.date(),
    resolvedAt: z.union([z.null(), z.date()]),
    paidAt: z.union([z.null(), z.date()]),
    createdAt: z.date(),
    updatedAt: z.date(),
  }),
  getAllClaims: z.object({
    claims: z.array(
      z.object({
        id: outputNumber,
        bookingId: outputNumber,
        flightId: outputNumber,
        passengerId: z.union([z.null(), outputNumber]),
        regulationType: z.enum(["local", "eu261", "dot"]),
        claimType: z.enum([
          "delay",
          "cancellation",
          "denied_boarding",
          "downgrade",
        ]),
        flightDistance: z.union([z.null(), outputNumber]),
        delayMinutes: z.union([z.null(), outputNumber]),
        calculatedAmount: outputNumber,
        approvedAmount: z.union([z.null(), outputNumber]),
        currency: z.string(),
        status: z.enum([
          "pending",
          "paid",
          "approved",
          "denied",
          "under_review",
          "appealed",
        ]),
        reason: z.union([z.null(), z.string()]),
        denialReason: z.union([z.null(), z.string()]),
        filedAt: z.date(),
        resolvedAt: z.union([z.null(), z.date()]),
        paidAt: z.union([z.null(), z.date()]),
        createdAt: z.date(),
        updatedAt: z.date(),
      })
    ),
    total: outputNumber,
    page: outputNumber,
    totalPages: outputNumber,
  }),
  getFlightLiability: z.object({
    flightId: outputNumber,
    flightNumber: z.string(),
    totalClaims: outputNumber,
    totalCalculated: outputNumber,
    totalApproved: outputNumber,
    totalPaid: outputNumber,
    statusBreakdown: z.record(z.string(), outputNumber),
  }),
  getStats: z.object({
    totalClaims: outputNumber,
    pendingClaims: outputNumber,
    approvedClaims: outputNumber,
    deniedClaims: outputNumber,
    paidClaims: outputNumber,
    appealedClaims: outputNumber,
    totalCalculated: outputNumber,
    totalApproved: outputNumber,
    totalPaid: outputNumber,
    avgProcessingDays: outputNumber,
  }),
  getRules: z.array(
    z.object({
      id: outputNumber,
      regulationType: z.enum(["local", "eu261", "dot"]),
      claimType: z.enum([
        "delay",
        "cancellation",
        "denied_boarding",
        "downgrade",
      ]),
      minDelay: z.union([z.null(), outputNumber]),
      maxDelay: z.union([z.null(), outputNumber]),
      distanceMin: z.union([z.null(), outputNumber]),
      distanceMax: z.union([z.null(), outputNumber]),
      compensationAmount: outputNumber,
      currency: z.string(),
      conditions: z.union([z.null(), z.record(z.string(), structuredValue)]),
      isActive: z.boolean(),
      createdAt: z.date(),
    })
  ),
  updateRule: z.object({
    id: outputNumber,
    regulationType: z.enum(["local", "eu261", "dot"]),
    claimType: z.enum([
      "delay",
      "cancellation",
      "denied_boarding",
      "downgrade",
    ]),
    minDelay: z.union([z.null(), outputNumber]),
    maxDelay: z.union([z.null(), outputNumber]),
    distanceMin: z.union([z.null(), outputNumber]),
    distanceMax: z.union([z.null(), outputNumber]),
    compensationAmount: outputNumber,
    currency: z.string(),
    conditions: z.union([z.null(), z.record(z.string(), structuredValue)]),
    isActive: z.boolean(),
    createdAt: z.date(),
  }),
};
