// Explicit response field allowlists. Review contract changes with producers and consumers.
import { z } from "zod";
import { outputNumber } from "./primitives";
export const responseContracts = {
  listAccounts: z.array(
    z.object({
      id: outputNumber,
      status: z.enum(["active", "pending", "suspended", "closed"]),
      createdAt: z.date(),
      updatedAt: z.date(),
      discountPercent: z.string(),
      approvedBy: z.union([z.null(), outputNumber]),
      approvedAt: z.union([z.null(), z.date()]),
      contactEmail: z.string(),
      contactPhone: z.union([z.null(), z.string()]),
      companyName: z.string(),
      taxId: z.string(),
      address: z.union([z.null(), z.string()]),
      contactName: z.string(),
      creditLimit: outputNumber,
      balance: outputNumber,
    })
  ),
  getAccountById: z.object({
    id: outputNumber,
    status: z.enum(["active", "pending", "suspended", "closed"]),
    createdAt: z.date(),
    updatedAt: z.date(),
    discountPercent: z.string(),
    approvedBy: z.union([z.null(), outputNumber]),
    approvedAt: z.union([z.null(), z.date()]),
    contactEmail: z.string(),
    contactPhone: z.union([z.null(), z.string()]),
    companyName: z.string(),
    taxId: z.string(),
    address: z.union([z.null(), z.string()]),
    contactName: z.string(),
    creditLimit: outputNumber,
    balance: outputNumber,
  }),
  getMyAccount: z.union([
    z.null(),
    z.object({
      id: outputNumber,
      status: z.enum(["active", "pending", "suspended", "closed"]),
      createdAt: z.date(),
      updatedAt: z.date(),
      discountPercent: z.string(),
      approvedBy: z.union([z.null(), outputNumber]),
      approvedAt: z.union([z.null(), z.date()]),
      contactEmail: z.string(),
      contactPhone: z.union([z.null(), z.string()]),
      companyName: z.string(),
      taxId: z.string(),
      address: z.union([z.null(), z.string()]),
      contactName: z.string(),
      creditLimit: outputNumber,
      balance: outputNumber,
      role: z.string(),
    }),
  ]),
  getUsers: z.array(
    z.object({
      id: outputNumber,
      createdAt: z.date(),
      updatedAt: z.date(),
      userId: outputNumber,
      role: z.enum(["admin", "booker", "traveler"]),
      isActive: z.boolean(),
      corporateAccountId: outputNumber,
      user: z.object({
        id: outputNumber,
        name: z.union([z.null(), z.string()]),
        email: z.union([z.null(), z.string()]),
      }),
    })
  ),
  getBookings: z.array(
    z.object({
      id: outputNumber,
      createdAt: z.date(),
      updatedAt: z.date(),
      bookingId: outputNumber,
      rejectionReason: z.union([z.null(), z.string()]),
      approvedBy: z.union([z.null(), outputNumber]),
      approvedAt: z.union([z.null(), z.date()]),
      costCenter: z.union([z.null(), z.string()]),
      projectCode: z.union([z.null(), z.string()]),
      travelPurpose: z.union([z.null(), z.string()]),
      approvalStatus: z.enum(["pending", "approved", "rejected"]),
      corporateAccountId: outputNumber,
      bookedByUserId: outputNumber,
      booking: z.object({
        id: outputNumber,
        bookingReference: z.string(),
        status: z.string(),
        totalAmount: outputNumber,
        flightId: outputNumber,
        createdAt: z.date(),
      }),
      flight: z.object({
        flightNumber: z.string(),
        departureTime: z.date(),
        originId: outputNumber,
        destinationId: outputNumber,
      }),
    })
  ),
  getStats: z.object({
    totalBookings: outputNumber,
    pendingApprovals: outputNumber,
    approvedBookings: outputNumber,
    rejectedBookings: outputNumber,
    totalSpent: outputNumber,
    userCount: outputNumber,
    creditRemaining: outputNumber,
  }),
  getAccountStats: z.object({
    totalBookings: outputNumber,
    pendingApprovals: outputNumber,
    approvedBookings: outputNumber,
    rejectedBookings: outputNumber,
    totalSpent: outputNumber,
    userCount: outputNumber,
    creditRemaining: outputNumber,
  }),
};
