// Explicit response field allowlists. Review contract changes with producers and consumers.
import { z } from "zod";
import { outputNumber, structuredValue } from "./primitives";
export const responseContracts = {
  createExport: z.object({
    id: outputNumber,
    exportType: z.enum([
      "flights",
      "bookings",
      "revenue",
      "customers",
      "operational",
    ]),
    format: z.enum(["json", "jsonl", "csv"]),
    status: z.enum(["completed", "pending", "failed", "processing"]),
    recordCount: outputNumber,
    fileSize: outputNumber,
    filePath: z.union([z.null(), z.string()]),
    createdAt: z.date(),
    completedAt: z.union([z.null(), z.date()]),
    errorMessage: z.union([z.null(), z.string()]),
  }),
  getExports: z.object({
    exports: z.array(
      z.object({
        id: outputNumber,
        exportType: z.enum([
          "flights",
          "bookings",
          "revenue",
          "customers",
          "operational",
        ]),
        dateRangeStart: z.date(),
        dateRangeEnd: z.date(),
        format: z.enum(["json", "jsonl", "csv"]),
        status: z.enum(["completed", "pending", "failed", "processing"]),
        filePath: z.union([z.null(), z.string()]),
        recordCount: outputNumber,
        fileSize: outputNumber,
        createdBy: outputNumber,
        createdAt: z.date(),
        completedAt: z.union([z.null(), z.date()]),
        errorMessage: z.union([z.null(), z.string()]),
      })
    ),
    total: outputNumber,
    page: outputNumber,
    limit: outputNumber,
    totalPages: outputNumber,
  }),
  getExportStatus: z.union([
    z.object({
      found: z.literal(false),
      id: z.undefined().optional(),
      exportType: z.undefined().optional(),
      status: z.undefined().optional(),
      recordCount: z.undefined().optional(),
      fileSize: z.undefined().optional(),
      filePath: z.undefined().optional(),
      createdAt: z.undefined().optional(),
      completedAt: z.undefined().optional(),
      errorMessage: z.undefined().optional(),
    }),
    z.object({
      found: z.literal(true),
      id: outputNumber,
      exportType: z.enum([
        "flights",
        "bookings",
        "revenue",
        "customers",
        "operational",
      ]),
      status: z.enum(["completed", "pending", "failed", "processing"]),
      recordCount: outputNumber,
      fileSize: outputNumber,
      filePath: z.union([z.null(), z.string()]),
      createdAt: z.date(),
      completedAt: z.union([z.null(), z.date()]),
      errorMessage: z.union([z.null(), z.string()]),
    }),
  ]),
  downloadExport: z.object({
    downloadUrl: z.union([z.null(), z.string()]),
    available: z.boolean(),
    exportType: z.union([
      z.null(),
      z.literal("flights"),
      z.literal("bookings"),
      z.literal("revenue"),
      z.literal("customers"),
      z.literal("operational"),
    ]),
    format: z.union([
      z.null(),
      z.literal("json"),
      z.literal("jsonl"),
      z.literal("csv"),
    ]),
    fileSize: outputNumber,
    recordCount: outputNumber,
  }),
  createSchedule: z.object({
    id: outputNumber,
    name: z.string(),
    exportType: z.enum([
      "flights",
      "bookings",
      "revenue",
      "customers",
      "operational",
    ]),
    frequency: z.enum(["daily", "weekly", "monthly"]),
    format: z.enum(["json", "jsonl", "csv"]),
    lastRunAt: z.union([z.null(), z.date()]),
    nextRunAt: z.date(),
    isActive: z.boolean(),
    createdAt: z.date(),
  }),
  getSchedules: z.array(
    z.object({
      id: outputNumber,
      name: z.string(),
      exportType: z.enum([
        "flights",
        "bookings",
        "revenue",
        "customers",
        "operational",
      ]),
      frequency: z.enum(["daily", "weekly", "monthly"]),
      format: z.enum(["json", "jsonl", "csv"]),
      lastRunAt: z.union([z.null(), z.date()]),
      nextRunAt: z.date(),
      isActive: z.boolean(),
      config: z.record(z.string(), structuredValue),
      createdAt: z.date(),
    })
  ),
  updateSchedule: z.union([
    z.object({
      success: z.literal(false),
      message: z.string(),
      schedule: z.undefined().optional(),
    }),
    z.object({
      success: z.literal(true),
      schedule: z.object({
        id: outputNumber,
        name: z.string(),
        exportType: z.enum([
          "flights",
          "bookings",
          "revenue",
          "customers",
          "operational",
        ]),
        frequency: z.enum(["daily", "weekly", "monthly"]),
        format: z.enum(["json", "jsonl", "csv"]),
        lastRunAt: z.union([z.null(), z.date()]),
        nextRunAt: z.date(),
        isActive: z.boolean(),
        createdAt: z.date(),
      }),
      message: z.undefined().optional(),
    }),
  ]),
  deleteSchedule: z.object({ success: z.boolean(), message: z.string() }),
  getETLStatus: z.object({
    status: z.enum(["unknown", "healthy", "degraded", "down"]),
    totalExports: outputNumber,
    completedExports: outputNumber,
    failedExports: outputNumber,
    processingExports: outputNumber,
    activeSchedules: outputNumber,
    lastExportAt: z.union([z.null(), z.string()]),
    recentFailures: z.array(
      z.object({
        id: outputNumber,
        exportType: z.enum([
          "flights",
          "bookings",
          "revenue",
          "customers",
          "operational",
        ]),
        errorMessage: z.union([z.null(), z.string()]),
        createdAt: z.string(),
      })
    ),
  }),
};
