// Explicit response field allowlists. Review contract changes with producers and consumers.
import { z } from "zod";
import { outputNumber } from "./primitives";
export const responseContracts = {
  getAircraftTypes: z.array(
    z.object({
      id: outputNumber,
      code: z.string(),
      name: z.string(),
      manufacturer: z.string(),
      maxTakeoffWeight: outputNumber,
      maxLandingWeight: outputNumber,
      maxZeroFuelWeight: outputNumber,
      operatingEmptyWeight: outputNumber,
      maxPayload: outputNumber,
      maxFuelCapacity: outputNumber,
      totalSeats: outputNumber,
      economySeats: outputNumber,
      businessSeats: outputNumber,
      cargoZones: z.union([z.null(), z.string()]),
      forwardCgLimit: z.union([z.null(), z.string()]),
      aftCgLimit: z.union([z.null(), z.string()]),
      active: z.boolean(),
      createdAt: z.date(),
      updatedAt: z.date(),
    })
  ),
  getAircraftType: z.object({
    id: outputNumber,
    code: z.string(),
    name: z.string(),
    manufacturer: z.string(),
    maxTakeoffWeight: outputNumber,
    maxLandingWeight: outputNumber,
    maxZeroFuelWeight: outputNumber,
    operatingEmptyWeight: outputNumber,
    maxPayload: outputNumber,
    maxFuelCapacity: outputNumber,
    totalSeats: outputNumber,
    economySeats: outputNumber,
    businessSeats: outputNumber,
    cargoZones: z.union([z.null(), z.string()]),
    forwardCgLimit: z.union([z.null(), z.string()]),
    aftCgLimit: z.union([z.null(), z.string()]),
    active: z.boolean(),
    createdAt: z.date(),
    updatedAt: z.date(),
  }),
  createAircraftType: z.object({
    code: z.string(),
    name: z.string(),
    manufacturer: z.string(),
    maxTakeoffWeight: outputNumber,
    maxLandingWeight: outputNumber,
    maxZeroFuelWeight: outputNumber,
    operatingEmptyWeight: outputNumber,
    maxPayload: outputNumber,
    maxFuelCapacity: outputNumber,
    totalSeats: outputNumber,
    economySeats: outputNumber,
    businessSeats: outputNumber,
    cargoZones: z
      .union([
        z.undefined(),
        z.array(z.object({ zone: z.string(), maxWeight: outputNumber })),
      ])
      .optional(),
    forwardCgLimit: z.union([z.undefined(), z.string()]).optional(),
    aftCgLimit: z.union([z.undefined(), z.string()]).optional(),
    id: outputNumber,
  }),
  getCrewMembers: z.array(
    z.object({
      id: outputNumber,
      employeeId: z.string(),
      firstName: z.string(),
      lastName: z.string(),
      role: z.enum(["captain", "first_officer", "purser", "cabin_crew"]),
      airlineId: outputNumber,
      licenseNumber: z.union([z.null(), z.string()]),
      licenseExpiry: z.union([z.null(), z.date()]),
      medicalExpiry: z.union([z.null(), z.date()]),
      qualifiedAircraft: z.union([z.null(), z.string()]),
      status: z.enum(["active", "inactive", "on_leave", "training"]),
      phone: z.union([z.null(), z.string()]),
      email: z.union([z.null(), z.string()]),
      createdAt: z.date(),
      updatedAt: z.date(),
    })
  ),
  createCrewMember: z.object({ id: outputNumber }),
  assignCrew: z.object({ id: outputNumber }),
  getFlightCrew: z.array(
    z.object({
      assignmentId: outputNumber,
      role: z.enum(["captain", "first_officer", "purser", "cabin_crew"]),
      status: z.enum(["confirmed", "assigned", "removed", "onboard"]),
      crewId: outputNumber,
      employeeId: z.string(),
      firstName: z.string(),
      lastName: z.string(),
      licenseNumber: z.union([z.null(), z.string()]),
    })
  ),
  removeCrewAssignment: z.object({ success: z.boolean() }),
  getFlightManifest: z.object({
    manifest: z.object({
      generatedAt: z.string(),
      flight: z.object({
        id: outputNumber,
        flightNumber: z.string(),
        airline: z.object({ name: z.string(), code: z.string() }),
        aircraftType: z.union([z.null(), z.string()]),
        origin: z.object({ code: z.string(), city: z.string() }),
        destination: z.object({ code: z.string(), city: z.string() }),
        departureTime: z.date(),
        arrivalTime: z.date(),
        status: z.enum(["scheduled", "delayed", "cancelled", "completed"]),
      }),
      passengers: z.object({
        total: outputNumber,
        adults: outputNumber,
        children: outputNumber,
        infants: outputNumber,
        economy: outputNumber,
        business: outputNumber,
        list: z.array(
          z.object({
            id: outputNumber,
            bookingRef: z.string(),
            pnr: z.string(),
            name: z.string(),
            type: z.enum(["adult", "child", "infant"]),
            cabinClass: z.enum(["economy", "business"]),
            seat: z.union([z.null(), z.string()]),
          })
        ),
      }),
      crew: z.object({
        total: outputNumber,
        cockpit: z.array(
          z.object({
            assignmentId: outputNumber,
            role: z.enum(["captain", "first_officer", "purser", "cabin_crew"]),
            status: z.enum(["confirmed", "assigned", "removed", "onboard"]),
            crewId: outputNumber,
            employeeId: z.string(),
            firstName: z.string(),
            lastName: z.string(),
            licenseNumber: z.union([z.null(), z.string()]),
          })
        ),
        cabin: z.array(
          z.object({
            assignmentId: outputNumber,
            role: z.enum(["captain", "first_officer", "purser", "cabin_crew"]),
            status: z.enum(["confirmed", "assigned", "removed", "onboard"]),
            crewId: outputNumber,
            employeeId: z.string(),
            firstName: z.string(),
            lastName: z.string(),
            licenseNumber: z.union([z.null(), z.string()]),
          })
        ),
      }),
      baggage: z.object({ pieces: outputNumber, totalWeight: outputNumber }),
      capacity: z.object({
        economySeats: outputNumber,
        businessSeats: outputNumber,
        economyAvailable: outputNumber,
        businessAvailable: outputNumber,
        loadFactor: outputNumber,
      }),
    }),
  }),
  calculateWeightBalance: z.object({
    aircraft: z.object({
      code: z.string(),
      name: z.string(),
      limits: z.object({
        mtow: outputNumber,
        mlw: outputNumber,
        mzfw: outputNumber,
        oew: outputNumber,
        maxPayload: outputNumber,
        maxFuel: outputNumber,
      }),
    }),
    weights: z.object({
      operatingEmpty: outputNumber,
      passengers: z.object({ count: outputNumber, weight: outputNumber }),
      baggage: z.object({ count: outputNumber, weight: outputNumber }),
      cargo: z.object({
        zones: z.array(z.object({ zone: z.string(), weight: outputNumber })),
        weight: outputNumber,
      }),
      fuel: outputNumber,
      payload: outputNumber,
      zeroFuel: outputNumber,
      takeoff: outputNumber,
      landing: outputNumber,
    }),
    balance: z.object({
      cgPosition: outputNumber,
      forwardLimit: outputNumber,
      aftLimit: outputNumber,
    }),
    safety: z.object({
      withinLimits: z.boolean(),
      warnings: z.array(z.string()),
    }),
  }),
  createLoadPlan: z.object({
    aircraft: z.object({
      code: z.string(),
      name: z.string(),
      limits: z.object({
        mtow: outputNumber,
        mlw: outputNumber,
        mzfw: outputNumber,
        oew: outputNumber,
        maxPayload: outputNumber,
        maxFuel: outputNumber,
      }),
    }),
    weights: z.object({
      operatingEmpty: outputNumber,
      passengers: z.object({ count: outputNumber, weight: outputNumber }),
      baggage: z.object({ count: outputNumber, weight: outputNumber }),
      cargo: z.object({
        zones: z.array(z.object({ zone: z.string(), weight: outputNumber })),
        weight: outputNumber,
      }),
      fuel: outputNumber,
      payload: outputNumber,
      zeroFuel: outputNumber,
      takeoff: outputNumber,
      landing: outputNumber,
    }),
    balance: z.object({
      cgPosition: outputNumber,
      forwardLimit: outputNumber,
      aftLimit: outputNumber,
    }),
    safety: z.object({
      withinLimits: z.boolean(),
      warnings: z.array(z.string()),
    }),
    id: outputNumber,
  }),
  getLoadPlan: z.union([
    z.null(),
    z.object({
      cargoDistribution: z.array(
        z.object({ zone: z.string(), weight: outputNumber })
      ),
      warnings: z.array(z.string()),
      id: outputNumber,
      flightId: outputNumber,
      aircraftTypeId: outputNumber,
      passengerCount: outputNumber,
      passengerWeight: outputNumber,
      baggageCount: outputNumber,
      baggageWeight: outputNumber,
      totalCargoWeight: outputNumber,
      fuelWeight: outputNumber,
      zeroFuelWeight: outputNumber,
      takeoffWeight: outputNumber,
      landingWeight: outputNumber,
      cgPosition: z.union([z.null(), z.string()]),
      status: z.enum(["approved", "draft", "calculated", "finalized"]),
      withinLimits: z.boolean(),
      approvedBy: z.union([z.null(), outputNumber]),
      approvedAt: z.union([z.null(), z.date()]),
      finalizedBy: z.union([z.null(), outputNumber]),
      finalizedAt: z.union([z.null(), z.date()]),
      createdAt: z.date(),
      updatedAt: z.date(),
    }),
  ]),
  approveLoadPlan: z.object({ success: z.boolean() }),
  finalizeLoadPlan: z.object({ success: z.boolean() }),
  getStats: z.object({
    flights: z.object({
      total: outputNumber,
      scheduled: outputNumber,
      delayed: outputNumber,
      completed: outputNumber,
    }),
    crew: z.object({ total: outputNumber, active: outputNumber }),
    loadPlans: z.object({
      total: outputNumber,
      draft: outputNumber,
      approved: outputNumber,
      finalized: outputNumber,
    }),
    aircraftTypes: outputNumber,
  }),
};
