// Explicit response field allowlists. Review contract changes with producers and consumers.
import { z } from "zod";
import { outputNumber } from "./primitives";
export const responseContracts = {
  issue: z.object({
    success: z.boolean(),
    data: z.object({
      id: outputNumber,
      status: z.enum([
        "void",
        "refunded",
        "suspended",
        "used",
        "issued",
        "exchanged",
      ]),
      createdAt: z.date(),
      updatedAt: z.date(),
      flightId: z.union([z.null(), outputNumber]),
      bookingId: z.union([z.null(), outputNumber]),
      currency: z.string(),
      passengerId: z.union([z.null(), outputNumber]),
      ticketNumber: z.union([z.null(), z.string()]),
      amount: outputNumber,
      iataNumber: z.union([z.null(), z.string()]),
      expiryDate: z.union([z.null(), z.date()]),
      emdType: z.enum(["EMD-S", "EMD-A"]),
      reasonForIssuance: z.enum([
        "baggage",
        "meal",
        "insurance",
        "priority_boarding",
        "unaccompanied_minor",
        "seat_selection",
        "lounge_access",
        "pet_transport",
        "sport_equipment",
        "upgrade",
        "penalty",
        "residual_value",
        "ground_transport",
        "wifi",
        "entertainment",
        "other",
      ]),
      issuingAirlineId: outputNumber,
      issuingAgentId: z.union([z.null(), outputNumber]),
      serviceDescription: z.string(),
      rficCode: z.union([z.null(), z.string()]),
      rfiscCode: z.union([z.null(), z.string()]),
      taxAmount: outputNumber,
      flightSegment: z.union([z.null(), z.string()]),
      dateOfService: z.union([z.null(), z.date()]),
      emdNumber: z.string(),
      dateOfIssuance: z.date(),
      voidedAt: z.union([z.null(), z.date()]),
      voidReason: z.union([z.null(), z.string()]),
      exchangedFromEmd: z.union([z.null(), z.string()]),
    }),
  }),
  get: z.object({
    success: z.boolean(),
    data: z.object({
      booking: z
        .union([
          z.undefined(),
          z.null(),
          z.object({
            id: outputNumber,
            bookingReference: z.string(),
            pnr: z.string(),
            status: z.string(),
          }),
        ])
        .optional(),
      passenger: z
        .union([
          z.undefined(),
          z.null(),
          z.object({
            id: outputNumber,
            firstName: z.string(),
            lastName: z.string(),
            type: z.string(),
          }),
        ])
        .optional(),
      flight: z
        .union([
          z.undefined(),
          z.null(),
          z.object({
            id: outputNumber,
            flightNumber: z.string(),
            departureTime: z.date(),
            arrivalTime: z.date(),
          }),
        ])
        .optional(),
      issuingAirline: z
        .union([
          z.undefined(),
          z.null(),
          z.object({ id: outputNumber, code: z.string(), name: z.string() }),
        ])
        .optional(),
      id: outputNumber,
      status: z.enum([
        "void",
        "refunded",
        "suspended",
        "used",
        "issued",
        "exchanged",
      ]),
      createdAt: z.date(),
      updatedAt: z.date(),
      flightId: z.union([z.null(), outputNumber]),
      bookingId: z.union([z.null(), outputNumber]),
      currency: z.string(),
      passengerId: z.union([z.null(), outputNumber]),
      ticketNumber: z.union([z.null(), z.string()]),
      amount: outputNumber,
      iataNumber: z.union([z.null(), z.string()]),
      expiryDate: z.union([z.null(), z.date()]),
      emdType: z.enum(["EMD-S", "EMD-A"]),
      reasonForIssuance: z.enum([
        "baggage",
        "meal",
        "insurance",
        "priority_boarding",
        "unaccompanied_minor",
        "seat_selection",
        "lounge_access",
        "pet_transport",
        "sport_equipment",
        "upgrade",
        "penalty",
        "residual_value",
        "ground_transport",
        "wifi",
        "entertainment",
        "other",
      ]),
      issuingAirlineId: outputNumber,
      issuingAgentId: z.union([z.null(), outputNumber]),
      serviceDescription: z.string(),
      rficCode: z.union([z.null(), z.string()]),
      rfiscCode: z.union([z.null(), z.string()]),
      taxAmount: outputNumber,
      flightSegment: z.union([z.null(), z.string()]),
      dateOfService: z.union([z.null(), z.date()]),
      emdNumber: z.string(),
      dateOfIssuance: z.date(),
      voidedAt: z.union([z.null(), z.date()]),
      voidReason: z.union([z.null(), z.string()]),
      exchangedFromEmd: z.union([z.null(), z.string()]),
    }),
  }),
  list: z.object({
    success: z.boolean(),
    data: z.object({
      items: z.array(
        z.object({
          id: outputNumber,
          emdNumber: z.string(),
          emdType: z.enum(["EMD-S", "EMD-A"]),
          bookingId: z.union([z.null(), outputNumber]),
          passengerId: z.union([z.null(), outputNumber]),
          ticketNumber: z.union([z.null(), z.string()]),
          issuingAirlineId: outputNumber,
          issuingAgentId: z.union([z.null(), outputNumber]),
          iataNumber: z.union([z.null(), z.string()]),
          reasonForIssuance: z.enum([
            "baggage",
            "meal",
            "insurance",
            "priority_boarding",
            "unaccompanied_minor",
            "seat_selection",
            "lounge_access",
            "pet_transport",
            "sport_equipment",
            "upgrade",
            "penalty",
            "residual_value",
            "ground_transport",
            "wifi",
            "entertainment",
            "other",
          ]),
          serviceDescription: z.string(),
          rficCode: z.union([z.null(), z.string()]),
          rfiscCode: z.union([z.null(), z.string()]),
          amount: outputNumber,
          currency: z.string(),
          taxAmount: outputNumber,
          status: z.enum([
            "void",
            "refunded",
            "suspended",
            "used",
            "issued",
            "exchanged",
          ]),
          flightId: z.union([z.null(), outputNumber]),
          flightSegment: z.union([z.null(), z.string()]),
          dateOfIssuance: z.date(),
          dateOfService: z.union([z.null(), z.date()]),
          expiryDate: z.union([z.null(), z.date()]),
          voidedAt: z.union([z.null(), z.date()]),
          voidReason: z.union([z.null(), z.string()]),
          exchangedFromEmd: z.union([z.null(), z.string()]),
          createdAt: z.date(),
          updatedAt: z.date(),
        })
      ),
      total: outputNumber,
      page: outputNumber,
      limit: outputNumber,
      totalPages: outputNumber,
      hasMore: z.boolean(),
    }),
  }),
  use: z.object({
    success: z.boolean(),
    data: z.object({
      id: outputNumber,
      status: z.enum([
        "void",
        "refunded",
        "suspended",
        "used",
        "issued",
        "exchanged",
      ]),
      createdAt: z.date(),
      updatedAt: z.date(),
      flightId: z.union([z.null(), outputNumber]),
      bookingId: z.union([z.null(), outputNumber]),
      currency: z.string(),
      passengerId: z.union([z.null(), outputNumber]),
      ticketNumber: z.union([z.null(), z.string()]),
      amount: outputNumber,
      iataNumber: z.union([z.null(), z.string()]),
      expiryDate: z.union([z.null(), z.date()]),
      emdType: z.enum(["EMD-S", "EMD-A"]),
      reasonForIssuance: z.enum([
        "baggage",
        "meal",
        "insurance",
        "priority_boarding",
        "unaccompanied_minor",
        "seat_selection",
        "lounge_access",
        "pet_transport",
        "sport_equipment",
        "upgrade",
        "penalty",
        "residual_value",
        "ground_transport",
        "wifi",
        "entertainment",
        "other",
      ]),
      issuingAirlineId: outputNumber,
      issuingAgentId: z.union([z.null(), outputNumber]),
      serviceDescription: z.string(),
      rficCode: z.union([z.null(), z.string()]),
      rfiscCode: z.union([z.null(), z.string()]),
      taxAmount: outputNumber,
      flightSegment: z.union([z.null(), z.string()]),
      dateOfService: z.union([z.null(), z.date()]),
      emdNumber: z.string(),
      dateOfIssuance: z.date(),
      voidedAt: z.union([z.null(), z.date()]),
      voidReason: z.union([z.null(), z.string()]),
      exchangedFromEmd: z.union([z.null(), z.string()]),
    }),
  }),
  void: z.object({
    success: z.boolean(),
    data: z.object({
      id: outputNumber,
      status: z.enum([
        "void",
        "refunded",
        "suspended",
        "used",
        "issued",
        "exchanged",
      ]),
      createdAt: z.date(),
      updatedAt: z.date(),
      flightId: z.union([z.null(), outputNumber]),
      bookingId: z.union([z.null(), outputNumber]),
      currency: z.string(),
      passengerId: z.union([z.null(), outputNumber]),
      ticketNumber: z.union([z.null(), z.string()]),
      amount: outputNumber,
      iataNumber: z.union([z.null(), z.string()]),
      expiryDate: z.union([z.null(), z.date()]),
      emdType: z.enum(["EMD-S", "EMD-A"]),
      reasonForIssuance: z.enum([
        "baggage",
        "meal",
        "insurance",
        "priority_boarding",
        "unaccompanied_minor",
        "seat_selection",
        "lounge_access",
        "pet_transport",
        "sport_equipment",
        "upgrade",
        "penalty",
        "residual_value",
        "ground_transport",
        "wifi",
        "entertainment",
        "other",
      ]),
      issuingAirlineId: outputNumber,
      issuingAgentId: z.union([z.null(), outputNumber]),
      serviceDescription: z.string(),
      rficCode: z.union([z.null(), z.string()]),
      rfiscCode: z.union([z.null(), z.string()]),
      taxAmount: outputNumber,
      flightSegment: z.union([z.null(), z.string()]),
      dateOfService: z.union([z.null(), z.date()]),
      emdNumber: z.string(),
      dateOfIssuance: z.date(),
      voidedAt: z.union([z.null(), z.date()]),
      voidReason: z.union([z.null(), z.string()]),
      exchangedFromEmd: z.union([z.null(), z.string()]),
    }),
  }),
  exchange: z.object({
    success: z.boolean(),
    data: z.object({
      originalEmdNumber: z.string(),
      originalStatus: z.enum([
        "void",
        "refunded",
        "suspended",
        "used",
        "issued",
        "exchanged",
      ]),
      newEmdNumber: z.string(),
      newEmdId: outputNumber,
      amountDifference: outputNumber,
    }),
  }),
  refund: z.object({
    success: z.boolean(),
    data: z.object({
      emdNumber: z.string(),
      originalAmount: outputNumber,
      refundAmount: outputNumber,
      taxRefund: outputNumber,
      totalRefund: outputNumber,
      isPartialRefund: z.boolean(),
      status: z.enum([
        "void",
        "refunded",
        "suspended",
        "used",
        "issued",
        "exchanged",
      ]),
    }),
  }),
  getByBooking: z.object({
    success: z.boolean(),
    data: z.array(
      z.object({
        id: outputNumber,
        status: z.enum([
          "void",
          "refunded",
          "suspended",
          "used",
          "issued",
          "exchanged",
        ]),
        createdAt: z.date(),
        updatedAt: z.date(),
        flightId: z.union([z.null(), outputNumber]),
        bookingId: z.union([z.null(), outputNumber]),
        currency: z.string(),
        passengerId: z.union([z.null(), outputNumber]),
        ticketNumber: z.union([z.null(), z.string()]),
        amount: outputNumber,
        iataNumber: z.union([z.null(), z.string()]),
        expiryDate: z.union([z.null(), z.date()]),
        emdType: z.enum(["EMD-S", "EMD-A"]),
        reasonForIssuance: z.enum([
          "baggage",
          "meal",
          "insurance",
          "priority_boarding",
          "unaccompanied_minor",
          "seat_selection",
          "lounge_access",
          "pet_transport",
          "sport_equipment",
          "upgrade",
          "penalty",
          "residual_value",
          "ground_transport",
          "wifi",
          "entertainment",
          "other",
        ]),
        issuingAirlineId: outputNumber,
        issuingAgentId: z.union([z.null(), outputNumber]),
        serviceDescription: z.string(),
        rficCode: z.union([z.null(), z.string()]),
        rfiscCode: z.union([z.null(), z.string()]),
        taxAmount: outputNumber,
        flightSegment: z.union([z.null(), z.string()]),
        dateOfService: z.union([z.null(), z.date()]),
        emdNumber: z.string(),
        dateOfIssuance: z.date(),
        voidedAt: z.union([z.null(), z.date()]),
        voidReason: z.union([z.null(), z.string()]),
        exchangedFromEmd: z.union([z.null(), z.string()]),
      })
    ),
  }),
  statistics: z.object({
    success: z.boolean(),
    data: z.object({
      airlineId: outputNumber,
      period: z.object({
        from: z.union([z.null(), z.string()]),
        to: z.union([z.null(), z.string()]),
      }),
      totals: z.object({
        count: outputNumber,
        amount: outputNumber,
        taxAmount: outputNumber,
        averageAmount: outputNumber,
      }),
      byStatus: z.array(
        z.object({
          status: z.string(),
          count: outputNumber,
          totalAmount: outputNumber,
        })
      ),
      byType: z.array(
        z.object({
          emdType: z.string(),
          count: outputNumber,
          totalAmount: outputNumber,
        })
      ),
      byReason: z.array(
        z.object({
          reason: z.string(),
          count: outputNumber,
          totalAmount: outputNumber,
        })
      ),
    }),
  }),
};
