// Explicit response field allowlists. Review contract changes with producers and consumers.
import { z } from "zod";
import { outputNumber } from "./primitives";
export const responseContracts = {
  findHotels: z.array(
    z.object({
      estimatedNights: outputNumber,
      estimatedTotalStandard: outputNumber,
      estimatedTotalSuite: outputNumber,
      id: outputNumber,
      name: z.string(),
      airportId: outputNumber,
      address: z.string(),
      phone: z.string(),
      email: z.string(),
      starRating: outputNumber,
      standardRate: outputNumber,
      distanceKm: z.string(),
      hasTransport: z.boolean(),
      isActive: z.boolean(),
      createdAt: z.date(),
    })
  ),
  bookRoom: z.object({
    hotelName: z.string(),
    hotelAddress: z.string(),
    hotelPhone: z.string(),
    id: outputNumber,
    hotelId: outputNumber,
    bookingId: outputNumber,
    flightId: outputNumber,
    passengerId: outputNumber,
    roomType: z.enum(["standard", "suite"]),
    checkIn: z.date(),
    checkOut: z.date(),
    nightlyRate: outputNumber,
    totalCost: outputNumber,
    mealIncluded: z.boolean(),
    transportIncluded: z.boolean(),
    status: z.enum([
      "cancelled",
      "checked_in",
      "reserved",
      "checked_out",
      "no_show",
    ]),
    confirmationNumber: z.string(),
    notes: z.union([z.null(), z.string()]),
    createdAt: z.date(),
    updatedAt: z.date(),
  }),
  getMyHotelBookings: z.array(
    z.object({
      id: outputNumber,
      hotelId: outputNumber,
      bookingId: outputNumber,
      flightId: outputNumber,
      passengerId: outputNumber,
      roomType: z.enum(["standard", "suite"]),
      checkIn: z.date(),
      checkOut: z.date(),
      nightlyRate: outputNumber,
      totalCost: outputNumber,
      mealIncluded: z.boolean(),
      transportIncluded: z.boolean(),
      status: z.enum([
        "cancelled",
        "checked_in",
        "reserved",
        "checked_out",
        "no_show",
      ]),
      confirmationNumber: z.string(),
      notes: z.union([z.null(), z.string()]),
      createdAt: z.date(),
      hotelName: z.string(),
      hotelAddress: z.string(),
      hotelPhone: z.string(),
      hotelStarRating: outputNumber,
      flightNumber: z.string(),
    })
  ),
  getFlightHotelBookings: z.array(
    z.object({
      id: outputNumber,
      hotelId: outputNumber,
      bookingId: outputNumber,
      flightId: outputNumber,
      passengerId: outputNumber,
      roomType: z.enum(["standard", "suite"]),
      checkIn: z.date(),
      checkOut: z.date(),
      nightlyRate: outputNumber,
      totalCost: outputNumber,
      mealIncluded: z.boolean(),
      transportIncluded: z.boolean(),
      status: z.enum([
        "cancelled",
        "checked_in",
        "reserved",
        "checked_out",
        "no_show",
      ]),
      confirmationNumber: z.string(),
      notes: z.union([z.null(), z.string()]),
      createdAt: z.date(),
      hotelName: z.string(),
      hotelAddress: z.string(),
      hotelPhone: z.string(),
      hotelStarRating: outputNumber,
    })
  ),
  cancelBooking: z.object({
    success: z.boolean(),
    confirmationNumber: z.string(),
  }),
  checkEntitlement: z.object({
    entitled: z.boolean(),
    hotelIncluded: z.boolean(),
    mealsIncluded: z.boolean(),
    transportIncluded: z.boolean(),
    reason: z.string(),
  }),
  getCosts: z.object({
    summary: z.object({
      totalCost: outputNumber,
      activeTotalCost: outputNumber,
      totalBookings: outputNumber,
      cancelledBookings: outputNumber,
      activeBookings: outputNumber,
    }),
    byHotel: z.array(
      z.object({
        hotelId: outputNumber,
        hotelName: z.string(),
        totalCost: outputNumber,
        bookingCount: outputNumber,
      })
    ),
    dateRange: z.object({ from: z.date(), to: z.date() }),
  }),
  getHotels: z.array(
    z.object({
      id: outputNumber,
      name: z.string(),
      airportId: outputNumber,
      address: z.string(),
      phone: z.string(),
      email: z.string(),
      starRating: outputNumber,
      standardRate: outputNumber,
      distanceKm: z.string(),
      hasTransport: z.boolean(),
      isActive: z.boolean(),
      createdAt: z.date(),
      airportCode: z.union([z.null(), z.string()]),
      airportCity: z.union([z.null(), z.string()]),
    })
  ),
  addHotel: z.object({
    id: outputNumber,
    name: z.string(),
    airportId: outputNumber,
    address: z.string(),
    phone: z.string(),
    email: z.string(),
    starRating: outputNumber,
    standardRate: outputNumber,
    distanceKm: z.string(),
    hasTransport: z.boolean(),
    isActive: z.boolean(),
    createdAt: z.date(),
  }),
  updateHotel: z.object({
    id: outputNumber,
    name: z.string(),
    airportId: outputNumber,
    address: z.string(),
    phone: z.string(),
    email: z.string(),
    starRating: outputNumber,
    standardRate: outputNumber,
    distanceKm: z.string(),
    hasTransport: z.boolean(),
    isActive: z.boolean(),
    createdAt: z.date(),
  }),
  assignTransport: z.object({
    success: z.boolean(),
    transportType: z.enum(["shuttle", "taxi", "private_car"]),
    confirmationNumber: z.string(),
  }),
};
