// Explicit response field allowlists. Review contract changes with producers and consumers.
import { z } from "zod";
import { outputNumber } from "./primitives";
export const responseContracts = {
  createFareClass: z.object({ id: outputNumber }),
  updateFareClass: z.object({ success: z.boolean() }),
  getFareClass: z.object({
    id: outputNumber,
    airlineId: outputNumber,
    name: z.string(),
    createdAt: z.date(),
    updatedAt: z.date(),
    code: z.string(),
    active: z.boolean(),
    cabinClass: z.enum(["economy", "business", "first", "premium_economy"]),
    priority: outputNumber,
    mealIncluded: z.boolean(),
    fareFamily: z.union([z.null(), z.string()]),
    basePriceMultiplier: z.string(),
    seatsAllocated: z.union([z.null(), outputNumber]),
    refundable: z.boolean(),
    changeable: z.boolean(),
    changeFee: z.union([z.null(), outputNumber]),
    upgradeable: z.boolean(),
    baggageAllowance: z.union([z.null(), outputNumber]),
    baggagePieces: z.union([z.null(), outputNumber]),
    carryOnAllowance: z.union([z.null(), outputNumber]),
    mileageEarningRate: z.union([z.null(), z.string()]),
    seatSelection: z.union([
      z.null(),
      z.literal("paid"),
      z.literal("none"),
      z.literal("free"),
    ]),
    loungeAccess: z.boolean(),
    priorityBoarding: z.boolean(),
  }),
  listFareClasses: z.array(
    z.object({
      id: outputNumber,
      airlineId: outputNumber,
      name: z.string(),
      createdAt: z.date(),
      updatedAt: z.date(),
      code: z.string(),
      active: z.boolean(),
      cabinClass: z.enum(["economy", "business", "first", "premium_economy"]),
      priority: outputNumber,
      mealIncluded: z.boolean(),
      fareFamily: z.union([z.null(), z.string()]),
      basePriceMultiplier: z.string(),
      seatsAllocated: z.union([z.null(), outputNumber]),
      refundable: z.boolean(),
      changeable: z.boolean(),
      changeFee: z.union([z.null(), outputNumber]),
      upgradeable: z.boolean(),
      baggageAllowance: z.union([z.null(), outputNumber]),
      baggagePieces: z.union([z.null(), outputNumber]),
      carryOnAllowance: z.union([z.null(), outputNumber]),
      mileageEarningRate: z.union([z.null(), z.string()]),
      seatSelection: z.union([
        z.null(),
        z.literal("paid"),
        z.literal("none"),
        z.literal("free"),
      ]),
      loungeAccess: z.boolean(),
      priorityBoarding: z.boolean(),
    })
  ),
  getFareClassAvailability: z.object({
    flightId: outputNumber,
    fareClasses: z.array(
      z.object({
        id: outputNumber,
        airlineId: outputNumber,
        name: z.string(),
        createdAt: z.date(),
        updatedAt: z.date(),
        code: z.string(),
        active: z.boolean(),
        cabinClass: z.enum(["economy", "business", "first", "premium_economy"]),
        priority: outputNumber,
        mealIncluded: z.boolean(),
        fareFamily: z.union([z.null(), z.string()]),
        basePriceMultiplier: z.string(),
        seatsAllocated: z.union([z.null(), outputNumber]),
        refundable: z.boolean(),
        changeable: z.boolean(),
        changeFee: z.union([z.null(), outputNumber]),
        upgradeable: z.boolean(),
        baggageAllowance: z.union([z.null(), outputNumber]),
        baggagePieces: z.union([z.null(), outputNumber]),
        carryOnAllowance: z.union([z.null(), outputNumber]),
        mileageEarningRate: z.union([z.null(), z.string()]),
        seatSelection: z.union([
          z.null(),
          z.literal("paid"),
          z.literal("none"),
          z.literal("free"),
        ]),
        loungeAccess: z.boolean(),
        priorityBoarding: z.boolean(),
        availableSeats: outputNumber,
        totalAllocated: outputNumber,
      })
    ),
  }),
  createFareRule: z.object({ id: outputNumber }),
  updateFareRule: z.object({ success: z.boolean() }),
  getFareRule: z.object({
    id: outputNumber,
    airlineId: outputNumber,
    createdAt: z.date(),
    updatedAt: z.date(),
    active: z.boolean(),
    validFrom: z.date(),
    validUntil: z.union([z.null(), z.date()]),
    priceMultiplier: z.union([z.null(), z.string()]),
    conditions: z.string(),
    fareClassId: outputNumber,
    ruleName: z.string(),
    ruleCategory: z.enum([
      "eligibility",
      "day_time",
      "seasonality",
      "flight_application",
      "advance_purchase",
      "minimum_stay",
      "maximum_stay",
      "stopovers",
      "transfers",
      "combinations",
      "blackout_dates",
      "surcharges",
      "penalties",
      "children_discount",
      "group_discount",
    ]),
    originAirportId: z.union([z.null(), outputNumber]),
    destinationAirportId: z.union([z.null(), outputNumber]),
    priceAdjustment: z.union([z.null(), outputNumber]),
    fareClass: z
      .union([
        z.undefined(),
        z.object({
          id: outputNumber,
          airlineId: outputNumber,
          name: z.string(),
          createdAt: z.date(),
          updatedAt: z.date(),
          code: z.string(),
          active: z.boolean(),
          cabinClass: z.enum([
            "economy",
            "business",
            "first",
            "premium_economy",
          ]),
          priority: outputNumber,
          mealIncluded: z.boolean(),
          fareFamily: z.union([z.null(), z.string()]),
          basePriceMultiplier: z.string(),
          seatsAllocated: z.union([z.null(), outputNumber]),
          refundable: z.boolean(),
          changeable: z.boolean(),
          changeFee: z.union([z.null(), outputNumber]),
          upgradeable: z.boolean(),
          baggageAllowance: z.union([z.null(), outputNumber]),
          baggagePieces: z.union([z.null(), outputNumber]),
          carryOnAllowance: z.union([z.null(), outputNumber]),
          mileageEarningRate: z.union([z.null(), z.string()]),
          seatSelection: z.union([
            z.null(),
            z.literal("paid"),
            z.literal("none"),
            z.literal("free"),
          ]),
          loungeAccess: z.boolean(),
          priorityBoarding: z.boolean(),
        }),
      ])
      .optional(),
  }),
  listFareRules: z.object({
    rules: z.array(
      z.object({
        id: outputNumber,
        airlineId: outputNumber,
        createdAt: z.date(),
        updatedAt: z.date(),
        active: z.boolean(),
        validFrom: z.date(),
        validUntil: z.union([z.null(), z.date()]),
        priceMultiplier: z.union([z.null(), z.string()]),
        conditions: z.string(),
        fareClassId: outputNumber,
        ruleName: z.string(),
        ruleCategory: z.enum([
          "eligibility",
          "day_time",
          "seasonality",
          "flight_application",
          "advance_purchase",
          "minimum_stay",
          "maximum_stay",
          "stopovers",
          "transfers",
          "combinations",
          "blackout_dates",
          "surcharges",
          "penalties",
          "children_discount",
          "group_discount",
        ]),
        originAirportId: z.union([z.null(), outputNumber]),
        destinationAirportId: z.union([z.null(), outputNumber]),
        priceAdjustment: z.union([z.null(), outputNumber]),
      })
    ),
    total: outputNumber,
  }),
  calculateFare: z.object({
    baseFare: outputNumber,
    fareClassMultiplier: z.string(),
    adjustedFare: outputNumber,
    surcharges: outputNumber,
    taxes: outputNumber,
    totalPerPassenger: outputNumber,
    totalAmount: outputNumber,
    currency: z.string(),
    appliedRules: z.array(
      z.object({
        ruleId: outputNumber,
        ruleName: z.string(),
        category: z.string(),
        adjustment: outputNumber,
        multiplier: z.string(),
      })
    ),
    passengerType: z.string(),
    passengerCount: outputNumber,
  }),
  validateRules: z.object({
    valid: z.boolean(),
    violations: z.array(
      z.object({
        ruleId: outputNumber,
        ruleName: z.string(),
        category: z.string(),
        message: z.string(),
      })
    ),
  }),
  compareFareClasses: z.object({
    flightId: outputNumber,
    comparisons: z.array(
      z.object({
        fareClass: z.object({
          id: outputNumber,
          airlineId: outputNumber,
          name: z.string(),
          createdAt: z.date(),
          updatedAt: z.date(),
          code: z.string(),
          active: z.boolean(),
          cabinClass: z.enum([
            "economy",
            "business",
            "first",
            "premium_economy",
          ]),
          priority: outputNumber,
          mealIncluded: z.boolean(),
          fareFamily: z.union([z.null(), z.string()]),
          basePriceMultiplier: z.string(),
          seatsAllocated: z.union([z.null(), outputNumber]),
          refundable: z.boolean(),
          changeable: z.boolean(),
          changeFee: z.union([z.null(), outputNumber]),
          upgradeable: z.boolean(),
          baggageAllowance: z.union([z.null(), outputNumber]),
          baggagePieces: z.union([z.null(), outputNumber]),
          carryOnAllowance: z.union([z.null(), outputNumber]),
          mileageEarningRate: z.union([z.null(), z.string()]),
          seatSelection: z.union([
            z.null(),
            z.literal("paid"),
            z.literal("none"),
            z.literal("free"),
          ]),
          loungeAccess: z.boolean(),
          priorityBoarding: z.boolean(),
        }),
        estimatedFare: outputNumber,
        surcharges: outputNumber,
        taxes: outputNumber,
        total: outputNumber,
        rulesApplied: outputNumber,
        features: z.object({
          refundable: z.boolean(),
          changeable: z.boolean(),
          changeFee: z.union([z.null(), outputNumber]),
          upgradeable: z.boolean(),
          baggageAllowance: z.union([z.null(), outputNumber]),
          baggagePieces: z.union([z.null(), outputNumber]),
          carryOnAllowance: z.union([z.null(), outputNumber]),
          seatSelection: z.union([z.null(), z.string()]),
          loungeAccess: z.boolean(),
          priorityBoarding: z.boolean(),
          mealIncluded: z.boolean(),
          mileageEarningRate: z.union([z.null(), z.string()]),
        }),
        availableSeats: outputNumber,
        isAvailable: z.boolean(),
      })
    ),
  }),
  calculateChangeFee: z.object({
    fareClassId: outputNumber,
    changeable: z.boolean(),
    baseFee: outputNumber,
    additionalFees: outputNumber,
    totalFee: outputNumber,
    currency: z.string(),
    rules: z.array(
      z.object({
        ruleId: outputNumber,
        ruleName: z.string(),
        feeContribution: outputNumber,
      })
    ),
  }),
};
