// Explicit response field allowlists. Review contract changes with producers and consumers.
import { z } from "zod";
import { outputNumber } from "./primitives";
export const responseContracts = {
  trackByNumber: z.object({
    flight: z.object({
      id: outputNumber,
      flightNumber: z.string(),
      status: z.string(),
      departureTime: z.date(),
      arrivalTime: z.date(),
      aircraftType: z.string(),
      origin: z.object({
        code: z.string(),
        city: z.string(),
        name: z.string(),
      }),
      destination: z.object({
        code: z.string(),
        city: z.string(),
        name: z.string(),
      }),
    }),
    currentPosition: z.union([
      z.null(),
      z.object({
        latitude: outputNumber,
        longitude: outputNumber,
        altitude: outputNumber,
        heading: outputNumber,
        groundSpeed: outputNumber,
        phase: z.enum([
          "arrived",
          "boarding",
          "taxiing",
          "takeoff",
          "climbing",
          "cruising",
          "descending",
          "approach",
          "landing",
        ]),
        estimatedArrival: z.union([z.null(), z.date()]),
        temperature: z.union([z.null(), outputNumber]),
        windSpeed: z.union([z.null(), outputNumber]),
        windDirection: z.union([z.null(), outputNumber]),
        turbulence: z.union([
          z.null(),
          z.literal("none"),
          z.literal("moderate"),
          z.literal("severe"),
          z.literal("light"),
        ]),
        distanceCovered: z.union([z.null(), outputNumber]),
        distanceRemaining: z.union([z.null(), outputNumber]),
        progressPercent: z.union([z.null(), outputNumber]),
        recordedAt: z.date(),
      }),
    ]),
    trail: z.array(
      z.object({
        latitude: outputNumber,
        longitude: outputNumber,
        altitude: outputNumber,
        heading: outputNumber,
        groundSpeed: outputNumber,
        phase: z.enum([
          "arrived",
          "boarding",
          "taxiing",
          "takeoff",
          "climbing",
          "cruising",
          "descending",
          "approach",
          "landing",
        ]),
        estimatedArrival: z.union([z.null(), z.date()]),
        temperature: z.union([z.null(), outputNumber]),
        windSpeed: z.union([z.null(), outputNumber]),
        windDirection: z.union([z.null(), outputNumber]),
        turbulence: z.union([
          z.null(),
          z.literal("none"),
          z.literal("moderate"),
          z.literal("severe"),
          z.literal("light"),
        ]),
        distanceCovered: z.union([z.null(), outputNumber]),
        distanceRemaining: z.union([z.null(), outputNumber]),
        progressPercent: z.union([z.null(), outputNumber]),
        recordedAt: z.date(),
      })
    ),
  }),
  trackById: z.object({
    flight: z.object({
      id: outputNumber,
      flightNumber: z.string(),
      status: z.string(),
      departureTime: z.date(),
      arrivalTime: z.date(),
      aircraftType: z.string(),
      origin: z.object({
        code: z.string(),
        city: z.string(),
        name: z.string(),
      }),
      destination: z.object({
        code: z.string(),
        city: z.string(),
        name: z.string(),
      }),
    }),
    currentPosition: z.union([
      z.null(),
      z.object({
        latitude: outputNumber,
        longitude: outputNumber,
        altitude: outputNumber,
        heading: outputNumber,
        groundSpeed: outputNumber,
        phase: z.enum([
          "arrived",
          "boarding",
          "taxiing",
          "takeoff",
          "climbing",
          "cruising",
          "descending",
          "approach",
          "landing",
        ]),
        estimatedArrival: z.union([z.null(), z.date()]),
        temperature: z.union([z.null(), outputNumber]),
        windSpeed: z.union([z.null(), outputNumber]),
        windDirection: z.union([z.null(), outputNumber]),
        turbulence: z.union([
          z.null(),
          z.literal("none"),
          z.literal("moderate"),
          z.literal("severe"),
          z.literal("light"),
        ]),
        distanceCovered: z.union([z.null(), outputNumber]),
        distanceRemaining: z.union([z.null(), outputNumber]),
        progressPercent: z.union([z.null(), outputNumber]),
        recordedAt: z.date(),
      }),
    ]),
    trail: z.array(
      z.object({
        latitude: outputNumber,
        longitude: outputNumber,
        altitude: outputNumber,
        heading: outputNumber,
        groundSpeed: outputNumber,
        phase: z.enum([
          "arrived",
          "boarding",
          "taxiing",
          "takeoff",
          "climbing",
          "cruising",
          "descending",
          "approach",
          "landing",
        ]),
        estimatedArrival: z.union([z.null(), z.date()]),
        temperature: z.union([z.null(), outputNumber]),
        windSpeed: z.union([z.null(), outputNumber]),
        windDirection: z.union([z.null(), outputNumber]),
        turbulence: z.union([
          z.null(),
          z.literal("none"),
          z.literal("moderate"),
          z.literal("severe"),
          z.literal("light"),
        ]),
        distanceCovered: z.union([z.null(), outputNumber]),
        distanceRemaining: z.union([z.null(), outputNumber]),
        progressPercent: z.union([z.null(), outputNumber]),
        recordedAt: z.date(),
      })
    ),
  }),
  activeFlights: z.array(
    z.object({
      flightId: outputNumber,
      flightNumber: z.string(),
      origin: z.string(),
      destination: z.string(),
      position: z.object({
        latitude: outputNumber,
        longitude: outputNumber,
        altitude: outputNumber,
        heading: outputNumber,
        groundSpeed: outputNumber,
        phase: z.enum([
          "arrived",
          "boarding",
          "taxiing",
          "takeoff",
          "climbing",
          "cruising",
          "descending",
          "approach",
          "landing",
        ]),
        estimatedArrival: z.union([z.null(), z.date()]),
        temperature: z.union([z.null(), outputNumber]),
        windSpeed: z.union([z.null(), outputNumber]),
        windDirection: z.union([z.null(), outputNumber]),
        turbulence: z.union([
          z.null(),
          z.literal("none"),
          z.literal("moderate"),
          z.literal("severe"),
          z.literal("light"),
        ]),
        distanceCovered: z.union([z.null(), outputNumber]),
        distanceRemaining: z.union([z.null(), outputNumber]),
        progressPercent: z.union([z.null(), outputNumber]),
        recordedAt: z.date(),
      }),
    })
  ),
  recordPosition: z.object({ success: z.boolean(), id: outputNumber }),
};
