// Explicit response field allowlists. Review contract changes with producers and consumers.
import { z } from "zod";
import { outputNumber } from "./primitives";
export const responseContracts = {
  createConnection: z.object({
    success: z.boolean(),
    data: z.object({
      id: outputNumber,
      connectionName: z.string(),
      provider: z.enum(["amadeus", "sabre", "travelport", "travelsky"]),
    }),
  }),
  updateConnection: z.object({
    success: z.boolean(),
    data: z.object({ success: z.literal(true) }),
  }),
  getConnection: z.object({
    success: z.boolean(),
    data: z.object({
      id: outputNumber,
      airlineId: outputNumber,
      status: z.enum(["active", "error", "maintenance", "inactive"]),
      createdAt: z.date(),
      updatedAt: z.date(),
      provider: z.enum(["amadeus", "sabre", "travelport", "travelsky"]),
      environment: z.enum(["production", "certification", "test"]),
      baseUrl: z.union([z.null(), z.string()]),
      connectionName: z.string(),
      pseudoCityCode: z.union([z.null(), z.string()]),
      officeId: z.union([z.null(), z.string()]),
      supportsBooking: z.boolean(),
      supportsTicketing: z.boolean(),
      supportsSchedules: z.boolean(),
      supportsPricing: z.boolean(),
      supportsAvailability: z.boolean(),
      maxRequestsPerMinute: z.union([z.null(), outputNumber]),
      maxRequestsPerDay: z.union([z.null(), outputNumber]),
      lastHealthCheck: z.union([z.null(), z.date()]),
      lastError: z.union([z.null(), z.string()]),
      apiKey: z.union([z.null(), z.string()]),
    }),
  }),
  listConnections: z.object({
    success: z.boolean(),
    data: z.array(
      z.object({
        id: outputNumber,
        airlineId: outputNumber,
        status: z.enum(["active", "error", "maintenance", "inactive"]),
        createdAt: z.date(),
        updatedAt: z.date(),
        provider: z.enum(["amadeus", "sabre", "travelport", "travelsky"]),
        environment: z.enum(["production", "certification", "test"]),
        baseUrl: z.union([z.null(), z.string()]),
        connectionName: z.string(),
        pseudoCityCode: z.union([z.null(), z.string()]),
        officeId: z.union([z.null(), z.string()]),
        supportsBooking: z.boolean(),
        supportsTicketing: z.boolean(),
        supportsSchedules: z.boolean(),
        supportsPricing: z.boolean(),
        supportsAvailability: z.boolean(),
        maxRequestsPerMinute: z.union([z.null(), outputNumber]),
        maxRequestsPerDay: z.union([z.null(), outputNumber]),
        lastHealthCheck: z.union([z.null(), z.date()]),
        lastError: z.union([z.null(), z.string()]),
        apiKey: z.union([z.null(), z.string()]),
      })
    ),
  }),
  testConnection: z.object({
    success: z.boolean(),
    data: z.object({
      connectionId: outputNumber,
      provider: z.enum(["amadeus", "sabre", "travelport", "travelsky"]),
      healthy: z.boolean(),
      responseTimeMs: outputNumber,
      message: z.string(),
    }),
  }),
  searchAvailability: z.object({
    success: z.boolean(),
    data: z.object({
      correlationId: z.string(),
      provider: z.enum(["amadeus", "sabre", "travelport", "travelsky"]),
      flights: z.array(
        z.object({
          flightNumber: z.string(),
          airline: z.string(),
          origin: z.string(),
          destination: z.string(),
          departureTime: z.string(),
          arrivalTime: z.string(),
          cabinClass: z.string(),
          seatsAvailable: outputNumber,
          fare: z.object({
            amount: outputNumber,
            currency: z.string(),
            fareClass: z.string(),
            fareBasis: z.string(),
          }),
          stops: outputNumber,
          duration: z.string(),
        })
      ),
      responseTimeMs: outputNumber,
    }),
  }),
  createGdsBooking: z.object({
    success: z.boolean(),
    data: z.object({
      correlationId: z.string(),
      provider: z.enum(["amadeus", "sabre", "travelport", "travelsky"]),
      pnrLocator: z.string(),
      status: z.enum(["pending", "confirmed", "waitlisted"]),
      segments: z.array(
        z.object({
          flightNumber: z.string(),
          origin: z.string(),
          destination: z.string(),
          departureTime: z.string(),
          arrivalTime: z.string(),
          cabinClass: z.string(),
          fareClass: z.string(),
          status: z.string(),
        })
      ),
      ticketTimeLimit: z.string(),
      totalFare: z.object({ amount: outputNumber, currency: z.string() }),
      responseTimeMs: outputNumber,
    }),
  }),
  getMessageLog: z.object({
    success: z.boolean(),
    data: z.object({
      messages: z.array(
        z.object({
          id: outputNumber,
          status: z.enum(["error", "success", "pending", "timeout"]),
          createdAt: z.date(),
          bookingReference: z.union([z.null(), z.string()]),
          provider: z.enum(["amadeus", "sabre", "travelport", "travelsky"]),
          errorMessage: z.union([z.null(), z.string()]),
          connectionId: outputNumber,
          messageType: z.enum([
            "availability_request",
            "availability_response",
            "pricing_request",
            "pricing_response",
            "booking_request",
            "booking_response",
            "ticketing_request",
            "ticketing_response",
            "cancel_request",
            "cancel_response",
            "schedule_request",
            "schedule_response",
          ]),
          direction: z.enum(["outbound", "inbound"]),
          requestPayload: z.union([z.null(), z.string()]),
          responsePayload: z.union([z.null(), z.string()]),
          correlationId: z.string(),
          responseTimeMs: z.union([z.null(), outputNumber]),
          httpStatusCode: z.union([z.null(), outputNumber]),
        })
      ),
      total: outputNumber,
      page: outputNumber,
      totalPages: outputNumber,
    }),
  }),
  getStatistics: z.object({
    success: z.boolean(),
    data: z.object({
      connectionId: outputNumber,
      provider: z.enum(["amadeus", "sabre", "travelport", "travelsky"]),
      totalMessages: outputNumber,
      successCount: outputNumber,
      errorCount: outputNumber,
      timeoutCount: outputNumber,
      successRate: outputNumber,
      avgResponseTimeMs: outputNumber,
      minResponseTimeMs: outputNumber,
      maxResponseTimeMs: outputNumber,
      messagesByType: z.record(z.string(), outputNumber),
      last24hVolume: outputNumber,
      last24hErrorRate: outputNumber,
    }),
  }),
};
