// Explicit response field allowlists. Review contract changes with producers and consumers.
import { z } from "zod";
import { outputNumber, structuredValue } from "./primitives";
export const responseContracts = {
  getDashboard: z.object({
    activeDisruptions: outputNumber,
    totalPassengersAffected: outputNumber,
    connectionsAtRisk: outputNumber,
    recoveryRate: outputNumber,
    criticalEvents: outputNumber,
    recentEvents: z.array(
      z.object({
        id: outputNumber,
        flightId: outputNumber,
        eventType: z.enum([
          "delay",
          "cancellation",
          "diversion",
          "equipment_change",
        ]),
        severity: z.enum(["high", "medium", "low", "critical"]),
        delayMinutes: z.union([z.null(), outputNumber]),
        reason: z.string(),
        affectedPassengers: outputNumber,
        connectionsAtRisk: outputNumber,
        estimatedRecoveryTime: z.union([z.null(), z.date()]),
        status: z.enum(["active", "resolved", "recovering"]),
        escalationLevel: outputNumber,
        createdBy: z.union([z.null(), outputNumber]),
        createdAt: z.date(),
        resolvedAt: z.union([z.null(), z.date()]),
        updatedAt: z.date(),
        flightNumber: z.union([z.undefined(), z.string()]).optional(),
        origin: z.union([z.undefined(), z.string()]).optional(),
        destination: z.union([z.undefined(), z.string()]).optional(),
        departureTime: z.union([z.undefined(), z.date()]).optional(),
      })
    ),
    recentActions: z.array(
      z.object({
        id: outputNumber,
        eventId: outputNumber,
        actionType: z.enum([
          "compensation",
          "rebook",
          "hotel",
          "notification",
          "meal_voucher",
        ]),
        targetPassengerId: z.union([z.null(), outputNumber]),
        status: z.enum(["completed", "pending", "failed", "in_progress"]),
        details: z.record(z.string(), structuredValue),
        evidenceType: z.string().nullable(),
        evidenceId: z.string().nullable(),
        createdAt: z.date(),
        completedAt: z.union([z.null(), z.date()]),
      })
    ),
    severityBreakdown: z.object({
      high: outputNumber,
      medium: outputNumber,
      low: outputNumber,
      critical: outputNumber,
    }),
  }),
  getActiveDisruptions: z.array(
    z.object({
      id: outputNumber,
      flightId: outputNumber,
      eventType: z.enum([
        "delay",
        "cancellation",
        "diversion",
        "equipment_change",
      ]),
      severity: z.enum(["high", "medium", "low", "critical"]),
      delayMinutes: z.union([z.null(), outputNumber]),
      reason: z.string(),
      affectedPassengers: outputNumber,
      connectionsAtRisk: outputNumber,
      estimatedRecoveryTime: z.union([z.null(), z.date()]),
      status: z.enum(["active", "resolved", "recovering"]),
      escalationLevel: outputNumber,
      createdBy: z.union([z.null(), outputNumber]),
      createdAt: z.date(),
      resolvedAt: z.union([z.null(), z.date()]),
      updatedAt: z.date(),
      flightNumber: z.union([z.undefined(), z.string()]).optional(),
      origin: z.union([z.undefined(), z.string()]).optional(),
      destination: z.union([z.undefined(), z.string()]).optional(),
      departureTime: z.union([z.undefined(), z.date()]).optional(),
    })
  ),
  createEvent: z.object({
    id: outputNumber,
    flightId: outputNumber,
    eventType: z.enum([
      "delay",
      "cancellation",
      "diversion",
      "equipment_change",
    ]),
    severity: z.enum(["high", "medium", "low", "critical"]),
    delayMinutes: z.union([z.null(), outputNumber]),
    reason: z.string(),
    affectedPassengers: outputNumber,
    connectionsAtRisk: outputNumber,
    estimatedRecoveryTime: z.union([z.null(), z.date()]),
    status: z.enum(["active", "resolved", "recovering"]),
    escalationLevel: outputNumber,
    createdBy: z.union([z.null(), outputNumber]),
    createdAt: z.date(),
    resolvedAt: z.union([z.null(), z.date()]),
    updatedAt: z.date(),
    flightNumber: z.union([z.undefined(), z.string()]).optional(),
    origin: z.union([z.undefined(), z.string()]).optional(),
    destination: z.union([z.undefined(), z.string()]).optional(),
    departureTime: z.union([z.undefined(), z.date()]).optional(),
  }),
  getEventDetail: z.object({
    event: z.object({
      id: outputNumber,
      flightId: outputNumber,
      eventType: z.enum([
        "delay",
        "cancellation",
        "diversion",
        "equipment_change",
      ]),
      severity: z.enum(["high", "medium", "low", "critical"]),
      delayMinutes: z.union([z.null(), outputNumber]),
      reason: z.string(),
      affectedPassengers: outputNumber,
      connectionsAtRisk: outputNumber,
      estimatedRecoveryTime: z.union([z.null(), z.date()]),
      status: z.enum(["active", "resolved", "recovering"]),
      escalationLevel: outputNumber,
      createdBy: z.union([z.null(), outputNumber]),
      createdAt: z.date(),
      resolvedAt: z.union([z.null(), z.date()]),
      updatedAt: z.date(),
      flightNumber: z.union([z.undefined(), z.string()]).optional(),
      origin: z.union([z.undefined(), z.string()]).optional(),
      destination: z.union([z.undefined(), z.string()]).optional(),
      departureTime: z.union([z.undefined(), z.date()]).optional(),
    }),
    actions: z.array(
      z.object({
        id: outputNumber,
        eventId: outputNumber,
        actionType: z.enum([
          "compensation",
          "rebook",
          "hotel",
          "notification",
          "meal_voucher",
        ]),
        targetPassengerId: z.union([z.null(), outputNumber]),
        status: z.enum(["completed", "pending", "failed", "in_progress"]),
        details: z.record(z.string(), structuredValue),
        evidenceType: z.string().nullable(),
        evidenceId: z.string().nullable(),
        createdAt: z.date(),
        completedAt: z.union([z.null(), z.date()]),
      })
    ),
    impact: z.object({
      totalPassengers: outputNumber,
      connectionsAtRisk: outputNumber,
      estimatedCostSAR: outputNumber,
      bookingsAffected: outputNumber,
      businessClassPassengers: outputNumber,
      economyClassPassengers: outputNumber,
    }),
  }),
  getAffectedPassengers: z.array(
    z.object({
      passengerId: outputNumber,
      firstName: z.string(),
      lastName: z.string(),
      type: z.string(),
      bookingReference: z.string(),
      bookingId: outputNumber,
      cabinClass: z.string(),
      seatNumber: z.union([z.null(), z.string()]),
      ticketNumber: z.union([z.null(), z.string()]),
      hasConnection: z.boolean(),
      connectionFlightNumber: z.union([z.null(), z.string()]),
      contactEmail: z.union([z.null(), z.string()]),
    })
  ),
  getConnectionsAtRisk: z.array(
    z.object({
      passengerId: outputNumber,
      passengerName: z.string(),
      bookingReference: z.string(),
      connectionFlightNumber: z.string(),
      connectionDepartureTime: z.date(),
      connectionOrigin: z.string(),
      connectionDestination: z.string(),
      minutesUntilConnection: outputNumber,
      riskLevel: z.enum(["high", "medium", "low", "critical"]),
    })
  ),
  triggerAutoProtection: z.object({
    actionsCreated: outputNumber,
    passengersProtected: outputNumber,
    passengersAffected: outputNumber,
    passengersPlanned: outputNumber,
    actions: z.array(
      z.object({
        id: outputNumber,
        eventId: outputNumber,
        actionType: z.enum([
          "compensation",
          "rebook",
          "hotel",
          "notification",
          "meal_voucher",
        ]),
        targetPassengerId: z.union([z.null(), outputNumber]),
        status: z.enum(["completed", "pending", "failed", "in_progress"]),
        details: z.record(z.string(), structuredValue),
        evidenceType: z.string().nullable(),
        evidenceId: z.string().nullable(),
        createdAt: z.date(),
        completedAt: z.union([z.null(), z.date()]),
      })
    ),
  }),
  sendNotification: z.object({
    notificationsSent: outputNumber,
    failedCount: outputNumber,
  }),
  escalate: z.object({
    id: outputNumber,
    flightId: outputNumber,
    eventType: z.enum([
      "delay",
      "cancellation",
      "diversion",
      "equipment_change",
    ]),
    severity: z.enum(["high", "medium", "low", "critical"]),
    delayMinutes: z.union([z.null(), outputNumber]),
    reason: z.string(),
    affectedPassengers: outputNumber,
    connectionsAtRisk: outputNumber,
    estimatedRecoveryTime: z.union([z.null(), z.date()]),
    status: z.enum(["active", "resolved", "recovering"]),
    escalationLevel: outputNumber,
    createdBy: z.union([z.null(), outputNumber]),
    createdAt: z.date(),
    resolvedAt: z.union([z.null(), z.date()]),
    updatedAt: z.date(),
    flightNumber: z.union([z.undefined(), z.string()]).optional(),
    origin: z.union([z.undefined(), z.string()]).optional(),
    destination: z.union([z.undefined(), z.string()]).optional(),
    departureTime: z.union([z.undefined(), z.date()]).optional(),
  }),
  resolveEvent: z.object({
    id: outputNumber,
    flightId: outputNumber,
    eventType: z.enum([
      "delay",
      "cancellation",
      "diversion",
      "equipment_change",
    ]),
    severity: z.enum(["high", "medium", "low", "critical"]),
    delayMinutes: z.union([z.null(), outputNumber]),
    reason: z.string(),
    affectedPassengers: outputNumber,
    connectionsAtRisk: outputNumber,
    estimatedRecoveryTime: z.union([z.null(), z.date()]),
    status: z.enum(["active", "resolved", "recovering"]),
    escalationLevel: outputNumber,
    createdBy: z.union([z.null(), outputNumber]),
    createdAt: z.date(),
    resolvedAt: z.union([z.null(), z.date()]),
    updatedAt: z.date(),
    flightNumber: z.union([z.undefined(), z.string()]).optional(),
    origin: z.union([z.undefined(), z.string()]).optional(),
    destination: z.union([z.undefined(), z.string()]).optional(),
    departureTime: z.union([z.undefined(), z.date()]).optional(),
  }),
  getRecoveryMetrics: z.object({
    totalEvents: outputNumber,
    resolvedEvents: outputNumber,
    avgResolutionMinutes: outputNumber,
    rebookingSuccess: outputNumber,
    compensationIssued: outputNumber,
    passengersRecovered: outputNumber,
    recoveryRatePercent: outputNumber,
  }),
};
