// Explicit response field allowlists. Review contract changes with producers and consumers.
import { z } from "zod";
import { outputNumber } from "./primitives";
export const responseContracts = {
  authenticate: z.object({
    capabilityToken: z.string(),
    sessionId: outputNumber,
    bookingId: outputNumber,
    bookingReference: z.string(),
    pnr: z.string(),
    flightNumber: z.string(),
    departureTime: z.date(),
    cabinClass: z.enum(["economy", "business"]),
    checkedIn: z.boolean(),
    passengers: z.array(
      z.object({
        id: outputNumber,
        firstName: z.string(),
        lastName: z.string(),
        type: z.enum(["adult", "child", "infant"]),
      })
    ),
  }),
  getCheckInData: z.object({
    booking: z.object({
      id: outputNumber,
      bookingReference: z.string(),
      pnr: z.string(),
      status: z.enum(["cancelled", "completed", "pending", "confirmed"]),
      cabinClass: z.enum(["economy", "business"]),
      checkedIn: z.boolean(),
      numberOfPassengers: outputNumber,
    }),
    flight: z.object({
      id: outputNumber,
      flightNumber: z.string(),
      airline: z.object({ name: z.string(), code: z.string() }),
      aircraftType: z.union([z.null(), z.string()]),
      origin: z.object({
        code: z.string(),
        name: z.string(),
        city: z.string(),
      }),
      destination: z.object({
        code: z.string(),
        name: z.string(),
        city: z.string(),
      }),
      departureTime: z.date(),
      arrivalTime: z.date(),
      status: z.enum(["scheduled", "delayed", "cancelled", "completed"]),
    }),
    passengers: z.array(
      z.object({
        id: outputNumber,
        type: z.enum(["adult", "child", "infant"]),
        title: z.union([z.null(), z.string()]),
        firstName: z.string(),
        lastName: z.string(),
        seatNumber: z.union([z.null(), z.string()]),
        ticketNumber: z.union([z.null(), z.string()]),
        passportNumber: z.union([z.null(), z.string()]),
      })
    ),
    seatMap: z.object({
      totalEconomy: outputNumber,
      totalBusiness: outputNumber,
      availableEconomy: outputNumber,
      availableBusiness: outputNumber,
      takenSeats: z.array(z.string()),
    }),
    ancillaries: z.object({
      available: z.array(
        z.object({
          id: outputNumber,
          code: z.string(),
          category: z.enum([
            "baggage",
            "meal",
            "seat",
            "insurance",
            "lounge",
            "priority_boarding",
          ]),
          name: z.string(),
          description: z.union([z.null(), z.string()]),
          price: outputNumber,
          currency: z.string(),
        })
      ),
      purchased: z.array(
        z.object({
          id: outputNumber,
          ancillaryServiceId: outputNumber,
          passengerId: z.union([z.null(), outputNumber]),
          quantity: outputNumber,
          totalPrice: outputNumber,
          status: z.enum(["cancelled", "active", "refunded"]),
          serviceName: z.string(),
          serviceCode: z.string(),
          category: z.enum([
            "baggage",
            "meal",
            "seat",
            "insurance",
            "lounge",
            "priority_boarding",
          ]),
        })
      ),
    }),
  }),
  checkIn: z.object({
    success: z.boolean(),
    bookingId: outputNumber,
    passengerId: outputNumber,
    passengerName: z.string(),
    seatNumber: z.union([z.null(), z.string()]),
    checkedIn: z.boolean(),
    message: z.string(),
  }),
  selectSeat: z.object({
    success: z.boolean(),
    passengerId: outputNumber,
    passengerName: z.string(),
    previousSeat: z.union([z.null(), z.string()]),
    newSeat: z.string(),
  }),
  printBoardingPass: z.object({
    boardingPass: z.object({
      passengerName: z.string(),
      ticketNumber: z.union([z.null(), z.string()]),
      bookingReference: z.string(),
      pnr: z.string(),
      flight: z.object({
        number: z.string(),
        airline: z.string(),
        airlineCode: z.string(),
        date: z.string(),
        departureTime: z.date(),
        arrivalTime: z.date(),
        aircraftType: z.union([z.null(), z.string()]),
      }),
      origin: z.object({
        code: z.string(),
        name: z.string(),
        city: z.string(),
      }),
      destination: z.object({
        code: z.string(),
        name: z.string(),
        city: z.string(),
      }),
      seat: z.string(),
      cabinClass: z.enum(["economy", "business"]),
      boardingTime: z.string(),
      sequence: z.string(),
      gate: z.string().nullable(),
      barcodeData: z.string(),
      printedAt: z.string(),
    }),
  }),
  printBagTag: z.object({
    bagTags: z.array(
      z.object({
        tagNumber: z.string(),
        passengerName: z.string(),
        flightNumber: z.string(),
        origin: z.string(),
        destination: z.string(),
        bookingReference: z.string(),
        sequence: z.string(),
        barcodeData: z.string(),
        printedAt: z.string(),
      })
    ),
    totalBags: outputNumber,
    passengerName: z.string(),
  }),
  addAncillary: z.object({
    success: z.boolean(),
    ancillaryId: outputNumber,
    serviceName: z.string(),
    serviceCode: z.string(),
    category: z.enum([
      "baggage",
      "meal",
      "seat",
      "insurance",
      "lounge",
      "priority_boarding",
    ]),
    price: outputNumber,
    currency: z.string(),
    passengerName: z.string(),
  }),
  getDevices: z.array(
    z.object({
      id: outputNumber,
      kioskCode: z.string(),
      airportId: outputNumber,
      terminal: z.string(),
      location: z.string(),
      status: z.enum(["maintenance", "online", "offline"]),
      hardwareType: z.union([z.null(), z.string()]),
      hasPrinter: z.boolean(),
      hasScanner: z.boolean(),
      hasPayment: z.boolean(),
      lastHeartbeat: z.union([z.null(), z.date()]),
      installedAt: z.union([z.null(), z.date()]),
      airportCode: z.string(),
      airportName: z.string(),
    })
  ),
  registerDevice: z.object({
    id: outputNumber,
    kioskCode: z.string(),
    airportId: outputNumber,
    terminal: z.string(),
    location: z.string(),
    status: z.literal("offline"),
  }),
  getAnalytics: z.union([
    z.object({
      airportId: outputNumber,
      dateRange: z.object({ from: z.date(), to: z.date() }),
      kiosks: z.array(z.never()),
      totals: z.object({
        totalSessions: outputNumber,
        completedSessions: outputNumber,
        abandonedSessions: outputNumber,
        errorSessions: outputNumber,
        avgCompletionRate: outputNumber,
        boardingPassesPrinted: outputNumber,
        bagTagsPrinted: outputNumber,
      }),
    }),
    z.object({
      airportId: outputNumber,
      dateRange: z.object({ from: z.string(), to: z.string() }),
      kiosks: z.array(
        z.object({
          kioskId: outputNumber,
          kioskCode: z.string(),
          terminal: z.string(),
          location: z.string(),
          status: z.enum(["maintenance", "online", "offline"]),
          totalSessions: outputNumber,
          completedSessions: outputNumber,
          abandonedSessions: outputNumber,
          errorSessions: outputNumber,
          completionRate: outputNumber,
          checkInSessions: outputNumber,
          bagTagSessions: outputNumber,
          ancillarySessions: outputNumber,
          avgSessionDurationSec: outputNumber,
        })
      ),
      totals: z.object({
        totalSessions: outputNumber,
        completedSessions: outputNumber,
        abandonedSessions: outputNumber,
        errorSessions: outputNumber,
        avgCompletionRate: outputNumber,
        boardingPassesPrinted: outputNumber,
        bagTagsPrinted: outputNumber,
      }),
    }),
  ]),
  getDeviceStatus: z.object({
    device: z.object({
      id: outputNumber,
      kioskCode: z.string(),
      airportId: outputNumber,
      terminal: z.string(),
      location: z.string(),
      status: z.enum(["maintenance", "online", "offline"]),
      hardwareType: z.union([z.null(), z.string()]),
      hasPrinter: z.boolean(),
      hasScanner: z.boolean(),
      hasPayment: z.boolean(),
      lastHeartbeat: z.union([z.null(), z.date()]),
      installedAt: z.union([z.null(), z.date()]),
      isResponsive: z.boolean(),
    }),
    todayStats: z.object({
      totalSessions: outputNumber,
      completedSessions: outputNumber,
      abandonedSessions: outputNumber,
      errorSessions: outputNumber,
    }),
  }),
};
