// Explicit response field allowlists. Review contract changes with producers and consumers.
import { z } from "zod";
import { outputNumber } from "./primitives";
export const responseContracts = {
  create: z.object({
    id: outputNumber,
    flightId: outputNumber,
    aircraftTypeId: outputNumber,
    status: z.enum(["draft", "finalized", "validated", "optimized", "amended"]),
    totalPayload: outputNumber,
    totalBaggage: outputNumber,
    totalCargo: outputNumber,
    totalMail: outputNumber,
    deadload: outputNumber,
    items: z.array(
      z.object({
        id: outputNumber,
        loadPlanId: outputNumber,
        compartmentId: z.union([z.null(), outputNumber]),
        itemType: z.enum(["baggage", "cargo", "mail", "ballast"]),
        description: z.string(),
        pieces: outputNumber,
        weight: outputNumber,
        volume: outputNumber,
        uldNumber: z.union([z.null(), z.string()]),
        status: z.enum(["loaded", "planned", "offloaded"]),
        createdAt: z.string(),
      })
    ),
    compartments: z.array(
      z.object({
        compartment: z.object({
          id: outputNumber,
          aircraftTypeId: outputNumber,
          compartmentCode: z.string(),
          name: z.string(),
          position: z.enum(["forward", "aft", "bulk"]),
          maxWeight: outputNumber,
          maxVolume: outputNumber,
          uldCompatible: z.boolean(),
          createdAt: z.string(),
        }),
        items: z.array(
          z.object({
            id: outputNumber,
            loadPlanId: outputNumber,
            compartmentId: z.union([z.null(), outputNumber]),
            itemType: z.enum(["baggage", "cargo", "mail", "ballast"]),
            description: z.string(),
            pieces: outputNumber,
            weight: outputNumber,
            volume: outputNumber,
            uldNumber: z.union([z.null(), z.string()]),
            status: z.enum(["loaded", "planned", "offloaded"]),
            createdAt: z.string(),
          })
        ),
        totalWeight: outputNumber,
        totalVolume: outputNumber,
        fillPercentWeight: outputNumber,
        fillPercentVolume: outputNumber,
      })
    ),
    lastAmendedAt: z.union([z.null(), z.string()]),
    finalizedAt: z.union([z.null(), z.string()]),
    finalizedBy: z.union([z.null(), outputNumber]),
    createdAt: z.string(),
    updatedAt: z.string(),
  }),
  get: z.union([
    z.null(),
    z.object({
      id: outputNumber,
      flightId: outputNumber,
      aircraftTypeId: outputNumber,
      status: z.enum([
        "draft",
        "finalized",
        "validated",
        "optimized",
        "amended",
      ]),
      totalPayload: outputNumber,
      totalBaggage: outputNumber,
      totalCargo: outputNumber,
      totalMail: outputNumber,
      deadload: outputNumber,
      items: z.array(
        z.object({
          id: outputNumber,
          loadPlanId: outputNumber,
          compartmentId: z.union([z.null(), outputNumber]),
          itemType: z.enum(["baggage", "cargo", "mail", "ballast"]),
          description: z.string(),
          pieces: outputNumber,
          weight: outputNumber,
          volume: outputNumber,
          uldNumber: z.union([z.null(), z.string()]),
          status: z.enum(["loaded", "planned", "offloaded"]),
          createdAt: z.string(),
        })
      ),
      compartments: z.array(
        z.object({
          compartment: z.object({
            id: outputNumber,
            aircraftTypeId: outputNumber,
            compartmentCode: z.string(),
            name: z.string(),
            position: z.enum(["forward", "aft", "bulk"]),
            maxWeight: outputNumber,
            maxVolume: outputNumber,
            uldCompatible: z.boolean(),
            createdAt: z.string(),
          }),
          items: z.array(
            z.object({
              id: outputNumber,
              loadPlanId: outputNumber,
              compartmentId: z.union([z.null(), outputNumber]),
              itemType: z.enum(["baggage", "cargo", "mail", "ballast"]),
              description: z.string(),
              pieces: outputNumber,
              weight: outputNumber,
              volume: outputNumber,
              uldNumber: z.union([z.null(), z.string()]),
              status: z.enum(["loaded", "planned", "offloaded"]),
              createdAt: z.string(),
            })
          ),
          totalWeight: outputNumber,
          totalVolume: outputNumber,
          fillPercentWeight: outputNumber,
          fillPercentVolume: outputNumber,
        })
      ),
      lastAmendedAt: z.union([z.null(), z.string()]),
      finalizedAt: z.union([z.null(), z.string()]),
      finalizedBy: z.union([z.null(), outputNumber]),
      createdAt: z.string(),
      updatedAt: z.string(),
    }),
  ]),
  assignCompartment: z.object({
    id: outputNumber,
    flightId: outputNumber,
    aircraftTypeId: outputNumber,
    status: z.enum(["draft", "finalized", "validated", "optimized", "amended"]),
    totalPayload: outputNumber,
    totalBaggage: outputNumber,
    totalCargo: outputNumber,
    totalMail: outputNumber,
    deadload: outputNumber,
    items: z.array(
      z.object({
        id: outputNumber,
        loadPlanId: outputNumber,
        compartmentId: z.union([z.null(), outputNumber]),
        itemType: z.enum(["baggage", "cargo", "mail", "ballast"]),
        description: z.string(),
        pieces: outputNumber,
        weight: outputNumber,
        volume: outputNumber,
        uldNumber: z.union([z.null(), z.string()]),
        status: z.enum(["loaded", "planned", "offloaded"]),
        createdAt: z.string(),
      })
    ),
    compartments: z.array(
      z.object({
        compartment: z.object({
          id: outputNumber,
          aircraftTypeId: outputNumber,
          compartmentCode: z.string(),
          name: z.string(),
          position: z.enum(["forward", "aft", "bulk"]),
          maxWeight: outputNumber,
          maxVolume: outputNumber,
          uldCompatible: z.boolean(),
          createdAt: z.string(),
        }),
        items: z.array(
          z.object({
            id: outputNumber,
            loadPlanId: outputNumber,
            compartmentId: z.union([z.null(), outputNumber]),
            itemType: z.enum(["baggage", "cargo", "mail", "ballast"]),
            description: z.string(),
            pieces: outputNumber,
            weight: outputNumber,
            volume: outputNumber,
            uldNumber: z.union([z.null(), z.string()]),
            status: z.enum(["loaded", "planned", "offloaded"]),
            createdAt: z.string(),
          })
        ),
        totalWeight: outputNumber,
        totalVolume: outputNumber,
        fillPercentWeight: outputNumber,
        fillPercentVolume: outputNumber,
      })
    ),
    lastAmendedAt: z.union([z.null(), z.string()]),
    finalizedAt: z.union([z.null(), z.string()]),
    finalizedBy: z.union([z.null(), outputNumber]),
    createdAt: z.string(),
    updatedAt: z.string(),
  }),
  optimize: z.object({
    id: outputNumber,
    flightId: outputNumber,
    aircraftTypeId: outputNumber,
    status: z.enum(["draft", "finalized", "validated", "optimized", "amended"]),
    totalPayload: outputNumber,
    totalBaggage: outputNumber,
    totalCargo: outputNumber,
    totalMail: outputNumber,
    deadload: outputNumber,
    items: z.array(
      z.object({
        id: outputNumber,
        loadPlanId: outputNumber,
        compartmentId: z.union([z.null(), outputNumber]),
        itemType: z.enum(["baggage", "cargo", "mail", "ballast"]),
        description: z.string(),
        pieces: outputNumber,
        weight: outputNumber,
        volume: outputNumber,
        uldNumber: z.union([z.null(), z.string()]),
        status: z.enum(["loaded", "planned", "offloaded"]),
        createdAt: z.string(),
      })
    ),
    compartments: z.array(
      z.object({
        compartment: z.object({
          id: outputNumber,
          aircraftTypeId: outputNumber,
          compartmentCode: z.string(),
          name: z.string(),
          position: z.enum(["forward", "aft", "bulk"]),
          maxWeight: outputNumber,
          maxVolume: outputNumber,
          uldCompatible: z.boolean(),
          createdAt: z.string(),
        }),
        items: z.array(
          z.object({
            id: outputNumber,
            loadPlanId: outputNumber,
            compartmentId: z.union([z.null(), outputNumber]),
            itemType: z.enum(["baggage", "cargo", "mail", "ballast"]),
            description: z.string(),
            pieces: outputNumber,
            weight: outputNumber,
            volume: outputNumber,
            uldNumber: z.union([z.null(), z.string()]),
            status: z.enum(["loaded", "planned", "offloaded"]),
            createdAt: z.string(),
          })
        ),
        totalWeight: outputNumber,
        totalVolume: outputNumber,
        fillPercentWeight: outputNumber,
        fillPercentVolume: outputNumber,
      })
    ),
    lastAmendedAt: z.union([z.null(), z.string()]),
    finalizedAt: z.union([z.null(), z.string()]),
    finalizedBy: z.union([z.null(), outputNumber]),
    createdAt: z.string(),
    updatedAt: z.string(),
  }),
  validate: z.union([
    z.object({
      valid: z.boolean(),
      warnings: z.array(z.string()),
      errors: z.array(z.string()),
      summary: z.undefined().optional(),
    }),
    z.object({
      valid: z.boolean(),
      warnings: z.array(z.string()),
      errors: z.array(z.string()),
      summary: z.object({
        totalItems: outputNumber,
        assignedItems: outputNumber,
        totalWeightKg: outputNumber,
        forwardWeightKg: outputNumber,
        aftWeightKg: outputNumber,
        bulkWeightKg: outputNumber,
        compartmentFill: z.array(
          z.object({
            code: z.string(),
            name: z.string(),
            position: z.enum(["forward", "aft", "bulk"]),
            weightPercent: outputNumber,
            volumePercent: outputNumber,
          })
        ),
      }),
    }),
  ]),
  updateBulk: z.object({
    id: outputNumber,
    flightId: outputNumber,
    aircraftTypeId: outputNumber,
    status: z.enum(["draft", "finalized", "validated", "optimized", "amended"]),
    totalPayload: outputNumber,
    totalBaggage: outputNumber,
    totalCargo: outputNumber,
    totalMail: outputNumber,
    deadload: outputNumber,
    items: z.array(
      z.object({
        id: outputNumber,
        loadPlanId: outputNumber,
        compartmentId: z.union([z.null(), outputNumber]),
        itemType: z.enum(["baggage", "cargo", "mail", "ballast"]),
        description: z.string(),
        pieces: outputNumber,
        weight: outputNumber,
        volume: outputNumber,
        uldNumber: z.union([z.null(), z.string()]),
        status: z.enum(["loaded", "planned", "offloaded"]),
        createdAt: z.string(),
      })
    ),
    compartments: z.array(
      z.object({
        compartment: z.object({
          id: outputNumber,
          aircraftTypeId: outputNumber,
          compartmentCode: z.string(),
          name: z.string(),
          position: z.enum(["forward", "aft", "bulk"]),
          maxWeight: outputNumber,
          maxVolume: outputNumber,
          uldCompatible: z.boolean(),
          createdAt: z.string(),
        }),
        items: z.array(
          z.object({
            id: outputNumber,
            loadPlanId: outputNumber,
            compartmentId: z.union([z.null(), outputNumber]),
            itemType: z.enum(["baggage", "cargo", "mail", "ballast"]),
            description: z.string(),
            pieces: outputNumber,
            weight: outputNumber,
            volume: outputNumber,
            uldNumber: z.union([z.null(), z.string()]),
            status: z.enum(["loaded", "planned", "offloaded"]),
            createdAt: z.string(),
          })
        ),
        totalWeight: outputNumber,
        totalVolume: outputNumber,
        fillPercentWeight: outputNumber,
        fillPercentVolume: outputNumber,
      })
    ),
    lastAmendedAt: z.union([z.null(), z.string()]),
    finalizedAt: z.union([z.null(), z.string()]),
    finalizedBy: z.union([z.null(), outputNumber]),
    createdAt: z.string(),
    updatedAt: z.string(),
  }),
  getCompartments: z.object({
    aircraftType: z.object({
      id: outputNumber,
      code: z.string(),
      name: z.string(),
      manufacturer: z.string(),
      totalSeats: outputNumber,
      isWidebody: z.boolean(),
    }),
    compartments: z.array(
      z.object({
        id: outputNumber,
        aircraftTypeId: outputNumber,
        compartmentCode: z.string(),
        name: z.string(),
        position: z.enum(["forward", "aft", "bulk"]),
        maxWeight: outputNumber,
        maxVolume: outputNumber,
        uldCompatible: z.boolean(),
        createdAt: z.string(),
      })
    ),
    totalMaxWeight: outputNumber,
    totalMaxVolume: outputNumber,
  }),
  finalize: z.object({
    success: z.boolean(),
    plan: z.object({
      id: outputNumber,
      flightId: outputNumber,
      aircraftTypeId: outputNumber,
      status: z.enum([
        "draft",
        "finalized",
        "validated",
        "optimized",
        "amended",
      ]),
      totalPayload: outputNumber,
      totalBaggage: outputNumber,
      totalCargo: outputNumber,
      totalMail: outputNumber,
      deadload: outputNumber,
      items: z.array(
        z.object({
          id: outputNumber,
          loadPlanId: outputNumber,
          compartmentId: z.union([z.null(), outputNumber]),
          itemType: z.enum(["baggage", "cargo", "mail", "ballast"]),
          description: z.string(),
          pieces: outputNumber,
          weight: outputNumber,
          volume: outputNumber,
          uldNumber: z.union([z.null(), z.string()]),
          status: z.enum(["loaded", "planned", "offloaded"]),
          createdAt: z.string(),
        })
      ),
      compartments: z.array(
        z.object({
          compartment: z.object({
            id: outputNumber,
            aircraftTypeId: outputNumber,
            compartmentCode: z.string(),
            name: z.string(),
            position: z.enum(["forward", "aft", "bulk"]),
            maxWeight: outputNumber,
            maxVolume: outputNumber,
            uldCompatible: z.boolean(),
            createdAt: z.string(),
          }),
          items: z.array(
            z.object({
              id: outputNumber,
              loadPlanId: outputNumber,
              compartmentId: z.union([z.null(), outputNumber]),
              itemType: z.enum(["baggage", "cargo", "mail", "ballast"]),
              description: z.string(),
              pieces: outputNumber,
              weight: outputNumber,
              volume: outputNumber,
              uldNumber: z.union([z.null(), z.string()]),
              status: z.enum(["loaded", "planned", "offloaded"]),
              createdAt: z.string(),
            })
          ),
          totalWeight: outputNumber,
          totalVolume: outputNumber,
          fillPercentWeight: outputNumber,
          fillPercentVolume: outputNumber,
        })
      ),
      lastAmendedAt: z.union([z.null(), z.string()]),
      finalizedAt: z.union([z.null(), z.string()]),
      finalizedBy: z.union([z.null(), outputNumber]),
      createdAt: z.string(),
      updatedAt: z.string(),
    }),
  }),
  amend: z.object({
    plan: z.object({
      id: outputNumber,
      flightId: outputNumber,
      aircraftTypeId: outputNumber,
      status: z.enum([
        "draft",
        "finalized",
        "validated",
        "optimized",
        "amended",
      ]),
      totalPayload: outputNumber,
      totalBaggage: outputNumber,
      totalCargo: outputNumber,
      totalMail: outputNumber,
      deadload: outputNumber,
      items: z.array(
        z.object({
          id: outputNumber,
          loadPlanId: outputNumber,
          compartmentId: z.union([z.null(), outputNumber]),
          itemType: z.enum(["baggage", "cargo", "mail", "ballast"]),
          description: z.string(),
          pieces: outputNumber,
          weight: outputNumber,
          volume: outputNumber,
          uldNumber: z.union([z.null(), z.string()]),
          status: z.enum(["loaded", "planned", "offloaded"]),
          createdAt: z.string(),
        })
      ),
      compartments: z.array(
        z.object({
          compartment: z.object({
            id: outputNumber,
            aircraftTypeId: outputNumber,
            compartmentCode: z.string(),
            name: z.string(),
            position: z.enum(["forward", "aft", "bulk"]),
            maxWeight: outputNumber,
            maxVolume: outputNumber,
            uldCompatible: z.boolean(),
            createdAt: z.string(),
          }),
          items: z.array(
            z.object({
              id: outputNumber,
              loadPlanId: outputNumber,
              compartmentId: z.union([z.null(), outputNumber]),
              itemType: z.enum(["baggage", "cargo", "mail", "ballast"]),
              description: z.string(),
              pieces: outputNumber,
              weight: outputNumber,
              volume: outputNumber,
              uldNumber: z.union([z.null(), z.string()]),
              status: z.enum(["loaded", "planned", "offloaded"]),
              createdAt: z.string(),
            })
          ),
          totalWeight: outputNumber,
          totalVolume: outputNumber,
          fillPercentWeight: outputNumber,
          fillPercentVolume: outputNumber,
        })
      ),
      lastAmendedAt: z.union([z.null(), z.string()]),
      finalizedAt: z.union([z.null(), z.string()]),
      finalizedBy: z.union([z.null(), outputNumber]),
      createdAt: z.string(),
      updatedAt: z.string(),
    }),
    amendments: z.array(z.string()),
  }),
};
