// Explicit response field allowlists. Review contract changes with producers and consumers.
import { z } from "zod";
import { outputNumber } from "./primitives";
export const responseContracts = {
  requestChangeDate: z.object({
    modificationId: outputNumber,
    originalAmount: outputNumber,
    newAmount: outputNumber,
    priceDifference: outputNumber,
    modificationFee: outputNumber,
    totalCost: outputNumber,
    requiresPayment: z.boolean(),
  }),
  requestUpgrade: z.object({
    modificationId: outputNumber,
    originalAmount: outputNumber,
    newAmount: outputNumber,
    priceDifference: outputNumber,
    modificationFee: outputNumber,
    totalCost: outputNumber,
    requiresPayment: z.boolean(),
  }),
  getDetails: z.object({
    id: outputNumber,
    bookingId: outputNumber,
    userId: outputNumber,
    modificationType: z.enum([
      "change_date",
      "upgrade_cabin",
      "change_flight",
      "add_services",
    ]),
    originalFlightId: z.union([z.null(), outputNumber]),
    originalCabinClass: z.union([
      z.null(),
      z.literal("economy"),
      z.literal("business"),
    ]),
    originalAmount: outputNumber,
    newFlightId: z.union([z.null(), outputNumber]),
    newCabinClass: z.union([
      z.null(),
      z.literal("economy"),
      z.literal("business"),
    ]),
    newAmount: outputNumber,
    priceDifference: outputNumber,
    modificationFee: outputNumber,
    totalCost: outputNumber,
    status: z.enum(["completed", "pending", "approved", "rejected"]),
    stripePaymentIntentId: z.union([z.null(), z.string()]),
    paymentStatus: z.union([
      z.null(),
      z.literal("pending"),
      z.literal("paid"),
      z.literal("refunded"),
    ]),
    reason: z.union([z.null(), z.string()]),
    adminNotes: z.union([z.null(), z.string()]),
    createdAt: z.date(),
    updatedAt: z.date(),
    completedAt: z.union([z.null(), z.date()]),
  }),
  myModifications: z.array(
    z.object({
      id: outputNumber,
      bookingId: outputNumber,
      userId: outputNumber,
      modificationType: z.enum([
        "change_date",
        "upgrade_cabin",
        "change_flight",
        "add_services",
      ]),
      originalFlightId: z.union([z.null(), outputNumber]),
      originalCabinClass: z.union([
        z.null(),
        z.literal("economy"),
        z.literal("business"),
      ]),
      originalAmount: outputNumber,
      newFlightId: z.union([z.null(), outputNumber]),
      newCabinClass: z.union([
        z.null(),
        z.literal("economy"),
        z.literal("business"),
      ]),
      newAmount: outputNumber,
      priceDifference: outputNumber,
      modificationFee: outputNumber,
      totalCost: outputNumber,
      status: z.enum(["completed", "pending", "approved", "rejected"]),
      stripePaymentIntentId: z.union([z.null(), z.string()]),
      paymentStatus: z.union([
        z.null(),
        z.literal("pending"),
        z.literal("paid"),
        z.literal("refunded"),
      ]),
      reason: z.union([z.null(), z.string()]),
      adminNotes: z.union([z.null(), z.string()]),
      createdAt: z.date(),
      updatedAt: z.date(),
      completedAt: z.union([z.null(), z.date()]),
    })
  ),
};
