// Explicit response field allowlists. Review contract changes with producers and consumers.
import { z } from "zod";
import { outputNumber } from "./primitives";
export const responseContracts = {
  myPayments: z.array(
    z.object({
      id: outputNumber,
      amount: outputNumber,
      currency: z.string(),
      method: z.enum([
        "tabby",
        "tamara",
        "stc_pay",
        "card",
        "wallet",
        "bank_transfer",
        "mada",
        "apple_pay",
      ]),
      status: z.enum(["completed", "pending", "refunded", "failed"]),
      transactionId: z.union([z.null(), z.string()]),
      createdAt: z.date(),
      bookingId: outputNumber,
      bookingReference: z.string(),
      pnr: z.string(),
      cabinClass: z.enum(["economy", "business"]),
      flightNumber: z.string(),
      origin: z.string(),
      destination: z.string(),
      departureTime: z.date(),
    })
  ),
  myStats: z.object({
    totalPayments: outputNumber,
    totalAmount: outputNumber,
    completedCount: outputNumber,
    completedAmount: outputNumber,
    refundedCount: outputNumber,
    refundedAmount: outputNumber,
    pendingCount: outputNumber,
    failedCount: outputNumber,
  }),
  adminHistory: z.array(
    z.object({
      id: outputNumber,
      amount: outputNumber,
      currency: z.string(),
      method: z.enum([
        "tabby",
        "tamara",
        "stc_pay",
        "card",
        "wallet",
        "bank_transfer",
        "mada",
        "apple_pay",
      ]),
      status: z.enum(["completed", "pending", "refunded", "failed"]),
      transactionId: z.union([z.null(), z.string()]),
      createdAt: z.date(),
      bookingId: outputNumber,
      bookingReference: z.string(),
      pnr: z.string(),
      cabinClass: z.enum(["economy", "business"]),
      numberOfPassengers: outputNumber,
      flightNumber: z.string(),
      origin: z.string(),
      destination: z.string(),
      departureTime: z.date(),
    })
  ),
  adminStats: z.object({
    totalPayments: outputNumber,
    totalAmount: outputNumber,
    completedCount: outputNumber,
    completedAmount: outputNumber,
    refundedCount: outputNumber,
    refundedAmount: outputNumber,
    pendingCount: outputNumber,
    failedCount: outputNumber,
    todayPayments: outputNumber,
    todayAmount: outputNumber,
  }),
};
