// Explicit response field allowlists. Review contract changes with producers and consumers.
import { z } from "zod";
import { outputNumber } from "./primitives";
export const responseContracts = {
  create: z.object({
    createdAt: z.date(),
    updatedAt: z.date(),
    flightId: outputNumber,
    userId: outputNumber,
    rating: outputNumber,
    id: outputNumber,
    status: z
      .union([
        z.undefined(),
        z.literal("pending"),
        z.literal("approved"),
        z.literal("rejected"),
        z.literal("hidden"),
      ])
      .optional(),
    bookingId: z.union([z.undefined(), z.null(), outputNumber]).optional(),
    title: z.union([z.undefined(), z.null(), z.string()]).optional(),
    comfortRating: z.union([z.undefined(), z.null(), outputNumber]).optional(),
    serviceRating: z.union([z.undefined(), z.null(), outputNumber]).optional(),
    valueRating: z.union([z.undefined(), z.null(), outputNumber]).optional(),
    comment: z.union([z.undefined(), z.null(), z.string()]).optional(),
    helpfulCount: z.union([z.undefined(), outputNumber]).optional(),
    isVerified: z
      .union([z.undefined(), z.literal(false), z.literal(true)])
      .optional(),
  }),
  getFlightReviews: z.array(
    z.object({
      id: outputNumber,
      userId: outputNumber,
      flightId: outputNumber,
      bookingId: z.union([z.null(), outputNumber]),
      rating: outputNumber,
      comfortRating: z.union([z.null(), outputNumber]),
      serviceRating: z.union([z.null(), outputNumber]),
      valueRating: z.union([z.null(), outputNumber]),
      title: z.union([z.null(), z.string()]),
      comment: z.union([z.null(), z.string()]),
      helpfulCount: outputNumber,
      isVerified: z.boolean(),
      status: z.enum(["pending", "approved", "rejected", "hidden"]),
      createdAt: z.date(),
      updatedAt: z.date(),
    })
  ),
  getFlightStats: z.object({
    totalReviews: outputNumber,
    averageRating: outputNumber,
    averageComfort: outputNumber,
    averageService: outputNumber,
    averageValue: outputNumber,
    ratingDistribution: z.record(z.string(), outputNumber),
  }),
  update: z.object({ success: z.boolean() }),
  delete: z.object({ success: z.boolean() }),
  getUserReviews: z.array(
    z.object({
      review: z.object({
        id: outputNumber,
        userId: outputNumber,
        flightId: outputNumber,
        bookingId: z.union([z.null(), outputNumber]),
        rating: outputNumber,
        comfortRating: z.union([z.null(), outputNumber]),
        serviceRating: z.union([z.null(), outputNumber]),
        valueRating: z.union([z.null(), outputNumber]),
        title: z.union([z.null(), z.string()]),
        comment: z.union([z.null(), z.string()]),
        helpfulCount: outputNumber,
        isVerified: z.boolean(),
        status: z.enum(["pending", "approved", "rejected", "hidden"]),
        createdAt: z.date(),
        updatedAt: z.date(),
      }),
      flight: z.object({
        id: outputNumber,
        flightNumber: z.string(),
        airlineId: outputNumber,
        tenantId: z.union([z.null(), outputNumber]),
        originId: outputNumber,
        destinationId: outputNumber,
        departureTime: z.date(),
        arrivalTime: z.date(),
        aircraftType: z.union([z.null(), z.string()]),
        status: z.enum(["scheduled", "delayed", "cancelled", "completed"]),
        economySeats: outputNumber,
        businessSeats: outputNumber,
        economyPrice: outputNumber,
        businessPrice: outputNumber,
        economyAvailable: outputNumber,
        businessAvailable: outputNumber,
        createdAt: z.date(),
        updatedAt: z.date(),
      }),
    })
  ),
  markHelpful: z.object({ success: z.boolean() }),
  getAirlineReviews: z.array(
    z.object({
      review: z.object({
        id: outputNumber,
        userId: outputNumber,
        flightId: outputNumber,
        bookingId: z.union([z.null(), outputNumber]),
        rating: outputNumber,
        comfortRating: z.union([z.null(), outputNumber]),
        serviceRating: z.union([z.null(), outputNumber]),
        valueRating: z.union([z.null(), outputNumber]),
        title: z.union([z.null(), z.string()]),
        comment: z.union([z.null(), z.string()]),
        helpfulCount: outputNumber,
        isVerified: z.boolean(),
        status: z.enum(["pending", "approved", "rejected", "hidden"]),
        createdAt: z.date(),
        updatedAt: z.date(),
      }),
      flight: z.object({
        id: outputNumber,
        flightNumber: z.string(),
        airlineId: outputNumber,
        tenantId: z.union([z.null(), outputNumber]),
        originId: outputNumber,
        destinationId: outputNumber,
        departureTime: z.date(),
        arrivalTime: z.date(),
        aircraftType: z.union([z.null(), z.string()]),
        status: z.enum(["scheduled", "delayed", "cancelled", "completed"]),
        economySeats: outputNumber,
        businessSeats: outputNumber,
        economyPrice: outputNumber,
        businessPrice: outputNumber,
        economyAvailable: outputNumber,
        businessAvailable: outputNumber,
        createdAt: z.date(),
        updatedAt: z.date(),
      }),
    })
  ),
  getAirlineStats: z.object({
    totalReviews: outputNumber,
    averageRating: outputNumber,
    averageComfort: outputNumber,
    averageService: outputNumber,
    averageValue: outputNumber,
    ratingDistribution: z.record(z.string(), outputNumber),
  }),
  canReview: z.object({
    canReview: z.boolean(),
    bookingId: z.union([z.undefined(), outputNumber]).optional(),
    reason: z.union([z.undefined(), z.string()]).optional(),
  }),
};
