// Explicit response field allowlists. Review contract changes with producers and consumers.
import { z } from "zod";
import { outputNumber } from "./primitives";
export const responseContracts = {
  getAll: z.array(
    z.object({
      id: outputNumber,
      createdAt: z.date(),
      updatedAt: z.date(),
      userId: outputNumber,
      email: z.union([z.null(), z.string()]),
      firstName: z.string(),
      lastName: z.string(),
      dateOfBirth: z.union([z.null(), z.date()]),
      passportNumber: z.union([z.null(), z.string()]),
      passportExpiry: z.union([z.null(), z.date()]),
      nationality: z.union([z.null(), z.string()]),
      phone: z.union([z.null(), z.string()]),
      isDefault: z.boolean(),
    })
  ),
  getById: z.union([
    z.null(),
    z.object({
      id: outputNumber,
      createdAt: z.date(),
      updatedAt: z.date(),
      userId: outputNumber,
      email: z.union([z.null(), z.string()]),
      firstName: z.string(),
      lastName: z.string(),
      dateOfBirth: z.union([z.null(), z.date()]),
      passportNumber: z.union([z.null(), z.string()]),
      passportExpiry: z.union([z.null(), z.date()]),
      nationality: z.union([z.null(), z.string()]),
      phone: z.union([z.null(), z.string()]),
      isDefault: z.boolean(),
    }),
  ]),
  getDefault: z.union([
    z.null(),
    z.object({
      id: outputNumber,
      createdAt: z.date(),
      updatedAt: z.date(),
      userId: outputNumber,
      email: z.union([z.null(), z.string()]),
      firstName: z.string(),
      lastName: z.string(),
      dateOfBirth: z.union([z.null(), z.date()]),
      passportNumber: z.union([z.null(), z.string()]),
      passportExpiry: z.union([z.null(), z.date()]),
      nationality: z.union([z.null(), z.string()]),
      phone: z.union([z.null(), z.string()]),
      isDefault: z.boolean(),
    }),
  ]),
  add: z.object({
    id: outputNumber,
    createdAt: z.date(),
    updatedAt: z.date(),
    userId: outputNumber,
    email: z.union([z.null(), z.string()]),
    firstName: z.string(),
    lastName: z.string(),
    dateOfBirth: z.union([z.null(), z.date()]),
    passportNumber: z.union([z.null(), z.string()]),
    passportExpiry: z.union([z.null(), z.date()]),
    nationality: z.union([z.null(), z.string()]),
    phone: z.union([z.null(), z.string()]),
    isDefault: z.boolean(),
  }),
  update: z.object({
    id: outputNumber,
    createdAt: z.date(),
    updatedAt: z.date(),
    userId: outputNumber,
    email: z.union([z.null(), z.string()]),
    firstName: z.string(),
    lastName: z.string(),
    dateOfBirth: z.union([z.null(), z.date()]),
    passportNumber: z.union([z.null(), z.string()]),
    passportExpiry: z.union([z.null(), z.date()]),
    nationality: z.union([z.null(), z.string()]),
    phone: z.union([z.null(), z.string()]),
    isDefault: z.boolean(),
  }),
  delete: z.object({ success: z.boolean() }),
  setDefault: z.object({
    id: outputNumber,
    createdAt: z.date(),
    updatedAt: z.date(),
    userId: outputNumber,
    email: z.union([z.null(), z.string()]),
    firstName: z.string(),
    lastName: z.string(),
    dateOfBirth: z.union([z.null(), z.date()]),
    passportNumber: z.union([z.null(), z.string()]),
    passportExpiry: z.union([z.null(), z.date()]),
    nationality: z.union([z.null(), z.string()]),
    phone: z.union([z.null(), z.string()]),
    isDefault: z.boolean(),
  }),
};
