// Explicit response field allowlists. Review contract changes with producers and consumers.
import { z } from "zod";
import { outputNumber } from "./primitives";
export const responseContracts = {
  createSeatMap: z.object({
    id: outputNumber,
    airlineId: outputNumber,
    aircraftType: z.string(),
    economySeats: outputNumber,
    businessSeats: outputNumber,
    createdAt: z.date(),
    updatedAt: z.date(),
    active: z.boolean(),
    totalSeats: outputNumber,
    cabinLayout: z.string(),
    configName: z.string(),
    firstClassSeats: outputNumber,
    premiumEconomySeats: outputNumber,
    seatPitch: z.union([z.null(), z.string()]),
    seatWidth: z.union([z.null(), z.string()]),
    hasWifi: z.boolean(),
    hasPowerOutlets: z.boolean(),
    hasIFE: z.boolean(),
  }),
  updateSeatMap: z.object({
    id: outputNumber,
    airlineId: outputNumber,
    aircraftType: z.string(),
    economySeats: outputNumber,
    businessSeats: outputNumber,
    createdAt: z.date(),
    updatedAt: z.date(),
    active: z.boolean(),
    totalSeats: outputNumber,
    cabinLayout: z.string(),
    configName: z.string(),
    firstClassSeats: outputNumber,
    premiumEconomySeats: outputNumber,
    seatPitch: z.union([z.null(), z.string()]),
    seatWidth: z.union([z.null(), z.string()]),
    hasWifi: z.boolean(),
    hasPowerOutlets: z.boolean(),
    hasIFE: z.boolean(),
  }),
  getSeatMap: z.object({
    cabinLayout: z.object({
      rows: z.array(
        z.object({
          row: outputNumber,
          cabinClass: z.enum([
            "economy",
            "business",
            "first",
            "premium_economy",
          ]),
          seats: z.array(
            z.object({
              column: z.string(),
              seatType: z.enum([
                "window",
                "aisle",
                "middle",
                "bulkhead_window",
                "bulkhead_middle",
                "bulkhead_aisle",
                "exit_row_window",
                "exit_row_middle",
                "exit_row_aisle",
              ]),
              hasExtraLegroom: z
                .union([z.undefined(), z.literal(false), z.literal(true)])
                .optional(),
              hasPowerOutlet: z
                .union([z.undefined(), z.literal(false), z.literal(true)])
                .optional(),
              isReclinable: z
                .union([z.undefined(), z.literal(false), z.literal(true)])
                .optional(),
              nearLavatory: z
                .union([z.undefined(), z.literal(false), z.literal(true)])
                .optional(),
              nearGalley: z
                .union([z.undefined(), z.literal(false), z.literal(true)])
                .optional(),
              priceTier: z
                .union([
                  z.undefined(),
                  z.literal("standard"),
                  z.literal("extra_legroom"),
                  z.literal("premium"),
                  z.literal("free"),
                  z.literal("preferred"),
                ])
                .optional(),
              seatPrice: z.union([z.undefined(), outputNumber]).optional(),
              blocked: z
                .union([z.undefined(), z.literal(false), z.literal(true)])
                .optional(),
            })
          ),
        })
      ),
    }),
    seatPitch: z.record(z.string(), outputNumber),
    seatWidth: z.record(z.string(), outputNumber),
    id: outputNumber,
    aircraftType: z.string(),
    airlineId: outputNumber,
    configName: z.string(),
    totalSeats: outputNumber,
    firstClassSeats: outputNumber,
    businessSeats: outputNumber,
    premiumEconomySeats: outputNumber,
    economySeats: outputNumber,
    hasWifi: z.boolean(),
    hasPowerOutlets: z.boolean(),
    hasIFE: z.boolean(),
    active: z.boolean(),
    createdAt: z.date(),
    updatedAt: z.date(),
  }),
  listSeatMaps: z.array(
    z.object({
      cabinLayout: z.object({
        rows: z.array(
          z.object({
            row: outputNumber,
            cabinClass: z.enum([
              "economy",
              "business",
              "first",
              "premium_economy",
            ]),
            seats: z.array(
              z.object({
                column: z.string(),
                seatType: z.enum([
                  "window",
                  "aisle",
                  "middle",
                  "bulkhead_window",
                  "bulkhead_middle",
                  "bulkhead_aisle",
                  "exit_row_window",
                  "exit_row_middle",
                  "exit_row_aisle",
                ]),
                hasExtraLegroom: z
                  .union([z.undefined(), z.literal(false), z.literal(true)])
                  .optional(),
                hasPowerOutlet: z
                  .union([z.undefined(), z.literal(false), z.literal(true)])
                  .optional(),
                isReclinable: z
                  .union([z.undefined(), z.literal(false), z.literal(true)])
                  .optional(),
                nearLavatory: z
                  .union([z.undefined(), z.literal(false), z.literal(true)])
                  .optional(),
                nearGalley: z
                  .union([z.undefined(), z.literal(false), z.literal(true)])
                  .optional(),
                priceTier: z
                  .union([
                    z.undefined(),
                    z.literal("standard"),
                    z.literal("extra_legroom"),
                    z.literal("premium"),
                    z.literal("free"),
                    z.literal("preferred"),
                  ])
                  .optional(),
                seatPrice: z.union([z.undefined(), outputNumber]).optional(),
                blocked: z
                  .union([z.undefined(), z.literal(false), z.literal(true)])
                  .optional(),
              })
            ),
          })
        ),
      }),
      seatPitch: z.record(z.string(), outputNumber),
      seatWidth: z.record(z.string(), outputNumber),
      id: outputNumber,
      aircraftType: z.string(),
      airlineId: outputNumber,
      configName: z.string(),
      totalSeats: outputNumber,
      firstClassSeats: outputNumber,
      businessSeats: outputNumber,
      premiumEconomySeats: outputNumber,
      economySeats: outputNumber,
      hasWifi: z.boolean(),
      hasPowerOutlets: z.boolean(),
      hasIFE: z.boolean(),
      active: z.boolean(),
      createdAt: z.date(),
      updatedAt: z.date(),
    })
  ),
  initializeFlightSeats: z.object({ seatsCreated: outputNumber }),
  getFlightSeatMap: z.object({
    flightId: outputNumber,
    seatMapId: outputNumber,
    aircraftType: z.string(),
    configName: z.string(),
    features: z.object({
      hasWifi: z.boolean(),
      hasPowerOutlets: z.boolean(),
      hasIFE: z.boolean(),
    }),
    cabins: z.array(
      z.object({
        cabinClass: z.string(),
        rows: z.array(
          z.object({
            row: outputNumber,
            seats: z.array(
              z.object({
                id: outputNumber,
                seatNumber: z.string(),
                row: outputNumber,
                column: z.string(),
                cabinClass: z.string(),
                seatType: z.string(),
                hasExtraLegroom: z.boolean(),
                hasPowerOutlet: z.boolean(),
                isReclinable: z.boolean(),
                nearLavatory: z.boolean(),
                nearGalley: z.boolean(),
                seatPrice: outputNumber,
                priceTier: z.string(),
                status: z.string(),
                isAssigned: z.boolean(),
              })
            ),
          })
        ),
      })
    ),
    summary: z.object({
      totalSeats: outputNumber,
      available: outputNumber,
      occupied: outputNumber,
      blocked: outputNumber,
      checkedIn: outputNumber,
    }),
  }),
  selectSeat: z.object({
    id: outputNumber,
    status: z.enum([
      "available",
      "checked_in",
      "occupied",
      "blocked",
      "held",
      "restricted",
    ]),
    createdAt: z.date(),
    updatedAt: z.date(),
    flightId: outputNumber,
    bookingId: z.union([z.null(), outputNumber]),
    cabinClass: z.enum(["economy", "business", "first", "premium_economy"]),
    passengerId: z.union([z.null(), outputNumber]),
    seatNumber: z.string(),
    assignedAt: z.union([z.null(), z.date()]),
    row: outputNumber,
    seatType: z.enum([
      "window",
      "aisle",
      "middle",
      "bulkhead_window",
      "bulkhead_middle",
      "bulkhead_aisle",
      "exit_row_window",
      "exit_row_middle",
      "exit_row_aisle",
    ]),
    column: z.string(),
    hasExtraLegroom: z.boolean(),
    hasPowerOutlet: z.boolean(),
    isReclinable: z.boolean(),
    nearLavatory: z.boolean(),
    nearGalley: z.boolean(),
    priceTier: z.enum([
      "standard",
      "extra_legroom",
      "premium",
      "free",
      "preferred",
    ]),
    seatPrice: outputNumber,
    seatMapId: outputNumber,
    checkedInAt: z.union([z.null(), z.date()]),
    boardingPassIssued: z.boolean(),
    boardingGroup: z.union([z.null(), z.string()]),
    boardingSequence: z.union([z.null(), outputNumber]),
  }),
  releaseSeat: z.object({ success: z.literal(true), seatNumber: z.string() }),
  changeSeat: z.object({
    id: outputNumber,
    status: z.enum([
      "available",
      "checked_in",
      "occupied",
      "blocked",
      "held",
      "restricted",
    ]),
    createdAt: z.date(),
    updatedAt: z.date(),
    flightId: outputNumber,
    bookingId: z.union([z.null(), outputNumber]),
    cabinClass: z.enum(["economy", "business", "first", "premium_economy"]),
    passengerId: z.union([z.null(), outputNumber]),
    seatNumber: z.string(),
    assignedAt: z.union([z.null(), z.date()]),
    row: outputNumber,
    seatType: z.enum([
      "window",
      "aisle",
      "middle",
      "bulkhead_window",
      "bulkhead_middle",
      "bulkhead_aisle",
      "exit_row_window",
      "exit_row_middle",
      "exit_row_aisle",
    ]),
    column: z.string(),
    hasExtraLegroom: z.boolean(),
    hasPowerOutlet: z.boolean(),
    isReclinable: z.boolean(),
    nearLavatory: z.boolean(),
    nearGalley: z.boolean(),
    priceTier: z.enum([
      "standard",
      "extra_legroom",
      "premium",
      "free",
      "preferred",
    ]),
    seatPrice: outputNumber,
    seatMapId: outputNumber,
    checkedInAt: z.union([z.null(), z.date()]),
    boardingPassIssued: z.boolean(),
    boardingGroup: z.union([z.null(), z.string()]),
    boardingSequence: z.union([z.null(), outputNumber]),
  }),
  getPassengerSeat: z.union([
    z.null(),
    z.object({
      id: outputNumber,
      status: z.enum([
        "available",
        "checked_in",
        "occupied",
        "blocked",
        "held",
        "restricted",
      ]),
      createdAt: z.date(),
      updatedAt: z.date(),
      flightId: outputNumber,
      bookingId: z.union([z.null(), outputNumber]),
      cabinClass: z.enum(["economy", "business", "first", "premium_economy"]),
      passengerId: z.union([z.null(), outputNumber]),
      seatNumber: z.string(),
      assignedAt: z.union([z.null(), z.date()]),
      row: outputNumber,
      seatType: z.enum([
        "window",
        "aisle",
        "middle",
        "bulkhead_window",
        "bulkhead_middle",
        "bulkhead_aisle",
        "exit_row_window",
        "exit_row_middle",
        "exit_row_aisle",
      ]),
      column: z.string(),
      hasExtraLegroom: z.boolean(),
      hasPowerOutlet: z.boolean(),
      isReclinable: z.boolean(),
      nearLavatory: z.boolean(),
      nearGalley: z.boolean(),
      priceTier: z.enum([
        "standard",
        "extra_legroom",
        "premium",
        "free",
        "preferred",
      ]),
      seatPrice: outputNumber,
      seatMapId: outputNumber,
      checkedInAt: z.union([z.null(), z.date()]),
      boardingPassIssued: z.boolean(),
      boardingGroup: z.union([z.null(), z.string()]),
      boardingSequence: z.union([z.null(), outputNumber]),
    }),
  ]),
  blockSeat: z.object({ success: z.literal(true), seatNumber: z.string() }),
  unblockSeat: z.object({ success: z.literal(true), seatNumber: z.string() }),
  checkIn: z.object({
    seat: z.object({
      id: outputNumber,
      status: z.enum([
        "available",
        "checked_in",
        "occupied",
        "blocked",
        "held",
        "restricted",
      ]),
      createdAt: z.date(),
      updatedAt: z.date(),
      flightId: outputNumber,
      bookingId: z.union([z.null(), outputNumber]),
      cabinClass: z.enum(["economy", "business", "first", "premium_economy"]),
      passengerId: z.union([z.null(), outputNumber]),
      seatNumber: z.string(),
      assignedAt: z.union([z.null(), z.date()]),
      row: outputNumber,
      seatType: z.enum([
        "window",
        "aisle",
        "middle",
        "bulkhead_window",
        "bulkhead_middle",
        "bulkhead_aisle",
        "exit_row_window",
        "exit_row_middle",
        "exit_row_aisle",
      ]),
      column: z.string(),
      hasExtraLegroom: z.boolean(),
      hasPowerOutlet: z.boolean(),
      isReclinable: z.boolean(),
      nearLavatory: z.boolean(),
      nearGalley: z.boolean(),
      priceTier: z.enum([
        "standard",
        "extra_legroom",
        "premium",
        "free",
        "preferred",
      ]),
      seatPrice: outputNumber,
      seatMapId: outputNumber,
      checkedInAt: z.union([z.null(), z.date()]),
      boardingPassIssued: z.boolean(),
      boardingGroup: z.union([z.null(), z.string()]),
      boardingSequence: z.union([z.null(), outputNumber]),
    }),
    boardingGroup: z.string(),
    boardingSequence: outputNumber,
  }),
  undoCheckIn: z.object({ success: z.literal(true), seatNumber: z.string() }),
  getBoardingPass: z.object({
    flightNumber: z.string(),
    airline: z.object({ code: z.string(), name: z.string() }),
    origin: z.object({ code: z.string(), name: z.string(), city: z.string() }),
    destination: z.object({
      code: z.string(),
      name: z.string(),
      city: z.string(),
    }),
    departureTime: z.date(),
    arrivalTime: z.date(),
    passenger: z.object({
      firstName: z.string(),
      lastName: z.string(),
      title: z.union([z.null(), z.string()]),
      ticketNumber: z.union([z.null(), z.string()]),
    }),
    seat: z.object({
      seatNumber: z.string(),
      cabinClass: z.string(),
      boardingGroup: z.union([z.null(), z.string()]),
      boardingSequence: z.union([z.null(), outputNumber]),
    }),
    gate: z.union([z.null(), z.string()]),
    boardingTime: z.union([z.null(), z.date()]),
    barcodeData: z.string(),
    issuedAt: z.date(),
  }),
  getCheckInStatus: z.object({
    flightId: outputNumber,
    totalPassengers: outputNumber,
    checkedIn: outputNumber,
    notCheckedIn: outputNumber,
    boardingPassesIssued: outputNumber,
    byClass: z.array(
      z.object({
        cabinClass: z.string(),
        total: outputNumber,
        checkedIn: outputNumber,
      })
    ),
  }),
  getSeatPricing: z.array(
    z.object({
      priceTier: z.string(),
      cabinClass: z.string(),
      seatPrice: outputNumber,
      availableCount: outputNumber,
      seatNumbers: z.array(z.string()),
    })
  ),
  calculateUpgradePrice: z.object({
    currentSeat: z.object({
      seatNumber: z.string(),
      seatPrice: outputNumber,
      priceTier: z.string(),
      cabinClass: z.string(),
    }),
    newSeat: z.object({
      seatNumber: z.string(),
      seatPrice: outputNumber,
      priceTier: z.string(),
      cabinClass: z.string(),
    }),
    priceDifference: outputNumber,
    isUpgrade: z.boolean(),
  }),
};
