// Explicit response field allowlists. Review contract changes with producers and consumers.
import { z } from "zod";
import { outputNumber } from "./primitives";
export const responseContracts = {
  register: z.object({
    agent: z.object({
      id: outputNumber,
      createdAt: z.date(),
      updatedAt: z.date(),
      email: z.string(),
      isActive: z.boolean(),
      phone: z.string(),
      contactName: z.string(),
      ownerUserId: z.union([z.null(), outputNumber]),
      agencyName: z.string(),
      iataNumber: z.string(),
      commissionRate: z.string(),
      dailyBookingLimit: outputNumber,
      monthlyBookingLimit: outputNumber,
      apiKey: z.string(),
      totalBookings: outputNumber,
      totalRevenue: outputNumber,
      totalCommission: outputNumber,
      lastActiveAt: z.union([z.null(), z.date()]),
    }),
    credentials: z.object({ apiKey: z.string(), apiSecret: z.string() }),
  }),
  list: z.object({
    agents: z.array(
      z.object({
        id: outputNumber,
        createdAt: z.date(),
        updatedAt: z.date(),
        email: z.string(),
        isActive: z.boolean(),
        phone: z.string(),
        contactName: z.string(),
        ownerUserId: z.union([z.null(), outputNumber]),
        agencyName: z.string(),
        iataNumber: z.string(),
        commissionRate: z.string(),
        dailyBookingLimit: outputNumber,
        monthlyBookingLimit: outputNumber,
        apiKey: z.string(),
        totalBookings: outputNumber,
        totalRevenue: outputNumber,
        totalCommission: outputNumber,
        lastActiveAt: z.union([z.null(), z.date()]),
      })
    ),
    total: outputNumber,
  }),
  getById: z.object({
    id: outputNumber,
    createdAt: z.date(),
    updatedAt: z.date(),
    email: z.string(),
    isActive: z.boolean(),
    phone: z.string(),
    contactName: z.string(),
    ownerUserId: z.union([z.null(), outputNumber]),
    agencyName: z.string(),
    iataNumber: z.string(),
    commissionRate: z.string(),
    dailyBookingLimit: outputNumber,
    monthlyBookingLimit: outputNumber,
    apiKey: z.string(),
    totalBookings: outputNumber,
    totalRevenue: outputNumber,
    totalCommission: outputNumber,
    lastActiveAt: z.union([z.null(), z.date()]),
  }),
  regenerateCredentials: z.object({
    apiKey: z.string(),
    apiSecret: z.string(),
  }),
  updateStatus: z.object({ success: z.boolean() }),
  updateCommissionRate: z.object({ success: z.boolean() }),
  getAgentStats: z.object({
    totalBookings: outputNumber,
    totalRevenue: outputNumber,
    totalCommission: outputNumber,
    pendingCommission: outputNumber,
    paidCommission: outputNumber,
    bookingsThisMonth: outputNumber,
    revenueThisMonth: outputNumber,
    commissionThisMonth: outputNumber,
  }),
  getPendingCommissions: z.array(
    z.object({
      id: outputNumber,
      agentId: outputNumber,
      agencyName: z.string(),
      bookingReference: z.string(),
      bookingAmount: outputNumber,
      commissionRate: z.string(),
      commissionAmount: outputNumber,
      createdAt: z.date(),
    })
  ),
  updateCommissionStatus: z.object({ success: z.boolean() }),
  validateCredentials: z.object({
    valid: z.boolean(),
    agentId: outputNumber,
    agencyName: z.string(),
  }),
  searchFlights: z.array(
    z.object({
      id: outputNumber,
      flightNumber: z.string(),
      airline: z.object({ code: z.string(), name: z.string() }),
      origin: z.object({
        code: z.string(),
        name: z.string(),
        city: z.string(),
      }),
      destination: z.object({
        code: z.string(),
        name: z.string(),
        city: z.string(),
      }),
      departureTime: z.date(),
      arrivalTime: z.date(),
      aircraftType: z.union([z.null(), z.string()]),
      availability: z.object({
        economy: z.object({ available: outputNumber, price: outputNumber }),
        business: z.object({ available: outputNumber, price: outputNumber }),
      }),
    })
  ),
  createBooking: z.object({
    bookingId: outputNumber,
    bookingReference: z.string(),
    commission: outputNumber,
  }),
  getBookings: z.object({
    bookings: z.array(
      z.object({
        id: outputNumber,
        bookingId: outputNumber,
        bookingReference: z.string(),
        pnr: z.string(),
        externalReference: z.union([z.null(), z.string()]),
        flightNumber: z.string(),
        departureTime: z.date(),
        arrivalTime: z.date(),
        status: z.enum(["cancelled", "completed", "pending", "confirmed"]),
        paymentStatus: z.enum(["pending", "paid", "refunded", "failed"]),
        cabinClass: z.enum(["economy", "business"]),
        passengers: outputNumber,
        bookingAmount: outputNumber,
        commissionRate: z.string(),
        commissionAmount: outputNumber,
        commissionStatus: z.enum(["cancelled", "pending", "paid", "approved"]),
        createdAt: z.date(),
      })
    ),
    total: outputNumber,
    page: outputNumber,
    limit: outputNumber,
  }),
  calculateCommission: z.object({
    commissionRate: outputNumber,
    commissionAmount: outputNumber,
  }),
  getStats: z.object({
    totalBookings: outputNumber,
    totalRevenue: outputNumber,
    totalCommission: outputNumber,
    pendingCommission: outputNumber,
    paidCommission: outputNumber,
    bookingsThisMonth: outputNumber,
    revenueThisMonth: outputNumber,
    commissionThisMonth: outputNumber,
  }),
  getApiDocumentation: z.object({
    version: z.string(),
    baseUrl: z.string(),
    authentication: z.object({
      type: z.string(),
      description: z.string(),
      example: z.object({ apiKey: z.string() }),
    }),
    endpoints: z.array(
      z.union([
        z.object({
          name: z.string(),
          method: z.string(),
          path: z.string(),
          description: z.string(),
          input: z.object({
            apiKey: z.string(),
            credentials: z.undefined().optional(),
            search: z.undefined().optional(),
            booking: z.undefined().optional(),
            filters: z.undefined().optional(),
            bookingAmount: z.undefined().optional(),
          }),
        }),
        z.object({
          name: z.string(),
          method: z.string(),
          path: z.string(),
          description: z.string(),
          input: z.object({
            credentials: z.string(),
            search: z.object({
              originCode: z.string(),
              destinationCode: z.string(),
              departureDate: z.string(),
              returnDate: z.string(),
              cabinClass: z.string(),
              passengers: z.string(),
            }),
            apiKey: z.undefined().optional(),
            booking: z.undefined().optional(),
            filters: z.undefined().optional(),
            bookingAmount: z.undefined().optional(),
          }),
        }),
        z.object({
          name: z.string(),
          method: z.string(),
          path: z.string(),
          description: z.string(),
          input: z.object({
            credentials: z.string(),
            booking: z.object({
              flightId: z.string(),
              cabinClass: z.string(),
              passengers: z.string(),
              externalReference: z.string(),
              contactEmail: z.string(),
              contactPhone: z.string(),
            }),
            apiKey: z.undefined().optional(),
            search: z.undefined().optional(),
            filters: z.undefined().optional(),
            bookingAmount: z.undefined().optional(),
          }),
        }),
        z.object({
          name: z.string(),
          method: z.string(),
          path: z.string(),
          description: z.string(),
          input: z.object({
            credentials: z.string(),
            filters: z.object({
              status: z.string(),
              startDate: z.string(),
              endDate: z.string(),
              page: z.string(),
              limit: z.string(),
            }),
            apiKey: z.undefined().optional(),
            search: z.undefined().optional(),
            booking: z.undefined().optional(),
            bookingAmount: z.undefined().optional(),
          }),
        }),
        z.object({
          name: z.string(),
          method: z.string(),
          path: z.string(),
          description: z.string(),
          input: z.object({
            credentials: z.string(),
            bookingAmount: z.string(),
            apiKey: z.undefined().optional(),
            search: z.undefined().optional(),
            booking: z.undefined().optional(),
            filters: z.undefined().optional(),
          }),
        }),
        z.object({
          name: z.string(),
          method: z.string(),
          path: z.string(),
          description: z.string(),
          input: z.object({
            credentials: z.string(),
            apiKey: z.undefined().optional(),
            search: z.undefined().optional(),
            booking: z.undefined().optional(),
            filters: z.undefined().optional(),
            bookingAmount: z.undefined().optional(),
          }),
        }),
      ])
    ),
    rateLimits: z.object({
      daily: z.string(),
      monthly: z.string(),
      api: z.string(),
    }),
    errors: z.object({
      UNAUTHORIZED: z.string(),
      NOT_FOUND: z.string(),
      BAD_REQUEST: z.string(),
      TOO_MANY_REQUESTS: z.string(),
    }),
  }),
};
