// Explicit response field allowlists. Review contract changes with producers and consumers.
import { z } from "zod";
import { outputNumber } from "./primitives";
export const responseContracts = {
  getMyPreferences: z.union([
    z.null(),
    z.object({
      id: outputNumber,
      createdAt: z.date(),
      updatedAt: z.date(),
      userId: outputNumber,
      passportNumber: z.union([z.null(), z.string()]),
      passportExpiry: z.union([z.null(), z.date()]),
      nationality: z.union([z.null(), z.string()]),
      preferredSeatType: z.union([
        z.null(),
        z.literal("window"),
        z.literal("aisle"),
        z.literal("middle"),
      ]),
      preferredCabinClass: z.union([
        z.null(),
        z.literal("economy"),
        z.literal("business"),
        z.literal("first"),
      ]),
      mealPreference: z.union([
        z.null(),
        z.literal("regular"),
        z.literal("vegetarian"),
        z.literal("vegan"),
        z.literal("halal"),
        z.literal("kosher"),
        z.literal("gluten_free"),
      ]),
      wheelchairAssistance: z.boolean(),
      extraLegroom: z.boolean(),
      phoneNumber: z.union([z.null(), z.string()]),
      emergencyContact: z.union([z.null(), z.string()]),
      emergencyPhone: z.union([z.null(), z.string()]),
      emailNotifications: z.boolean(),
      smsNotifications: z.boolean(),
      autoCheckIn: z.boolean(),
    }),
  ]),
  updateMyPreferences: z.object({
    id: outputNumber,
    createdAt: z.date(),
    updatedAt: z.date(),
    userId: outputNumber,
    passportNumber: z.union([z.null(), z.string()]),
    passportExpiry: z.union([z.null(), z.date()]),
    nationality: z.union([z.null(), z.string()]),
    preferredSeatType: z.union([
      z.null(),
      z.literal("window"),
      z.literal("aisle"),
      z.literal("middle"),
    ]),
    preferredCabinClass: z.union([
      z.null(),
      z.literal("economy"),
      z.literal("business"),
      z.literal("first"),
    ]),
    mealPreference: z.union([
      z.null(),
      z.literal("regular"),
      z.literal("vegetarian"),
      z.literal("vegan"),
      z.literal("halal"),
      z.literal("kosher"),
      z.literal("gluten_free"),
    ]),
    wheelchairAssistance: z.boolean(),
    extraLegroom: z.boolean(),
    phoneNumber: z.union([z.null(), z.string()]),
    emergencyContact: z.union([z.null(), z.string()]),
    emergencyPhone: z.union([z.null(), z.string()]),
    emailNotifications: z.boolean(),
    smsNotifications: z.boolean(),
    autoCheckIn: z.boolean(),
  }),
  deleteMyPreferences: z.object({ success: z.boolean() }),
  getSavedPassport: z.union([
    z.null(),
    z.object({
      passportNumber: z.union([z.null(), z.string()]),
      passportExpiry: z.union([z.null(), z.date()]),
      nationality: z.union([z.null(), z.string()]),
    }),
  ]),
  updatePassport: z.object({ success: z.boolean() }),
  getNotificationSettings: z.object({
    emailNotifications: z.boolean(),
    smsNotifications: z.boolean(),
  }),
  updateNotificationSettings: z.object({ success: z.boolean() }),
};
