// Explicit response field allowlists. Review contract changes with producers and consumers.
import { z } from "zod";
import { outputNumber } from "./primitives";
export const responseContracts = {
  validate: z.object({
    valid: z.boolean(),
    voucher: z.object({
      id: outputNumber,
      code: z.string(),
      type: z.enum(["fixed", "percentage"]),
      value: outputNumber,
      minPurchase: outputNumber,
      maxDiscount: z.union([z.null(), outputNumber]),
      maxUses: z.union([z.null(), outputNumber]),
      usedCount: outputNumber,
      validFrom: z.date(),
      validUntil: z.date(),
      isActive: z.boolean(),
      description: z.union([z.null(), z.string()]),
      createdBy: z.union([z.null(), outputNumber]),
      createdAt: z.date(),
      updatedAt: z.date(),
    }),
    discountAmount: outputNumber,
    finalAmount: outputNumber,
  }),
  applyVoucher: z.object({
    success: z.boolean(),
    discountApplied: outputNumber,
    finalAmount: outputNumber,
    voucherCode: z.string(),
  }),
  myCredits: z.object({
    balance: outputNumber,
    credits: z.array(
      z.object({
        id: outputNumber,
        amount: outputNumber,
        usedAmount: outputNumber,
        available: outputNumber,
        source: z.enum(["refund", "bonus", "promo", "compensation"]),
        expiresAt: z.union([z.null(), z.date()]),
        description: z.union([z.null(), z.string()]),
      })
    ),
  }),
  myCreditHistory: z.array(
    z.object({
      id: outputNumber,
      userId: outputNumber,
      amount: outputNumber,
      source: z.enum(["refund", "bonus", "promo", "compensation"]),
      description: z.union([z.null(), z.string()]),
      expiresAt: z.union([z.null(), z.date()]),
      usedAmount: outputNumber,
      bookingId: z.union([z.null(), outputNumber]),
      createdBy: z.union([z.null(), outputNumber]),
      createdAt: z.date(),
      updatedAt: z.date(),
    })
  ),
  myCreditUsage: z.array(
    z.object({
      id: outputNumber,
      userCreditId: outputNumber,
      userId: outputNumber,
      bookingId: outputNumber,
      amountUsed: outputNumber,
      usedAt: z.date(),
    })
  ),
  useCredits: z.object({
    success: z.boolean(),
    amountUsed: outputNumber,
    usages: z.array(z.object({ creditId: outputNumber, amount: outputNumber })),
  }),
  create: z.object({
    id: outputNumber,
    code: z.string(),
    type: z.enum(["fixed", "percentage"]),
    value: outputNumber,
    minPurchase: outputNumber,
    maxDiscount: z.union([z.null(), outputNumber]),
    maxUses: z.union([z.null(), outputNumber]),
    usedCount: outputNumber,
    validFrom: z.date(),
    validUntil: z.date(),
    isActive: z.boolean(),
    description: z.union([z.null(), z.string()]),
    createdBy: z.union([z.null(), outputNumber]),
    createdAt: z.date(),
    updatedAt: z.date(),
  }),
  getAll: z.array(
    z.object({
      id: outputNumber,
      code: z.string(),
      type: z.enum(["fixed", "percentage"]),
      value: outputNumber,
      minPurchase: outputNumber,
      maxDiscount: z.union([z.null(), outputNumber]),
      maxUses: z.union([z.null(), outputNumber]),
      usedCount: outputNumber,
      validFrom: z.date(),
      validUntil: z.date(),
      isActive: z.boolean(),
      description: z.union([z.null(), z.string()]),
      createdBy: z.union([z.null(), outputNumber]),
      createdAt: z.date(),
      updatedAt: z.date(),
    })
  ),
  getById: z.object({
    id: outputNumber,
    code: z.string(),
    type: z.enum(["fixed", "percentage"]),
    value: outputNumber,
    minPurchase: outputNumber,
    maxDiscount: z.union([z.null(), outputNumber]),
    maxUses: z.union([z.null(), outputNumber]),
    usedCount: outputNumber,
    validFrom: z.date(),
    validUntil: z.date(),
    isActive: z.boolean(),
    description: z.union([z.null(), z.string()]),
    createdBy: z.union([z.null(), outputNumber]),
    createdAt: z.date(),
    updatedAt: z.date(),
  }),
  update: z.object({
    id: outputNumber,
    code: z.string(),
    type: z.enum(["fixed", "percentage"]),
    value: outputNumber,
    minPurchase: outputNumber,
    maxDiscount: z.union([z.null(), outputNumber]),
    maxUses: z.union([z.null(), outputNumber]),
    usedCount: outputNumber,
    validFrom: z.date(),
    validUntil: z.date(),
    isActive: z.boolean(),
    description: z.union([z.null(), z.string()]),
    createdBy: z.union([z.null(), outputNumber]),
    createdAt: z.date(),
    updatedAt: z.date(),
  }),
  deactivate: z.object({
    id: outputNumber,
    code: z.string(),
    type: z.enum(["fixed", "percentage"]),
    value: outputNumber,
    minPurchase: outputNumber,
    maxDiscount: z.union([z.null(), outputNumber]),
    maxUses: z.union([z.null(), outputNumber]),
    usedCount: outputNumber,
    validFrom: z.date(),
    validUntil: z.date(),
    isActive: z.boolean(),
    description: z.union([z.null(), z.string()]),
    createdBy: z.union([z.null(), outputNumber]),
    createdAt: z.date(),
    updatedAt: z.date(),
  }),
  getUsageHistory: z.array(
    z.object({
      id: outputNumber,
      voucherId: outputNumber,
      userId: outputNumber,
      bookingId: outputNumber,
      discountApplied: outputNumber,
      usedAt: z.date(),
    })
  ),
  addCredit: z.object({
    id: outputNumber,
    userId: outputNumber,
    amount: outputNumber,
    source: z.enum(["refund", "bonus", "promo", "compensation"]),
    description: z.union([z.null(), z.string()]),
    expiresAt: z.union([z.null(), z.date()]),
    usedAmount: outputNumber,
    bookingId: z.union([z.null(), outputNumber]),
    createdBy: z.union([z.null(), outputNumber]),
    createdAt: z.date(),
    updatedAt: z.date(),
  }),
  getUserCredits: z.object({
    balance: outputNumber,
    credits: z.array(
      z.object({
        id: outputNumber,
        amount: outputNumber,
        usedAmount: outputNumber,
        available: outputNumber,
        source: z.enum(["refund", "bonus", "promo", "compensation"]),
        expiresAt: z.union([z.null(), z.date()]),
        description: z.union([z.null(), z.string()]),
      })
    ),
  }),
  getAllCredits: z.array(
    z.object({
      id: outputNumber,
      userId: outputNumber,
      amount: outputNumber,
      source: z.enum(["refund", "bonus", "promo", "compensation"]),
      description: z.union([z.null(), z.string()]),
      expiresAt: z.union([z.null(), z.date()]),
      usedAmount: outputNumber,
      bookingId: z.union([z.null(), outputNumber]),
      createdBy: z.union([z.null(), outputNumber]),
      createdAt: z.date(),
      updatedAt: z.date(),
    })
  ),
  processExpiredCredits: z.object({ processedCount: outputNumber }),
};
