// Explicit response field allowlists. Review contract changes with producers and consumers.
import { z } from "zod";
import { outputNumber } from "./primitives";
export const responseContracts = {
  calculate: z.object({
    id: outputNumber,
    flightId: outputNumber,
    aircraftTypeId: outputNumber,
    operatingEmptyWeight: outputNumber,
    passengerWeight: outputNumber,
    baggageWeight: outputNumber,
    cargoWeight: outputNumber,
    fuelWeight: outputNumber,
    totalWeight: outputNumber,
    maxTakeoffWeight: outputNumber,
    cgPosition: outputNumber,
    cgForwardLimit: outputNumber,
    cgAftLimit: outputNumber,
    isWithinLimits: z.boolean(),
    trimSetting: outputNumber,
    status: z.enum(["amended", "preliminary", "final"]),
    calculatedBy: outputNumber,
    calculatedAt: z.date(),
    createdAt: z.date(),
    updatedAt: z.date(),
    details: z.object({
      aircraft: z.object({
        code: z.string(),
        name: z.string(),
        limits: z.object({
          mtow: outputNumber,
          mlw: outputNumber,
          mzfw: outputNumber,
          oew: outputNumber,
          maxPayload: outputNumber,
          maxFuel: outputNumber,
        }),
      }),
      weights: z.object({
        operatingEmpty: outputNumber,
        passengers: z.object({
          count: outputNumber,
          weight: outputNumber,
          breakdown: z.object({
            males: z.object({ count: outputNumber, weight: outputNumber }),
            females: z.object({ count: outputNumber, weight: outputNumber }),
            children: z.object({ count: outputNumber, weight: outputNumber }),
            infants: z.object({ count: outputNumber, weight: outputNumber }),
          }),
        }),
        baggage: z.object({
          checkedCount: outputNumber,
          checkedWeight: outputNumber,
          carryOnCount: outputNumber,
          totalWeight: outputNumber,
        }),
        cargo: z.object({
          zones: z.array(z.object({ zone: z.string(), weight: outputNumber })),
          totalWeight: outputNumber,
        }),
        fuel: z.object({
          totalFuelWeight: outputNumber,
          breakdown: z.object({
            taxiFuel: outputNumber,
            tripFuel: outputNumber,
            contingency: outputNumber,
            alternateFuel: outputNumber,
            finalReserve: outputNumber,
            extraFuel: outputNumber,
          }),
          fuelDensity: outputNumber,
        }),
        zeroFuel: outputNumber,
        takeoff: outputNumber,
        landing: outputNumber,
      }),
      balance: z.object({
        cgPosition: outputNumber,
        forwardLimit: outputNumber,
        aftLimit: outputNumber,
        trimSetting: outputNumber,
      }),
      isWithinLimits: z.boolean(),
    }),
  }),
  getFlightWB: z.union([
    z.null(),
    z.object({
      id: outputNumber,
      flightId: outputNumber,
      aircraftTypeId: outputNumber,
      operatingEmptyWeight: outputNumber,
      passengerWeight: outputNumber,
      baggageWeight: outputNumber,
      cargoWeight: outputNumber,
      fuelWeight: outputNumber,
      totalWeight: outputNumber,
      maxTakeoffWeight: outputNumber,
      cgPosition: outputNumber,
      cgForwardLimit: outputNumber,
      cgAftLimit: outputNumber,
      isWithinLimits: z.boolean(),
      trimSetting: outputNumber,
      status: z.enum(["amended", "preliminary", "final"]),
      calculatedBy: outputNumber,
      calculatedAt: z.date(),
      createdAt: z.date(),
      updatedAt: z.date(),
    }),
  ]),
  getAircraftLimits: z.object({
    id: outputNumber,
    aircraftTypeId: outputNumber,
    maxTakeoffWeight: outputNumber,
    maxLandingWeight: outputNumber,
    maxZeroFuelWeight: outputNumber,
    operatingEmptyWeight: outputNumber,
    maxPayload: outputNumber,
    maxFuelCapacity: outputNumber,
    maxPassengers: outputNumber,
    standardMaleWeight: outputNumber,
    standardFemaleWeight: outputNumber,
    standardChildWeight: outputNumber,
    standardInfantWeight: outputNumber,
    standardBagWeight: outputNumber,
    createdAt: z.date(),
    updatedAt: z.date(),
  }),
  updateAircraftLimits: z.object({
    id: outputNumber,
    aircraftTypeId: outputNumber,
    maxTakeoffWeight: outputNumber,
    maxLandingWeight: outputNumber,
    maxZeroFuelWeight: outputNumber,
    operatingEmptyWeight: outputNumber,
    maxPayload: outputNumber,
    maxFuelCapacity: outputNumber,
    maxPassengers: outputNumber,
    standardMaleWeight: outputNumber,
    standardFemaleWeight: outputNumber,
    standardChildWeight: outputNumber,
    standardInfantWeight: outputNumber,
    standardBagWeight: outputNumber,
    createdAt: z.date(),
    updatedAt: z.date(),
  }),
  generateLoadSheet: z.object({
    loadSheetNumber: z.string(),
    edition: z.string(),
    generatedAt: z.string(),
    flight: z.object({
      id: outputNumber,
      flightNumber: z.string(),
      date: z.string(),
      origin: z.string(),
      destination: z.string(),
      aircraftType: z.string(),
      registration: z.string(),
    }),
    crew: z.object({
      cockpit: outputNumber,
      cabin: outputNumber,
      total: outputNumber,
    }),
    passengers: z.object({
      males: outputNumber,
      females: outputNumber,
      children: outputNumber,
      infants: outputNumber,
      totalExcludingInfants: outputNumber,
      total: outputNumber,
    }),
    weights: z.object({
      operatingEmptyWeight: outputNumber,
      passengerWeight: outputNumber,
      baggageWeight: outputNumber,
      cargoMailWeight: outputNumber,
      totalTrafficLoad: outputNumber,
      dryOperatingWeight: outputNumber,
      zeroFuelWeightActual: outputNumber,
      zeroFuelWeightMax: outputNumber,
      takeoffFuel: outputNumber,
      takeoffWeightActual: outputNumber,
      takeoffWeightMax: outputNumber,
      tripFuel: outputNumber,
      landingWeightActual: outputNumber,
      landingWeightMax: outputNumber,
    }),
    balance: z.object({
      cgPercent: outputNumber,
      cgForwardLimit: outputNumber,
      cgAftLimit: outputNumber,
      trimSetting: outputNumber,
      stabilizerSetting: outputNumber,
    }),
    cargoByZone: z.array(
      z.object({
        zone: z.string(),
        weight: outputNumber,
        maxWeight: outputNumber,
      })
    ),
    limitations: z.object({
      isWithinAllLimits: z.boolean(),
      items: z.array(z.string()),
    }),
    remarks: z.array(z.string()),
  }),
  checkLimits: z.object({
    isWithinAllLimits: z.boolean(),
    checks: z.array(
      z.object({
        name: z.string(),
        actual: outputNumber,
        limit: outputNumber,
        unit: z.string(),
        passed: z.boolean(),
        margin: outputNumber,
      })
    ),
    warnings: z.array(z.string()),
    errors: z.array(z.string()),
  }),
  getHistory: z.array(
    z.object({
      id: outputNumber,
      status: z.string(),
      passengerCount: outputNumber,
      passengerWeight: outputNumber,
      baggageWeight: outputNumber,
      cargoWeight: outputNumber,
      fuelWeight: outputNumber,
      zeroFuelWeight: outputNumber,
      takeoffWeight: outputNumber,
      landingWeight: outputNumber,
      cgPosition: z.union([z.null(), z.string()]),
      withinLimits: z.boolean(),
      warnings: z.array(z.string()),
      createdAt: z.date(),
    })
  ),
};
